### ISSUE TITLE
Broken link in Cron plugin page

### ISSUE THREAD

**Issue by kansi** [hexpm/hexpm#1007]
https://hexdocs.pm/oban/Oban.Plugins.Cron.html#content
![image](https://user-images.githubusercontent.com/4709940/108493631-d3e3ee80-72a6-11eb-90e4-be6fa3de4482.png)

`Peridoic Jobs` link is broken

**Comment by ericmj** [comment]
Hex packages maintain their own docs, please open this issue on: https://github.com/sorentwo/oban.

**Comment by sorentwo** [comment]
@kansi I happen to watch this repo and noticed the issue. Fixed with https://github.com/sorentwo/oban/commit/8708dd33b7bbca01262b50a3dd56b44087170047
