### ISSUE TITLE
hexpm returns a 400 when an invalid semver is provided for revertion 

### ISSUE THREAD

**Issue by starbelly** [hexpm/hexpm#1015]
If an invalid semver is provided as an argument when attempting to revert a package (i.e., "eh?") hexpm will return a 400 vs a useful message stating why it the operation failed. 

Happy to provide a PR on this as soon as possible.

**Comment by wojtekmach** [comment]
could you paste the whole error? We should include in the response body something like `"version": "is invalid"` but we probably aren't and that's the crux, but just double checking.

**Comment by starbelly** [comment]
The raw error as returned by hex_core is : 

```
{error,{rebar3_hex_revert,{api_error,<<"truecoat">>,<<"me">>,[72,84,84,80,32,115,116,97,116,117,115,32,99,111,100,101,58,32,"400"]
}}}
```

But what you I see adding an IO.inspect/1 call in the release controller in hexpm is : 

```
{:error, :release,
 #Ecto.Changeset<
   action: :delete,
   changes: %{},
   errors: [
     inserted_at: {"can only delete a release up to one hour after publication",
      []}
   ],
   data: #Hexpm.Repository.Release<>,
   valid?: false
 >, %{}}
[info] state=set duration=14.691 status=422 path=/api/packages/truecoat/releases/0.42.42 method=DELETE format=erlang controller=HexpmWeb.API.ReleaseController action=delete
```

**Comment by starbelly** [comment]
To note I've created this PR for rebar3_hex as I do feel this should be dealt with before making it to the server : https://github.com/tsloughter/rebar3_hex/pull/216

**Comment by wojtekmach** [comment]
right, this changeset error should result in a decent enough response error, it's either incorrectly encoded on the server or, more likely, we simply don't show error body on hex_core which is definitely a bug. If the latter, do you mind moving this to hex_core?
