### ISSUE TITLE
Add info about :text type to Ecto docs

### ISSUE THREAD

**Issue by istudyatuni** [hexpm/hexpm#1017]
In the new version of the documentation no information about this type `:text`, but here https://hexdocs.pm/ecto/2.2.12/Ecto.Migration.html#module-field-types it is. Yes, this is another part that is not in the new version of documentation, but it works!
I'm using postresql, and this type create type `text` in database

**Comment by istudyatuni** [comment]
Sorry, if I opened this issue in the wrong place, I go here with "IS SOMETHING WRONG? LET US KNOW BY OPENING AN ISSUE"

**Comment by wojtekmach** [comment]
The :text type is mentioned on https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-field-types. If you have ideas how to improve the docs for that module, please send PRs to https://github.com/elixir-ecto/ecto_sql.

In the future please remember that hex.pm, hexdocs.pm, etc are hosting the packages but Hex is not responsible for actual contents. If you find bugs, please report them in corresponding repositories. Thanks!

**Comment by istudyatuni** [comment]
I'll know! Thanks for the super fast reply)
