### ISSUE TITLE
New version of package not found in registry

### ISSUE THREAD

**Issue by Katur7** [hexpm/hexpm#1021]
Hi,

I'm trying to update to the latest version of gproc, 0.9.0.
I can see it's available on the website, [https://hex.pm/packages/gproc/versions](https://hex.pm/packages/gproc/versions)

But when I try updating the version in my rebar.config and running ./rebar3 upgrade gproc I get the following error:
===> Package not found in registry: gproc-0.9.0.

When I tried it with the DEBUG=1 flag I got the following:
===> Package gproc-0.9.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Fetching registry from "https://repo.hex.pm:443/registry.ets.gz?"

So I tried downloading the file and loading the ETS table. When I lookup gproc in the table I cannot find the latest version
```
7> ets:lookup(Tab, <<"gproc">>).
[{<<"gproc">>,
  [[<<"0.3.0">>,<<"0.3.1">>,<<"0.5.0">>,<<"0.6.1">>,
    <<"0.8.0">>]]}]
```

Is it possible to add the latest version to the registry?

**Comment by ferd** [comment]
No, you're apparently on a very, very old version of rebar3. That's the registry version 1.0.0, and it's been fully removed in January this year by hex.pm, outside of our control. The hex v2 registry format (which we're now using) was introduced to Rebar3 in version 3.7.0, back in November 2018 (and had been around for longer in Hex).

**Comment by wojtekmach** [comment]
Yup, what @ferd said. Please update your rebar3!

> That's the registry version 1.0.0, and it's been fully removed in January this year by hex.pm, outside of our control. 

To be precise the old registry has not been removed but since a year or so ago it was deprecated and stopped being updated.

**Comment by Katur7** [comment]
I see.

I will update our version of rebar3.

Thank you :)
