### ISSUE TITLE
HTTP 400 response if checking for license information

### ISSUE THREAD

**Issue by obo-spi** [hexpm/hexpm#1022]
We check for licenses in our build pipeline.

This we do querying packages in the following way: 'https://hex.pm/api/packages/packagename'

But we receive:
Error fetching elixir package for HTTP Error 400: Bad Request

This now happens for our pipeline server, but locally I can run the license checking tool.

Any idea? Are our servers banned somehow. Do you implement rate limits or similar?

**Comment by ericmj** [comment]
We do have rate limiting and some automatic blocking but that would give you a 429 or 403 error. Is there any information in the response body? Can you give us an example request that fails?

**Comment by obo-spi** [comment]
This one fails

https://hex.pm/api/packages/phoenix_pubsub

**Comment by wojtekmach** [comment]
please paste the response body. ideally please paste how exactly you're making the http request as well.

**Comment by obo-spi** [comment]
Ouch think this is part of the solution:

```
{"message":"User-Agent header is required","status":400}
```

Sorry for being that noob. Any wish what you expect from a CI build server?

**Comment by obo-spi** [comment]
After sending an user-agent on the build server we receive

```
{"message":"invalid API key","status":401}
```

But locally all works fine. Any hint?

**Comment by obo-spi** [comment]
We're making the requests with python (wish it were elixir, but legacy forced us ...)

```
                url = f'https://hex.pm/api/packages/{self.package_name}'
                headers = {
                    'user-agent': 'any',
                }
                req = urllib.request.Request(url, None, headers)
                response = urllib.request.urlopen(req)
```

**Comment by ericmj** [comment]
I can only give the same advice as in the error message, you are sending an invalid API key, so you need to send a valid API key or no key. The key is supplied in the `authorization` header.

**Comment by wojtekmach** [comment]
btw, if you're hitting the API just to get the information about the licenses, there's a potentially easier way to get the same outcome. Each fetched dependency has a `hex_metadata.config` file that contains the license.

```
$ cd src/ecto
$ mix deps.get
$ elixir -e 'for path <- Path.wildcard("deps/**/hex_metadata.config") do {:ok, contents} = :file.consult(path) ; map = Map.new(contents); IO.inspect(map["licenses"], label: map["name"]) end'
decimal: ["Apache 2.0"]
earmark_parser: ["Apache-2.0"]
ex_doc: ["Apache-2.0"]
jason: ["Apache 2.0"]
makeup: ["BSD"]
makeup_elixir: ["BSD"]
makeup_erlang: ["BSD"]
nimble_parsec: ["Apache 2"]
telemetry: ["Apache 2.0"]
```

I think someone might even created a package that extract the licenses like that.

**Comment by obo-spi** [comment]
Thanks so much. This helped!

**Comment by obo-spi** [comment]
Above solved
