### ISSUE TITLE
Channels documentation around incoming events is out of step with code examples

### ISSUE THREAD

**Issue by robertkeizer** [hexpm/hexpm#1025]
It appears as though the code example and the written documentation relating to [Incoming Events]( https://hexdocs.pm/phoenix/channels.html#incoming-events) has diverged slightly. The documentation makes reference to `handle_out/3` and explains the default behaviour, even stipulating the following:

> We included it here because hooking into outgoing events allows for powerful message customization and filtering. 

The code example does not contain a definition for `handle_out/3`.

**Comment by wojtekmach** [comment]
Hex is about hosting packages and their docs but not about the contents themselves, please reopen the issue on the package repo. Thanks!
