### ISSUE TITLE
Notes on installing a dependency from a GitHub release tag

### ISSUE THREAD

**Issue by thbar** [hexpm/hexpm#1040]
Hello,

Today while doing maintenance work (upgrade to Elixir 1.12 and OTP 24), I met one case https://github.com/mochi/mochiweb/issues/233 where a library is tagged on GitHub but the package is not yet available on Hex.pm.

I searched for the correct way to declare that in `mix.exs`, initially on https://hex.pm/docs/usage, but I could not find a snippet showing how to do that on that page.

I was pretty sure it was doable, and did a bit of code search inside Hex.pm, and ended up on this:

https://github.com/hexpm/hex/blob/cf0b48d09b31312c574ec3ad57ef69278e66ff46/mix.exs#L43

I also had to use `override: true`, because `mochiweb` is not used directly by the app, but by a dependency, which specifies something a bit different (see https://github.com/etalab/transport-site/commit/9771d96029da4c8f8f02e96d4d34204234424492).

This leads me to 2 questions:
- Is https://hex.pm/docs/usage the real documentation, or only a quick first guide? Should it detail those options directly, so that a newcomer can go faster & be less confused? Or is the information somewhere else already?
- I do understand the `override: true` bit, yet something feels off in that case. Maybe I would expect the system to solely rely on the version specifier that we may pass here (like Bundler does if I recall well), which would be enough to determine if the compatibility is met. I am not actually breaking the requirement, but I could unexpectedly end up breaking it later if I forget to remove the `override: true`.

As a sidenote, I could not initially find a trace of the version in the `mochiweb` repository, and wondered if this information was versioned at all, or passed at release time by the maintainer, but ultimately found that it is indeed stored in the repo:
- https://diff.hex.pm/diff/mochiweb/2.20.0..2.20.1
- https://github.com/mochi/mochiweb/blob/master/src/mochiweb.app.src

Surfacing this information in the usage guide could probably help maintain apps for people (like me) who are not super familiar with Erlang.

The goal of this issue is just to start a discussion on this and make sure the information is more accessible to new users!

**Comment by ericmj** [comment]
https://hex.pm only documents how to use Hex packages, when fetching dependencies with git or other ways Hex packages are not used. To learn how to fetch other kinds of dependencies you need to look at the documentation of your build tool, for Elixir/Mix that's here: https://hexdocs.pm/mix/Mix.Tasks.Deps.html.

**Comment by thbar** [comment]
@ericmj this makes sense. Thanks for adding the extra link & for the explanation!
