### ISSUE TITLE
Emails end up in spam, SPF doesn't match

### ISSUE THREAD

**Issue by jeroenvisser101** [hexpm/hexpm#1041]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/1941348/125212167-e7224580-e2ab-11eb-8c2b-52def304b67d.png">

It's weird, as this IPv6 address seems to belong to Google, but the headers of the email seem to suggest it was sent using AmazonSES (which is also configured on hex.pm to be permitted sender).

I can provide the full headers via email if this is of any help.

**Comment by ericmj** [comment]
What kind of email is this?

We send emails from both Google and AmazonSES and include both in the SPF DNS record:

```
> host -t TXT hex.pm
[...]
hex.pm descriptive text "v=spf1 include:amazonses.com include:_spf.google.com ~all"
```

**Comment by jeroenvisser101** [comment]
I've sent you the email with headers. It's the mail that is sent after a package is published, I noticed it mentions a Google domain that is used for unverified forwarding (unverified-forwarding.1e100.net).

**Comment by ericmj** [comment]
unverified-forwarding.1e100.net seems to be the sender when you have forwarding rules in Gmail. The receiving email server is trying to verify the IP of unverified-forwarding.1e100.net against the SPF record which fails. I don't know much about SPF but I don't think it should do that, it should verify against the original sender.

Have you set up forwarding rules in Gmail? What email provider are you using or rather, who is saying that SPF check failed?

**Comment by jeroenvisser101** [comment]
I think it may have been due to a catch-all rule I set up, so that may be the forwarding part. Will check. This is all G Suite for Work  (or Google Workspace or whatever branding they use nowadays)
