### ISSUE TITLE
Package description not reverted when reverting a version

### ISSUE THREAD

**Issue by thiamsantos** [hexpm/hexpm#1042]
## Current behavior

When reverting a package version using `mix hex.publish --revert VERSION` the package description is not reverted, keeping the description present in the reverted version. I don't know for sure if it affects any other values. 

Steps to reproduce:

- Publish a package
- Update the description in `mix.exs`
- Publish a new version with the updated description
- Revert the just published version with `mix hex.publish --revert VERSION` 
- Open the package page on hex.pm, the description will be the one present in the reverted version, and not in the previous version

## Expected behavior

The description of the package in hex.pm to be reverted to the previous version, before the version that was reverted.

**Comment by ericmj** [comment]
This may be a wont fix, because it's not easy to fix and not 100% clear which version's description should be used instead.

**Comment by thiamsantos** [comment]
> This may be a wont fix

I think that's okay as needing reverting a version is not that common. But would be nice to have it documented at https://hexdocs.pm/hex/Mix.Tasks.Hex.Publish.html#module-reverting-a-package. PRs are welcome for it?

> because it's not easy to fix and not 100% clear which version's description should be used instead

Just out of curiosity, why this is a hard thing to accomplish? We couldn't get the description of the most recent version description after the revert?

**Comment by ericmj** [comment]
> I think that's okay as needing reverting a version is not that common. But would be nice to have it documented at https://hexdocs.pm/hex/Mix.Tasks.Hex.Publish.html#module-reverting-a-package. PRs are welcome for it?

I think it's too small of detail to document, we don't want to add information to the documentation that is only useful in very rare circumstances.

> Just out of curiosity, why this is a hard thing to accomplish? We couldn't get the description of the most recent version description after the revert?

It's not clear which package to use. Should it be the most recently published package or the one with the highest version, what if the version is pre-release or if the version has been retired?

It's not just the description that is the issue, it's all fields here https://github.com/hexpm/hexpm/blob/main/lib/hexpm/repository/package_metadata.ex#L7-L11. Currently we do not store this information per release so we would either have to redownload the package tarball to parse the metadata again or duplicate it to store per release.
