### ISSUE TITLE
Read only tokens for private packages

### ISSUE THREAD

**Issue by girishramnani** [hexpm/hexpm#1056]
It would be great if we can have tokens that just have read capabilities to private packages. It reduces risk even if the token gets exposed and also allows easier distribution of the token in the team.

**Comment by ericmj** [comment]
That exists or were you thinking of something else? https://hex.pm/dashboard/

<img width="728" alt="Screenshot 2021-09-10 at 08 54 24" src="https://user-images.githubusercontent.com/316890/132864378-79483b5f-302d-4f29-a4dd-ec07fa8aa7a1.png">

You can also generate it with the CLI: `mix hex.organization key myorg generate --permission repository`.

It is very strongly recommended to not share authentication tokens though. Everyone in your team should have their own accounts (also note this is required by the terms of service) with their own tokens that are not shared. For tokens that need to be shared, such as for CI, they should be encrypted and not be able to be read.

**Comment by girishramnani** [comment]
Ack. Closing

**Comment by girishramnani** [comment]
Thanks for the quick reply
