### ISSUE TITLE
Download graph on all packages pages have stopped working

### ISSUE THREAD

**Issue by aesmail** [hexpm/hexpm#1068]
Hello,
I'm not sure if this is the correct place, but apparently the downloads graph for all packages on hex.pm stopped updating a few days ago.
Image attached:

![Screen Shot 2021-11-03 at 09 48 10](https://user-images.githubusercontent.com/602354/140019348-87e02f30-fa58-4f32-b768-9a07cb7d42d9.png)

**Comment by ericmj** [comment]
Fixed now. Thanks for letting us know.
