### ISSUE TITLE
Unable to add/persist payment method for an organization account

### ISSUE THREAD

**Issue by thebugcatcher** [hexpm/hexpm#1070]
We have been on Hex.PM for 30 days (free trial) and I'm unable to add new payment method to continue our subscription. Clicking "Add payment method" does show a form, but submitting the form along with the payment method doesn't do anything. It also doesn't show any error message.

![Screenshot from 2021-11-06 19-37-50](https://user-images.githubusercontent.com/10440910/140626943-0c5afc72-6b36-497b-9685-82515b74022a.png)
![Screenshot from 2021-11-06 19-38-28](https://user-images.githubusercontent.com/10440910/140626947-07db65a0-ad93-4305-9d1f-da5366dc5d30.png)

Any help would be greatly appreciated!

**Comment by ericmj** [comment]
Hi Adi!

Thanks for the report. A javascript bug caused the stripe callback not to trigger. It should be fixed now: https://github.com/hexpm/hexpm/commit/94b7e0c31d75a232da1987a46ae7fd3ba6f8fd1f.

Closing the issue but let me know if you are still having issues.

**Comment by thebugcatcher** [comment]
Hey @ericmj! Thanks a lot for the quick fix :+1:
