### ISSUE TITLE
What happened to downloads

### ISSUE THREAD

**Issue by nacengineer** [hexpm/hexpm#1102]
Apologies for posting as an issue but I have no twitter. 

On hex.pm I notice that the download graph for all the projects all go off a cliff a few days ago and crash to zero. 

Is this a bug in hex or did something happen?  

e.g. Jason https://hex.pm/packages/jason

**Comment by ericmj** [comment]
I don't see it being zero, it's at a minimum of 40000 daily downloads. Did you include the correct link?

**Comment by nacengineer** [comment]
huh It's working today. yesterday all the graphs I checked for all the hex packages I could think of fell off to zero at the end. Guess someone flipped a switch somewhere. Sorry for the bother.
