### ISSUE TITLE
Pending search results are showing an error

### ISSUE THREAD

**Issue by bcardarella** [hexpm/hexpm#1118]
When searching a library's documentation the pending search results shows "Page not found". This seems like an odd user experience, despite the loading symbol being shown. See screencap:
![Feb-07-2022 10-28-27](https://user-images.githubusercontent.com/18524/152818809-6ef35b64-278c-40bf-bc2c-4f04ebe629b0.gif)

**Comment by ericmj** [comment]
The search is implemented by https://github.com/elixir-lang/ex_doc so please open an issue on that repo. Thank you for the report!
