### ISSUE TITLE
Download stats dropped to 0

### ISSUE THREAD

**Issue by g-andrade** [hexpm/hexpm#1122]
It appears to have happened a few days ago; tested it in Firefox on macOS, saw the issue in private / incognito mode as well - same thing on Chrome.

Possibly the same problem as seen earlier in #1102 ?

---
![Screenshot 2022-02-25 at 15 23 15](https://user-images.githubusercontent.com/7349502/155741269-3cccea76-ce52-475b-80e9-6e248c074dc0.png)
---
![Screenshot 2022-02-25 at 15 23 25](https://user-images.githubusercontent.com/7349502/155741270-42f99f94-e80a-4e20-a218-1b85fe1299d7.png)
---
![Screenshot 2022-02-25 at 15 23 37](https://user-images.githubusercontent.com/7349502/155741272-4527a837-05b1-48dc-8205-be202a0c45bb.png)
---

**Comment by ericmj** [comment]
Thanks for the report, I am rebuilding the stats.

**Comment by aesmail** [comment]
I think this is happening again now for the last couple of days.

<img width="400" alt="Screen Shot 2022-08-22 at 21 59 53" src="https://user-images.githubusercontent.com/602354/185998194-04318355-2c56-4744-ae9c-01d6bed6bf6d.png">
