### ISSUE TITLE
Download statistics are 0 for days

### ISSUE THREAD

**Issue by crownedgrouse** [hexpm/hexpm#1123]
please note that the download statistics are 0 for all packages for days now.

![image](https://user-images.githubusercontent.com/4357695/156741706-0ce49c12-246b-423c-b733-bbb05b172eb4.png)

**Comment by crownedgrouse** [comment]
could this be related to https://github.com/hexpm/hexpm/commit/26fefe29f7ab4e7e3957c50959499b285cfb7a86  ?

**Comment by crownedgrouse** [comment]
could this be related to https://github.com/hexpm/hexpm/commit/e726bc932ef5dccdcb79da22d304fb1df337c34c ?

**Comment by crownedgrouse** [comment]
Fixed

**Comment by crownedgrouse** [comment]
Issue is back again

**Comment by josevalim** [comment]
It is good now. :)
