### ISSUE TITLE
Republishing docs with different main does not update page link

### ISSUE THREAD

**Issue by bryannaegele** [hexpm/hexpm#1129]
I've had this a few times where in copy/pasting mix file sections I end up forgetting to update `main` module for docs before publishing. After correcting the mistake in the mix file and publishing docs again, the link on the package's hexpm page will not update, including if you publish a new version.

Example: 
https://hex.pm/packages/opentelemetry_process_propagator
https://hexdocs.pm/opentelemetry_process_propagator/OpentelemetryTelemetry.html
https://hexdocs.pm/opentelemetry_process_propagator/OpentelemetryProcessPropagator.html

**Comment by ericmj** [comment]
Did you clear your browser cache before checking?

**Comment by bryannaegele** [comment]
It does seem to be working today. Is there a propagation or cache expiry time involved here?

**Comment by ericmj** [comment]
On the server/CDN side we purge the cache immediately, it should take less than 10 seconds to update. But on the client side we cache pretty aggressively and obviously cant purge so depending on your browser you may need to manually clear your cache for things to update.

Closing this but let me know if you think there is an issue or having anything to less add.
