### ISSUE TITLE
Fastly mirror lacking packages

### ISSUE THREAD

**Issue by tcitworld** [hexpm/hexpm#1130]
This only happens on remote machines, but on my local machine the `repo.hex.pm` Fastly mirror works correctly.

Both configurations are identical (installed through asdf):
```
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Mix 1.13.3 (compiled with Erlang/OTP 24)
```

DNS returns different but close IPs
* Local
  ```
  repo.hex.pm.		300	IN	CNAME	dualstack.f2.shared.global.fastly.net.
  dualstack.f2.shared.global.fastly.net. 20 IN A	151.101.122.2
  ```

* Remote
  ```
  repo.hex.pm.            115     IN      CNAME   dualstack.f2.shared.global.fastly.net.
  dualstack.f2.shared.global.fastly.net. 60 IN A  151.101.14.2
  ```

Reproduction configuration:
```elixir
defp deps do
  [
    {:phoenix_live_view, "~> 0.17.8"}
  ]
end
```
Without the mirror
```shell
$ mix deps.get
** (Mix) No matching version for phoenix_live_view ~> 0.17.8 (from: mix.exs) in registry

The latest version is: 0.17.7
```

With the mirror
```shell
$ HEX_MIRROR=https://cdn.jsdelivr.net/hex mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  mime 2.0.2
  phoenix 1.6.6
  phoenix_html 3.2.0
  phoenix_live_view 0.17.8
  phoenix_pubsub 2.1.1
  phoenix_view 1.1.2
  plug 1.13.4
  plug_crypto 1.2.2
  telemetry 1.1.0
* Getting phoenix_live_view (Hex package)
* Getting phoenix (Hex package)
* Getting phoenix_html (Hex package)
* Getting telemetry (Hex package)
* Getting phoenix_pubsub (Hex package)
* Getting phoenix_view (Hex package)
* Getting plug (Hex package)
* Getting plug_crypto (Hex package)
* Getting mime (Hex package)
```

**Comment by halostatue** [comment]
We’re seeing `ex_cldr 2.28.0` missing from both the fastly and jsdelivr mirrors on Semaphore CI, but are not seeing the packages missing from either on local machines.

**Comment by ericmj** [comment]
Can you go to https://www.fastly-debug.com/ on both the local and remote machine and paste the base64 text block here? If there is any private information displayed you can email it to support@hex.pm. You may need to disable content blockers in your browser such as ad blockers.

**Comment by ericmj** [comment]
This issue should be fixed after purging the CDN cache. Thanks for the report and please let us know if the issue persists or happens again.

**Comment by tcitworld** [comment]
Thanks! This seems to be resolved. It seems the jsdelivr.net CDN might have the same issue from time to time, though.
