### ISSUE TITLE
Let releases be modified if it has no downloads

### ISSUE THREAD

**Issue by vinibrsl** [hexpm/hexpm#1151]
Currently releases can only be modified (e.g. reverted, republished) up to one hour after publication.

```
Publishing failed
Validation error(s)
  inserted_at: can only modify a release up to one hour after publication
```

I suggest that releases should be able to be modified if they have no downloads, even if the time constraint has passed.

**Comment by ericmj** [comment]
We only update the download stats every 24 hours and at that point it has likely had at least one download due to mirrors and automated systems that download packages. I am also hesitant to rely on the download stats for functionality since they are unreliable.

**Comment by wojtekmach** [comment]
Closing for the reason above. Thank you for bringing this up though!
