### ISSUE TITLE
Add filtering out retired packages when you search on the website

### ISSUE THREAD

**Issue by kaypee90** [hexpm/hexpm#1155]

**Comment by ericmj** [comment]
Can you expand on this issue? Where do you want filtering?

**Comment by kaypee90** [comment]
@ericmj  So when I perform a search for a package on the website. I was looking at adding a toggle that can exclude retired packages from the search results.

**Comment by ericmj** [comment]
I think that could be hard to do because packages themselves are not retired, it's the versions of a package that is retired.
