### ISSUE TITLE
inserted_at value is null for releases in the packages API

### ISSUE THREAD

**Issue by KShivendu** [hexpm/hexpm#1167]
Hi,

I was exploring the Hex.pm [packages API](https://hex.pm/api/packages/) and noticed that `inserted_at` field is null for all the releases. 
However, selecting a specific package (like [this](https://hex.pm/api/packages/aadya)) reveals the values for `inserted_at`. 

The `inserted_at` field is a very useful package metadata. The API should have a consistent behavior and show the real value instead of null which can be confusing.

Thanks!

**Comment by wojtekmach** [comment]
Fixed in 1e0ba5a5, thank you for the report!

**Comment by KShivendu** [comment]
Hey @wojtekmach when is this going to be deployed in production? (https://hex.pm/api/packages/)

**Comment by ericmj** [comment]
It's deployed now.
