### ISSUE TITLE
Create a complete development environment setup

### ISSUE THREAD

**Issue by dmarcoux** [hexpm/hexpm#1177]
Right now, the development environment is only partially set up and documented. Any contributor is left out with making it work on their own. For example, which version of Elixir, Node and Yarn should a contributor install to get this project running?

I suggest doing the same as with the Postgres database and using Docker Compose for the rest of the setup.

This was already discussed in the PR #402, but I created this issue following a suggestion from @Benjamin-Philip in #1175. I find the arguments brought up in that PR to be wrong. Having a reproducible development environment isn't a personal setup, it makes working on the project a lot easier for everyone. And if somehow a contributor doesn't want to use the Docker Compose setup, they at the very least know what the dependencies for the project are. It's also not about how to host the project in production, this is purely for development purposes.

What do you think?

**Comment by ericmj** [comment]
I think this is a good idea. It will probably be a better developer experience to run hexpm outside of docker, but for people that do not want to configure the dependencies and to discover the deps this will help 👍

**Comment by ericmj** [comment]
This would be nice, but currently not planned. Contributions welcome!
