### ISSUE TITLE
Release inserted_at different from updated_at

### ISSUE THREAD

**Issue by KShivendu** [hexpm/hexpm#1182]
Hi, 

I'm looking for some clarity on why `updated_at` != `inserted_at` for releases. I believe that different values for these in case of packages makes sense but releases happen only once and afaik they can't change. Also, all the columns in the [releases table](https://github.com/hexpm/hexpm/blob/91b476e539e0dbb42c9fdc442d929efab4a49c72/priv/repo/migrations/20140128213400_add_releases_table.exs#L6) look like something that shouldn't change over time. Or am I missing something here? 

Example: In https://hex.pm/api/packages/phoenix/releases/1.7.0-rc.2 `updated_at` and `inserted_at` values are different. What exactly has been updated here? 

Thanks a lot :)

**Comment by ericmj** [comment]
It's 3 seconds between inserted_at and updated_at so the update is probably when the docs were published for the release. It would also be updated if the release is republished which can happen within in a one hour window.
