### ISSUE TITLE
Avatar image 404s for users and orgs who are not gravatar users

### ISSUE THREAD

**Issue by lpil** [hexpm/hexpm#1201]
Hello! The avatar image 404s for users and orgs who are not gravatar users.

Here's some examples:
- https://hex.pm/users/promethia
- https://hex.pm/orgs/exercism_gleam_maintainers

Thanks!

**Comment by wojtekmach** [comment]
The issue was closed by a commit but we don't deploy these automatically. I've deployed just now.
