### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by slashmili** [hexpm/hexpm#1202]
Hey!

I'm wondering if you are planning or open to making the hex.pm website to support os level "Appearance"? The same way that it works in docs of each package (e.g https://hexdocs.pm/elixir/)

If you are open and looking for a contribution, what kind of restriction should we consider when choosing the color for the dark mode?

I assume we also want to let user overwrite the settings?

**Comment by ericmj** [comment]
We have no plans for a dark mode on this website design. We are planning to do a new design and may consider it when it's implemented.
