### ISSUE TITLE
Allow limiting the scope of organization tokens to specific packages

### ISSUE THREAD

**Issue by jeffwidman** [hexpm/hexpm#1205]
This is a feature request to allow limiting the scope of read-only organization tokens to specific packages.

In :dependabot: , we have a public unit test that checks that Dependabot can access a private package on a Hex organization: https://github.com/dependabot/dependabot-core/blob/cd7227750358494e02cbd66c110f02b63e39c408/hex/spec/dependabot/hex/update_checker_spec.rb#L277-L289

Because this code is all open source, we don't control all the places the tests are run from... ie, outside contributors need to be able to run this test. So we've chosen to expose the token in the clear. 

However, from time to time, we need to debug support requests where we need to replicate a failure, so we need to have other private packages on a Hex org. We do _not_ want these accessible from the token that's exposed publicly.

For now we've worked around the problem by having two separate Hex organizations, but it's confusing for new team members... I myself didn't realize that's why we needed two orgs, and accidentally uploaded a package that we want to stay private to the org where we publicly expose the token. And I expect others to do that down the road.

Similarly, within a larger org, I'd expect that for principle of least privilege that CI systems should only have access to the private packages that they run tests for, not _all_ private packages within a hex organization.

So can you please make it possible to limit the scope of organization keys to specific packages?

**Comment by ericmj** [comment]
We can enable package keys for organizations also but I would definitely recommend using separate organizations if you have two expose a key to the public.

Note that the package scoped keys are only for publishing, to fetch you need to expose a repository key that has read access to everything in the repository.

So for your use case I think you should continue using separate orgs.

**Comment by ericmj** [comment]
This would be nice to have but currently low priority.
