### ISSUE TITLE
Easy way to view release dates on https://hexdocs.pm/module

### ISSUE THREAD

**Issue by dev-guy** [hexpm/hexpm#1209]
Perhaps I'm an idiot (I am) but when I go to https://hexdocs.pm/openai_ex , I see a drop-down of release (numbers) but I don't see any meta-information about the selected release, such as the release date. Other interesting information is the number of daily downloads and a link to the project (GitHub, gitlab, etc.)

I thought this existed last week so perhaps the website is undergoing maintenance. I don't know whom/where to ask.

**Comment by wojtekmach** [comment]
This is more of an ExDoc issue given Hexdocs is mostly concerned with hosting and not the docs contents.

I believe something like this was raised a couple times in the past: linking back to Hex package from Hexdocs. Unfortunately there isn't a lot of room to spare in the sidebar, not to mention the release dropdown. There is a [Hex Package] link all the way down in the footer though.

I'm going to close this but if you'd like to pursue this, please check for previous discussions around this in the ExDoc issue tracker.
