### ISSUE TITLE
Missing guards page

### ISSUE THREAD

**Issue by maikelthedev** [hexpm/hexpm#1219]
I'm reading the elixir page in https://hexdocs.pm/elixir/1.16/case-cond-and-if.html and it links to a Guards page that doesn't exist. The link should be 

https://hexdocs.pm/elixir/references/patterns-and-guards.html#guards

**Comment by ericmj** [comment]
Please report any Elixir documentation issues to the Elixir issue tracker: https://github.com/elixir-lang/elixir/issues
