### ISSUE TITLE
Add documentation surrounding hex repo verification

### ISSUE THREAD

**Issue by apreifsteck** [hexpm/hexpm#1221]
Back in 2019 there was a [change](https://github.com/hexpm/hex/blob/main/CHANGELOG.md#security-fixes-1) that requires the latest registry version. The changelog says that "Further clarification of this issue will come at a later stage". I've been trying to self-host my own hex repo, and even starting from scratch with what's in the box, I'm seeing errors related to this change when I try and fetch packages, so clarification would be quite welcome at this point 😅 

The error that I am seeing is this:
```
** (Mix.Error) Fetched deprecated registry record version from repo local. For security reasons this registry version is no longer supported. The repository you are using should update to fix the security reason. Set HEX_NO_VERIFY_REPO_ORIGIN=1 to disable this check.
```

I am seeking guidance or documentation that would describe how to update the repository to pass this check, instead of disabling it.

**Comment by ericmj** [comment]
There's a few different ways of building and hosting registries so we need some more information before we can answer this question.

How are you building the repository now and what have you tried?

**Comment by apreifsteck** [comment]
I was building the registry with a fork of hexpm, using [an azure storage client](https://github.com/hexpm/hexpm/pull/1220)

**Comment by ericmj** [comment]
I would recommend following this guide https://hex.pm/docs/self-hosting. This project is not meant to be used for self-hosted repos, there's a lot of things undocumented and assumptions in the code that are not correct for self-hosted repos.
