### ISSUE TITLE
Proposal: Add discussions links to hex.pm (Elixir Forum link, Github Discussion link, Discord link, ...) - hexrooms.pm is available 

### ISSUE THREAD

**Issue by couhajjou** [hexpm/hexpm#1228]
As a user of a package, I would like to find what channels/apps are used to discuss with the author and the user of the package.

We can have something like this in package page (ex https://hex.pm/packages/ash_postgres)

-----
**Owners**
[ash-project](https://hex.pm/users/ash-project)

...

...

**Discussions**
- github discussions
- elixirforum
- discord
- mattermost
- roll-your-own
-----

discussion links can be added to mix.

Please empower the community!

I have the domain and I can transfer it to the hex organisation.

**Comment by wojtekmach** [comment]
You already can add arbitrary links to packages with :links map. We could extend this in the future for links to be a map of maps so we could render it more nicely but id wait for more use cases. Thanks!
