### ISSUE TITLE
CSS issue with heading in the Versions page 

### ISSUE THREAD

**Issue by perzanko** [hexpm/hexpm#1229]
It clearly doesn't handle long package names. `line-height` needs a change.

<img width="1070" alt="Screenshot 2024-01-29 at 14 21 53" src="https://github.com/hexpm/hexpm/assets/22469100/ffd9cff0-8d4d-4cef-8ac2-b5527aafa923">

**Comment by ericmj** [comment]
Would you be willing to send a PR to fix this?
