### ISSUE TITLE
404 Link in Elixir Doc

### ISSUE THREAD

**Issue by Zottel92** [hexpm/hexpm#1231]
Hello there,

On the Doc-Page for Enum and Stream is a link for the Enum Cheatsheet that leads nowhere:
https://hexdocs.pm/elixir/enumerable-and-streams.html (3rd Paragraph of the Enumerables Chapter)

The wrong, used link leads to: https://hexdocs.pm/elixir/enum-cheat.cheatmd (404)
And the correct should most likely be: https://hexdocs.pm/elixir/enum-cheat.html

The error page said to create the issue here, so I hope this is the correct place.

Thanks for the good docs, I have a blast to read it so far.

Best regards,

**Comment by ericmj** [comment]
Please report Elixir documentation issues at https://github.com/elixir-lang/elixir.
