### ISSUE TITLE
Cannot Login to Hex.pm due to 2FA lost

### ISSUE THREAD

**Issue by GPrimola** [hexpm/hexpm#1236]
Hi,

I'm trying to login to Hex.pm but I've lost my 2FA codes.
I've already sent some emails to `support@hex.pm` regarding this issue, but I got no answers.

Can anyone help me with that?

Thanks!

PS: sorry to open an issue for that matter, but I've tried contact many times.

**Comment by ericmj** [comment]
Sorry about the delay, sometimes it can take a little longer for us to respond to emails, specially over the weekend. I have replied to your email with instructions on how to reset 2FA.
