### ISSUE TITLE
Show authenticator key when adding two-factor authentication

### ISSUE THREAD

**Issue by Munksgaard** [hexpm/hexpm#1237]
When going two-factor authenciation setup (https://hex.pm/dashboard/tfa/setup) it is currently not possible to get the textual representation of the authentication key needed. This makes it impossible to add two-factor authentication using e.g. the firefox bitwarden plugin.

**Comment by wojtekmach** [comment]
What is the usual textual representation, a otpauth:// url? If so, here's a quick draft:

<img width="1417" alt="image" src="https://github.com/hexpm/hexpm/assets/76071/2912070f-8faa-4635-a453-cd027760edcb">

```diff
diff --git a/lib/hexpm_web/templates/dashboard/tfa_auth_setup/index.html.eex b/lib/hexpm_web/templates/dashboard/tfa_auth_setup/index.html.eex
index ca0a1cc2..c984e03e 100644
--- a/lib/hexpm_web/templates/dashboard/tfa_auth_setup/index.html.eex
+++ b/lib/hexpm_web/templates/dashboard/tfa_auth_setup/index.html.eex
@@ -8,7 +8,8 @@
       <div class="panel-heading">Setup Security App</div>
       <div class="panel-body recovery-codes-panel">
         <h1>Scan this barcode with your app</h1>
-        <div style="text-align:center"><%= raw ViewHelpers.auth_qr_code_svg(@current_user) %></div>
+        <div style="text-align:center"><%= raw ViewHelpers.tfa_qr_code_svg(@current_user) %></div>
+        <div><code><%= raw ViewHelpers.tfa_url(@current_user) %></code></div>
       </div>
       <div class="panel-body">
         <%= form_tag(~p"/dashboard/tfa/setup") do %>
diff --git a/lib/hexpm_web/views/view_helpers.ex b/lib/hexpm_web/views/view_helpers.ex
index fd9734f1..138759f5 100644
--- a/lib/hexpm_web/views/view_helpers.ex
+++ b/lib/hexpm_web/views/view_helpers.ex
@@ -319,8 +319,13 @@ defmodule HexpmWeb.ViewHelpers do
     Map.put(output, key, Phoenix.View.render_one(struct, view, name, assigns))
   end
 
-  def auth_qr_code_svg(user) do
+  def tfa_url(user) do
     "otpauth://totp/hex.pm:#{user.username}?issuer=hex.pm&secret=#{user.tfa.secret}"
+  end
+
+  def tfa_qr_code_svg(user) do
+    user
+    |> tfa_url()
     |> EQRCode.encode()
     |> EQRCode.svg(width: 250)
   end

```

Does that solve the problem?

If so, if you could take it from here and make it look a bit better, we'd really appreciate a PR.

**Comment by Munksgaard** [comment]
Thank you for the quick response and impressive turnaround! 

I _think_ it's usually just the "secret" part. For example, here is what huggingface.co shows:

![screenshot](https://github.com/hexpm/hexpm/assets/230613/07d591d9-65e1-40b6-be75-9a0c3c82f0ff)

(where the secret I have unhelpfully blacked out is a string of uppercase alphanumerical characters)

I am not familiar with the opath uri-scheme (nor am I an expert in 2FA), so I don't know if they would be helpful. I don't recall having come across them before.

**Comment by Munksgaard** [comment]
And yes, I'd be happy to take a stab at turning your code into a proper PR. I'll try to make time for it this evening.

**Comment by wojtekmach** [comment]
Oh, if it's just secret then that's even better, we could even use their wording:

> You can also use your setup key (...)
