### ISSUE TITLE
Link to Enum cheatsheet needs updating

### ISSUE THREAD

**Issue by rlumsden** [hexpm/hexpm#1240]
It looks like the link to the Enum cheatsheet here: [https://hexdocs.pm/elixir/enumerable-and-streams.html](url) is out of date. 

![image](https://github.com/hexpm/hexpm/assets/59280121/ef9fa70a-85cb-49ad-8c56-b61009dd04f2)

Should it be linking to [https://hexdocs.pm/elixir/main/enum-cheat.html](url) ?

**Comment by wojtekmach** [comment]
Good find! Please send a PR to elixir-lang/elixir. And in the future don't report packages/docs bugs on hexpm/hexpm, this repo tracks issues with the service itself and not with what it's hosting. :)
