### ISSUE TITLE
opentelemetry_httpoison missing from Hex

### ISSUE THREAD

**Issue by pwcsquared** [hexpm/hexpm#1243]
The `opentelemetry_httpoison` doesn't seem to be published to Hex. I believe it used to be available on hex.pm before, but I may be recalling incorrectly.

**Comment by wojtekmach** [comment]
Please open the issue on that projects repository. This repo is concerned with hosting but not the packages themselves.

**Comment by pwcsquared** [comment]
Apologies, should have checked where that 404 link took me before opening this issue 😓
