### ISSUE TITLE
Beta packages minor issues.

### ISSUE THREAD

**Issue by dkuku** [hexpm/hexpm#1248]
My company publishes beta packages that have an id at the end.

The problem I spotted is that these are not sorted by time:
![image](https://github.com/hexpm/hexpm/assets/904179/8356b54d-6882-48a0-8702-a2cf20334b88)
But the order CI generated them is different.
![image](https://github.com/hexpm/hexpm/assets/904179/f69ce73e-2122-44f8-b872-c7cd7ef4ef4d)

Second issue I spotted is that for beta the generated entry looks like this:
`{:protobuf_staff_wages, "~> 3.3.6-beta.25318df", organization: "my_org"}`
And when I added this to mix.exs it installed a version that someone else generated and it was `newer` according to the sorting algorithm. 
It would make sense to point to the exact version 
`{:protobuf_staff_wages, "== 3.3.6-beta.25318df", organization: "my_org"}`

**Comment by wojtekmach** [comment]
Thank you for the report. This is pretty far from the beaten path and I'm not sure we can address it without complicating code which I'd rather avoid for somewhat niche scenario.

We always ordered packages by version numbers, not dates. I suppose we within the same major/minor/version we could order by date. Though if it's possible to change the versioning scheme on your end I'd do that, I think it'd be more useful to you too. Here's a schema I've seen some projects use:

```
MAJOR.MINOR.PATCH-beta.COMMIT_NUMBER-SHA
```

E.g.:

```
3.3.6-beta.0001-25318df # first commit since 3.3.6 cut off
3.3.6-beta.0002-...
```

Regarding `"~> 3.3.6-beta.25318df"`, yeah I can see it's somewhat annoying outcome in that particular case but I believe `~>` operator is the good default and I'm not sure we should make an exception (I'm not even sure what exact rules for such exception would be, all pre-release versions?)

**Comment by dkuku** [comment]
the id issue can be adressed by changing it on our end, but the ´~>´ it's an issue when 2 people update the same package in different branches. If I call ´mix deps.get´ and someone else pushes in the meantime a beta version with different changes and highier version I will get his changes not mine. When I think about it, this can be even an attack vector :)

**Comment by ericmj** [comment]
> The problem I spotted is that these are not sorted by time:
 
We will select the package with the highest version number according to the semver ordering. You need to use a versioning scheme that follows this.

https://semver.org/

> It would make sense to point to the exact version

Usually you want to use a requirement that allows updating to a newer version that is backwards compatible. That's why we use `~>`. If you change the ordering to follow semver that should not be an issue anymore.

**Comment by dkuku** [comment]
I'm only suggesting to point to exact version of beta packages. 
I understand that this may not be a big issue (but I hit it twice during 1 week). It only exists for members of the same organization.
It may exist in other ecosystems, so it may be a good topic for a blog post.

**Comment by wojtekmach** [comment]
I think it's tough, do we make an exception just for _beta_ packages or all prereleases? If there's a, for example, phoenix live view 1.0.0-rc.0, I think `~> 1.0.0-rc.0` is what people want, easily update to rc.1 and indeed 1.0.0 final.

I don't think we should change this so I'll go ahead and close this but of course please feel free to continue discussing this.
