### ISSUE TITLE
Recent downloads is always 0 for packages displayed as an exact match

### ISSUE THREAD

**Issue by jonathanballs** [hexpm/hexpm#1254]
See description. Download numbers are a positive heuristic for finding trusted/reliable packages and a broken indicator might lead some users to assume the package they were looking for wasn't the right one.

<img width="1268" alt="Screenshot 2024-05-23 at 16 02 48" src="https://github.com/hexpm/hexpm/assets/4366510/93a5cffc-880e-4711-a3f6-8724f482ab07">

**Comment by darraghenright** [comment]
Way ahead of me, I just noticed this and came to report same. I can confirm same happens as an anonymous user.

**Comment by darraghenright** [comment]
Running `hexpm` locally here. Looks like a regression introduced in this recent commit which added some improvements when displaying an exact match:

https://github.com/hexpm/hexpm/commit/1fb4816abaa8ef23f40795dfa93b9e6b7c569452

If I revert this commit, the exact match shows the accurate number.

I don't have time right now to look into what changed that cause the issue but I should be able to look into it a little later if that helps.
