### ISSUE TITLE
Help cancel automatic deduction!

### ISSUE THREAD

**Issue by chrisstyle** [hexpm/hexpm#1264]
My hexpm account is hongliyu, the Organization is helijia

1. 
I've canceled my annual plan, but the system still tries to charge me every week.
 Please stop auto deduction! the invoice info:
`Organization: helijia
Invoice number: #A8727
Amount: $70.00`

2. I need leave the organization, but tips:
" The last member of an organization cannot leave."

**Comment by chrisstyle** [comment]
I sent mail to "support@hex.pm", but got no reply, and the system still trying to deduct the fee!

**Comment by ericmj** [comment]
We have replied to your email but got no response.

The billing has already been canceled and no charges will be made.
