### ISSUE TITLE
Bug: Validation error: "invalid license"

### ISSUE THREAD

**Issue by jimsynz** [hexpm/hexpm#1270]
Hi there.

I publish my personal works under the [HL3-FULL](https://firstdonoharm.dev/version/3/0/full.html) license. I get that it's not on the list of SPDX license (although I do see `Hippocratic-2.1` on the list), however it seems a bit weird for Hex to refuse my package on the grounds that it doesn't like the license I have chosen.

Here's the console output when attempting to publish a new `reactor_req` package:

```
Building reactor_req 0.1.0
  Dependencies:
    igniter ~> 0.2 (app: igniter)
    reactor ~> 0.9 (app: reactor)
    req ~> 0.5 (app: req)
    spark ~> 2.0 (app: spark)
  App: reactor_req
  Name: reactor_req
  Files:
    lib
    lib/reactor
    lib/reactor/req
    lib/reactor/req/builders
    lib/reactor/req/builders/request.ex
    lib/reactor/req/builders/post.ex
    lib/reactor/req/builders/delete.ex
    lib/reactor/req/builders/put.ex
    lib/reactor/req/builders/patch.ex
    lib/reactor/req/builders/merge.ex
    lib/reactor/req/builders/run.ex
    lib/reactor/req/builders/get.ex
    lib/reactor/req/builders/builder.ex
    lib/reactor/req/builders/head.ex
    lib/reactor/req/builders/new.ex
    lib/reactor/req/ext.ex
    lib/reactor/req/step.ex
    lib/reactor/req/dsl
    lib/reactor/req/dsl/request.ex
    lib/reactor/req/dsl/options.ex
    lib/reactor/req/dsl/post.ex
    lib/reactor/req/dsl/delete.ex
    lib/reactor/req/dsl/put.ex
    lib/reactor/req/dsl/patch.ex
    lib/reactor/req/dsl/merge.ex
    lib/reactor/req/dsl/run.ex
    lib/reactor/req/dsl/get.ex
    lib/reactor/req/dsl/head.ex
    lib/reactor/req/dsl/new.ex
    lib/reactor/req.ex
    .formatter.exs
    mix.exs
    README.md
    LICENSE.md
    CHANGELOG.md
    documentation
    documentation/dsls
    documentation/dsls/DSL:-Reactor.Req.md
  Version: 0.1.0
  Build tools: mix
  Description: A Reactor extension which provides steps for working with `Req`.
  Licenses: HL3-FULL
  Links: 
    Changelog: https://harton.dev/james/reactor_req/src/branch/main/CHANGELOG.md
    GitHub: https://github.com/jimsynz/reactor_req
    Source: https://harton.dev/james/reactor_req
    Sponsor: https://github.com/sponsors/jimsynz
  Elixir: ~> 1.17
The following licenses are not recognized by SPDX:
 * HL3-FULL

Consider using licenses from https://spdx.org/licenses
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.
{:failed_connect, [{:to_address, {~c"hex.pm", 443}}, {:inet, [:inet], :econnrefused}]}

Proceed? [Yn] 
Building docs...
Compiling 26 files (.ex)
Generated reactor_req app
Generating docs...
View "html" docs at "doc/index.html"
Local password: 
Publishing package...
[#########################] 100%
Publishing failed
Validation error(s)
  meta:
    licenses: invalid license "HL3-FULL"
```

I already have quite a number of packages already published under this license also.

**Comment by jimsynz** [comment]
FYI I was able to publish this package by setting the `licenses` key in the package information to an empty list.

**Comment by ericmj** [comment]
We have made the choice to only accept licenses on the SPDX list as it enforces a single label for a given license. I would suggest asking SPDX to include the HL3-FULL license.

**Comment by jimsynz** [comment]
Hi @ericmj. There was some discussion of SPDX on the Ethical Source slack - the consensus was that it was very difficult to get SPDX to include Hippocratic-2.1 as they want to see a certain amount of usage before they add it. If package managers like hex don't allow license labels that are not in the SPDX then that effectively becomes a 🐔/🥚 problem.

Regardless, can I ask what the intent of this feature is? Is it hex's position that it's okay to publish packages under non-SPDX licenses and just not use the license label in `mix.exs`? If so I am happy to open a PR to make the validation message more explanatory.

**Comment by ericmj** [comment]
The intent for this is that consumers of packages should be able to run tools over their dependency lists to determine what licenses are being used in their dependencies. For example companies that need to do this for compliance reasons. This is only possible if the licenses use a common format, such as SPDX.

You can leave the :licenses list empty for the times when you cannot use the SPDX format, the assumption then is that the package maintainer will put the license in a LICENSE file or similar.

If you could send a PR that improves the validation message that would be appreciated. Thank you!

**Comment by jimsynz** [comment]
roger wilco.
