### ISSUE TITLE
Repo documentation link does not work

### ISSUE THREAD

**Issue by SoldierCoder** [hexpm/hexpm#1272]
If you look up the Elixir module named Repo, it is missing all the documentation.

**Comment by wojtekmach** [comment]
Thanks for the report. If you are referring to Ecto Repo link being broken in documentation, please note hexdocs hosts documentation infrastructure but not the docs contents themselves. For that, go to individual GitHub repositories of the packages themselves. Please send a PR to Ecto with a docs change, it will be very appreciated!
