### ISSUE TITLE
Choosing a strong Erlang example dep for the home page

### ISSUE THREAD

**Issue by JesseStimpson** [hexpm/hexpm#1278]
I was introducing a new Erlang developer to hex.pm today, and I was surprised to find hackney as being the example Erlang dep on the home page. I mean no offense to the hackney project, but I believe other projects would be more well suited for a canonical example. 

I think the `telemetry` project may be the most natural fit. A case could also be made for `cowboy` to achieve parity with the Elixir example.

Thanks! :)

**Comment by ericmj** [comment]
What's the issue with using hackney as example dependency?

**Comment by JesseStimpson** [comment]
Hi @ericmj , 

When I inspect the telemetry project I have these positive takeaways:

* Up-to-date and correctly rendered documentation on Hex
* Passing CI on GitHub Actions
* Well-maintained Issues and PRs

With respect to the hackney project, the library may perform very well, but I do not have these same takeaways, and I feel they are important to visitors of Hex to get a positive impression of the quality of work I have personally come to expect from the Elixir and Erlang communities.

**Comment by ericmj** [comment]
Those are all good reasons, thanks for explaining. I agree that telemetry would be a better example, would you mind sending a PR that updates it?

**Comment by JesseStimpson** [comment]
Sure thing. I will submit one in the coming days. Thanks.
