### ISSUE TITLE
Searching for words in package name doesn't return the package near the top

### ISSUE THREAD

**Issue by ericlathrop** [hexpm/hexpm#1281]
I wasted a fair bit of time building a package when a package already existed with the super obvious name just because hex's search didn't show it immediately.

Examples:
Search for "http cache" shows "http_cache" on page 5
Search for "mix test watch" shows "mix_test_watch halfway down the first page".

Packages with similar names to the search should be sorted near the top.

**Comment by ericmj** [comment]
Search improvements are being tracked in this issue: https://github.com/hexpm/hexpm/issues/1050

**Comment by ericlathrop** [comment]
Ah, sorry, I missed that.
