### ISSUE TITLE
Add graphs for download statistics for all and individual packages

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#151]

**Comment by milmazz** [comment]
@ericmj Something like a time series that shows the Downloads over the last 60 days? or do you prefer something like a monthly average downloads?

**Comment by ericmj** [comment]
Maybe show the last 30 days and monthly average downloads over the entire lifetime?

**Comment by jcspencer** [comment]
If we want to show downloads from a given time period, do we need to include a date in the HexWeb.Stats.PackageDownload schema?

**Comment by ericmj** [comment]
Sure, if we want to .We can adjust the cached download views as necessary.

**Comment by ericmj** [comment]
Is anyone working on this otherwise I might grab it?

**Comment by fteem** [comment]
I'd like to take a stab at this if free?

**Comment by ericmj** [comment]
I think it's free. If you already started working on this @milmazz please let us know so we don't duplicate efforts.

**Comment by milmazz** [comment]
@ericmj No, I haven't work on this. So, @fteem please go ahead, if you need some help just let us know.

**Comment by fteem** [comment]
@milmazz cool, I'll tackle this.

**Comment by jcspencer** [comment]
If we were to do this, I suggest we simply pre-render a graph as a background job after the download stats are calculated (one option is just to pre-render a d3 svg in phantom). This speeds up both server-side queries (we don't need to constantly query download stats) and speeds up client-side loading (no need to render the graph every time).

**Comment by lorenzosinisi** [comment]
I have a proposal and I have just opened a PR for that, listing all the downloads for each day for a specific package https://github.com/hexpm/hexpm/pull/722, what do you think?

**Comment by ericmj** [comment]
This is another feature request, we want to add visual graphs to the website that shows package downloads over time.

**Comment by lorenzosinisi** [comment]
Alright, thanks @ericmj !

**Comment by zacck** [comment]
@br4inii let me know if you need any help getting this done, I would start by getting some ideas from @ericmj 👍  `GodSpeed`

**Comment by zacck** [comment]
@ericmj I would like to finish this one up If I understand correctly we want a fucntionality that behaves like the following screenshot from  npm
![screen shot 2019-01-04 at 09 57 23](https://user-images.githubusercontent.com/897731/50678446-5d70cd80-1007-11e9-9040-e4bfa3e77a00.png)

Where a visual graph is shown next to the number of downloads, one thing to consider would be what unit to use for the `x-axis` days? weeks? months?

**Comment by ericmj** [comment]
The plan is to have a small, simple graph in the sidebar (like npm), and a separate page with detailed and more graphs.

Probably a good idea to start with a PR for only the small graph in the sidebar and build from there. Hard to say what the axes should be, but we can try with week units over the last 52 weeks. It would be great if we could make the code modular so we could reuse it for different units and scales, but this could also be left for later.

What do you think?

**Comment by zacck** [comment]
@ericmj  I think I should start with the small graph on the sidebar, where I can be using weeks on the x axis,  once I have that working we can break it down into something modular that can be re used to build other graphs ... key is to get this first small graph out  :) I feel

**Comment by zacck** [comment]
Hi @ericmj  a little help from you would go a long way, I am trying to collect all package downloads from the past 52 weeks so that I can sort them into `weekly` totals then  graph them. 

However, I seem to be confused about where to get this data at the moment I am trying to pick all the downloads as using the package id as follows 

``` elixir
iex(5)> query = from pd in PackageDownload, where: pd.package_id == 18
#Ecto.Query<from p in Hexpm.Repository.PackageDownload,
 where: p.package_id == 18>
iex(6)> Repo.all(query)
[debug] QUERY OK source="package_downloads" db=0.5ms queue=0.4ms
SELECT p0."package_id", p0."view", p0."downloads" FROM "package_downloads" AS p0 WHERE (p0."package_id" = 18) []
[
  %Hexpm.Repository.PackageDownload{
    __meta__: #Ecto.Schema.Metadata<:loaded, "package_downloads">,
    downloads: 18,
    package: #Ecto.Association.NotLoaded<association :package is not loaded>,
    package_id: 18,
    view: "recent"
  },
  %Hexpm.Repository.PackageDownload{
    __meta__: #Ecto.Schema.Metadata<:loaded, "package_downloads">,
    downloads: 6,
    package: #Ecto.Association.NotLoaded<association :package is not loaded>,
    package_id: 18,
    view: "day"
  },
  %Hexpm.Repository.PackageDownload{
    __meta__: #Ecto.Schema.Metadata<:loaded, "package_downloads">,
    downloads: 6,
    package: #Ecto.Association.NotLoaded<association :package is not loaded>,
    package_id: 18,
    view: "week"
  },
  %Hexpm.Repository.PackageDownload{
    __meta__: #Ecto.Schema.Metadata<:loaded, "package_downloads">,
    downloads: 24,
    package: #Ecto.Association.NotLoaded<association :package is not loaded>,
    package_id: 18,
    view: "all"
  }
]
```

However, as you can see the data I get as a result isn't detailed enough for me to sort it into weekly downloads.

Please let me know if you have strategy I can apply at this or maybe I can look else where?

**Comment by ericmj** [comment]
> oh wait I found out a release has a count of daily donwnloads, what then I think I should do is sort these daily downloads into weekly aggregates then use those aggregates to build out the graph here is how I am picking the downloads

That's great first approach, we can optimize this later to use a more direct views with materialized views.

**Comment by gausby** [comment]
Would be great if the download stats would take package version into account, such that one can see the number of downloads for a given version number. This would make the decision to keep or drop support for a given version range easier.

**Comment by ericmj** [comment]
This has been implemented in https://github.com/hexpm/hexpm/pull/966 by @supersimple. We wouldn't having more graphs for all packages and more customizable graphs if anyone wants to work on that. The work in #966 can be used a starting graph for that but I don't think we need an issue tracking this anymore.
