### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#271]
Per conversation on https://github.com/hexpm/hex_web/pull/265#discussion_r55612798 there're a few things we could do to clean up the test suite:
- [x] return common records from the setup hook instead of fetching them in each example. E.g.: `test "release docs", %{user: user} do`
- [x] consider using some sort of factory library for generating test data

**Comment by wojtekmach** [comment]
@ericmj I created this issue so that I don't forget about it :) Feel free to drop ideas how to improve the test suite even further

**Comment by sotojuan** [comment]
> return common records from the setup hook instead of fetching them in each example. E.g.: test "release docs", %{user: user} do

Taking care of this right now :-)

**Comment by mkaszubowski** [comment]
@wojtekmach Do you have any preference for factory library? https://github.com/thoughtbot/ex_machina and https://github.com/batate/blacksmith both looks good, I could introduce it to the tests if that's ok with you.

**Comment by wojtekmach** [comment]
I haven't used either of these so not sure. Also, it's really @ericmj's call :)

**Comment by wojtekmach** [comment]
@ericmj since the fresh off-the-press "What's new in ecto 2.0" chapters suggests that in many cases using just ecto 2 is good enough (as opposed to bringing in another dep) I think we should give it a go :) wdyt?

**Comment by ericmj** [comment]
I talked with @wojtekmach and we decided we can go ahead without a factory library but we should continue moving model creation to the setup callback and we should generate random data for the models so that we still get test concurrency from postgres.

**Comment by ericmj** [comment]
I have started work on this if you look at the latest commits in master. More work has to be done but I think we can close because improving the test suite will be an ongoing job.
