### ISSUE TITLE
Add reserved package versions

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#272]
If a package release has been removed we should reserve that version for all future so that we can't republish over it.

**Comment by OnorioCatenacci** [comment]
Is there a database somewhere that keeps the current and prior versions of packages Eric?  I think the simplest way to accomplish this would be to simply add a step to add an entry into a database to record that a version is in use and to mark prior versions as "unavailable".

**Comment by ericmj** [comment]
This information is not currently stored anywhere. We store current packages and their versions of course but previous versions have not been stored.

**Comment by wojtekmach** [comment]
I believe this has been discussed in some issues before - one way to do it is to never truly delete a package or release record (or any record, eventually) from the DB and instead "soft delete" it by setting a flag. This way, uniqueness constraint would prevent republishing.

**Comment by ericmj** [comment]
I think it's better to keep a list of reserved names and version.

**Comment by jcspencer** [comment]
@ericmj would this go against what you described in #197 in regards to registry immutability?

**Comment by ericmj** [comment]
@jcspencer #197 limits the user's ability to remove packages. Admins will still be able to remove packages in special circumstances such as for legal reasons.

**Comment by enilsen16** [comment]
This would also prevent packages from not having any releases.
