### ISSUE TITLE
Add 2-factor authentication for publishing

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#278]
For reference: https://www.kb.cert.org/vuls/id/319816.

We should start out by sending an email with a link or a code you have to enter for the publish to proceed. In the future we can look at other forms of 2-factor such as sending an SMS.

**Comment by ericmj** [comment]
We would also need the 2-factor for adding or removing package owners.

**Comment by ferd** [comment]
+1 to this, especially useful since pretty much all installs and compile runs are allowed arbitrary code execution.

**Comment by jcspencer** [comment]
I'm willing to implement this, but before I do, I have a few questions:

1. What type of 2FA codes will we be using? TOTP, HOTP, etc.
2. Will we be using any external providers? (i.e. Google Authenticator, Yubico, etc.)

**Comment by jcspencer** [comment]
IMO, I'd either provide support for Google Authenticator-esque applications (for TOTP codes), or send OTP codes over SMS.

**Comment by ferd** [comment]
I like TOTP more than SMS since I do not need to pay fees when I'm traveling for TOTP.

**Comment by ericmj** [comment]
I think it's overkill for the first iteration. We just need to generate a code, with a time limit, on the server, email that to the publisher and have him enter it when publishing. Similar to how email confirmation works today.

After this is working we can look at other services such as SMS and Google Authenticator.

**Comment by jcspencer** [comment]
I think that we should implement email first, but by sending TOTP tokens. That way when we implement things like Google Authenticator, we don't need to reinvent the wheel again. 

On 5 April 2016 10:10:02 PM AEST, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>I think it's overkill for the first iteration. We just need to generate
>a code, with a time limit, on the server, email that to the publisher
>and have him enter it when publishing. Similar to how email
>confirmation works today.
>
>After this is working we can look at other services such as SMS and
>Google Authenticator.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/278#issuecomment-205772181

-- 
James Spencer

**Comment by ericmj** [comment]
I don't think TOTP really works if you cant share a secret with the client, remember that 2-factor is supposed to circumvent the user system being compromised and the user already stores an API key which is a shared secret.

TOTP also seems superfluous if we are going to send the TOTP value to the user. TOTP builds on the client and the server independently generate the same value.

**Comment by jcspencer** [comment]
The main advantage of using TOTP tokens is that they are time derived, so they will automatically expire. Even if the client isn't generating their own tokens to prove they have the secret, the tokens sent are time-limited by design. 

Are you suggesting we generate random crypto data and derive a number from it?

On 6 April 2016 10:35:51 AM AEST, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>I don't think TOTP really works if you cant share a secret with the
>client, remember that 2-factor is supposed to circumvent the user
>system being compromised and the user already stores an API key which
>is a shared secret.
>
>TOTP also seems superfluous if we are going to send the TOTP value to
>the user. TOTP builds on the client and the server independently
>generate the same value.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/278#issuecomment-206049454

-- 
James Spencer

**Comment by ericmj** [comment]
That's why I suggested doing it like the email confirmation tokens which also expire after time. I don't see any benefit TOTP gives us over normal time-limited tokens.

**Comment by jcspencer** [comment]
I have begun the implementation of this. I am building the feature using the following parameters (definitely up for discussion):

When an API request is made that requires 2FA, a 401 response is returned with a header `X-Hex-OTP: required; <type>`<sup>[1]</sup>. Once a client has gathered the required 2FA token, it is added to a request in the `X-Hex-OTP` header.

2FA tokens are able to be generated by two means (in this initial implementation):
- TOTP (Google Authenticator). 30 second timeout (GA mobile limitation).
- SMS. 5 minute timeout. 

Both token types are based on TOTP, using a 20 byte secret, but this can obviously be swapped out if deemed necessary. 

When an account enables 2FA, `n` recovery codes are generated from 10 random byes (16 chars of Base32). Any of these codes can be used in place of a 2FA code exactly *once*. I am unsure as to whether these codes should be retrievable (except upon creation).

[1] [GitHub API Reference](https://developer.github.com/v3/auth/#working-with-two-factor-authentication)

**Comment by wojtekmach** [comment]
btw, AWS recently announced worldwide SMS messaging [1] so it might be a good fit for delivery.

[1] https://mobile.awsblog.com/post/TxSP0HUNM8FQ1Y/Introducing-Worldwide-SMS-Messaging

**Comment by ericmj** [comment]
@jcspencer Sounds good. The recovery codes should still be accessible after they have been generated.

@wojtekmach I'm leaning towards Twilio for SMS. Amazon seems to have some crazy pricing for sending to numbers outside the US, sometimes more than 100x as expensive when compared to Twilio.

**Comment by jcspencer** [comment]
@ericmj @wojtekmach Also, [ExTwilio](https://github.com/danielberkompas/ex_twilio) is a well-built library for interfacing with Twilio. AFAIK, there aren't any existing Elixir/Erlang libraries that allow you to easily interface with AWS SMS.

**Comment by jcspencer** [comment]
Hi all,

I've completed an implementation of the TOTP generation, SMS api (twilio / local - for testing) and api extensions, alongside tests for each. The one thing left is a trivial problem: how should each user's settings for TOTP be stored?

Should there be an embedded `settings` schema kept inside a user object to store all settings (for future extensibility), should this data be kept in a separate table (i.e. `user_settings`) or should it be embedded in the user object (messy + unintuitive, imo)?

**Comment by jcspencer** [comment]
@ericmj ping

**Comment by ericmj** [comment]
Sorry, missed your previous message. A `settings` map field on `User` can be used for user settings.

**Comment by jcspencer** [comment]
I've got a working prototype locally that I'm putting the finishing touches on. Below are the implementation details, and any feedback would be much appreciated!

## Implementation Details

By default, a each user has a twofactor column that looks like:
{
  "id": uuid, 
  "type": "disabled", 
  "secret": "", 
  "enabled": false,
  "backupcodes": []
}
 
Where:
- `type` is the type of 2FA to use; currently, it's limited to 'disabled' and 'totp' (future implementations could include 'sms', etc.)
- `secret` is a shared secret (20 bytes - base32) used for TOTP. It is encrypted using PBES2_HMAC_SHA2 / AES_CBC_HMAC_SHA2 (described here hexpm/hexpm#255) with an app secret before we store it.
- `backupcodes` is an array of base32 strings - each 10 bytes (base32) which are formatted in the structure "xxxx-xxxx-xxxx" - these are single-use tokens that the user can use to access their account if they lose their phone, etc.

## Setup Process
- The secret, as well as ten backup codes are generated and stored in the database.
- A QR code is generated to allow the user to quickly setup Google Authenticator (or a similar TOTP generator), along with a secret to manually type in. After this, the QR code cannot be regenerated for security purposes.
- The user is requested to enter the current TOTP token to confirm that their client is setup properly (makes sure we don't lock anybody out!)
- If the code is correct, we toggle the `enabled` field and give the user their 10 backup codes.

## Authentication Process:
### Web:
- The login page has an additional field called `OTP`. If the code is incorrect or not included, the response is returned with the message "Two factor authentication required."

### API:
- The user must append the header `x-hex-otp` with the current OTP to the request
- If the TOTP token is either wrong or not included, the response is returned with the `x-hex-otp` header `required; type` (where type is either 'totp' or 'sms'), a 401 status code and the message "two-factor authentication required".

**Comment by ericmj** [comment]
It looks good @jcspencer. My only comment is that the twofactor column in the database should be its own table. How are the backup codes entered, do you enter them instead of the TOTP? Before we release this we also need a way for users to disable 2FA.

**Comment by jcspencer** [comment]
Moving the twofactor column to a table is easy enough.

Currently, backup codes are simply entered instead of the TOTP code when prompted. They can be regenerated on the Dashboard page.

Users are able to disable 2FA on the dashboard. Currently it doesn't require verification, but should we require reauthentication before we disable it?

**Comment by ericmj** [comment]
> Users are able to disable 2FA on the dashboard. Currently it doesn't require verification, but should we require reauthentication before we disable it?

Yes, probably behind a "sudo mode" similar to how github does for some actions https://help.github.com/articles/sudo-mode/.

**Comment by ericmj** [comment]
The original vulnerability is fixed on the client side by requiring a password for publishing packages. We would still like to support two-factor authentication but it is a pretty big task and currently not of the highest priority.

**Comment by hewsut** [comment]
(Obvious?) two cents from someone in a fairly large company trying to nudge folk toward Elixir.

Two factor auth on the package manager is a _big_ deal. Lack of 2FA does make the pitch for the Elixir/Erlang ecosystem more difficult.

**Comment by hubertlepicki** [comment]
So, umm. You guys need some help implementing this? I can possibly get someone implementing this from our team at AmberBit

**Comment by ericmj** [comment]
Any help in this area is appreciated. I believe @supersimple has started exploring this, so we should sync up first to avoid duplicate efforts.

**Comment by palash25** [comment]
Hi @supersimple is this project still reserved for Google Summer of Code or is someone else working on it?

**Comment by supersimple** [comment]
Hi @palash25
We aren't saving the project for GSoC, I have just been distracted with other things. Right now we have many of the components we need, but there are some small things missing. 
I'd love more contributors, but I need to get an updated checklist of what we have and don't have so we can assign work.
I will do my best to take a look at it this week and have a plan to move forward.

Thanks again
