### ISSUE TITLE
Add support for namespaces

### ISSUE THREAD

**Issue by asabil** [hexpm/hexpm#364]
## Background

The conversation started, because an elixir package is published under the name `uuid`, while the erlang one is published under the name `uuid_erl` https://twitter.com/zeank/status/743372406069334016
## Suggested solution

A suggestion would be to introduce namespaces for hex.pm and have both `zyro/uuid` and `okeuday/uuid`
## Migration

The issue at hand is how to handle the migration of existing unnamespaced packages. A migration path could be as follow:
1. Add support for namespaced packages.
2. Disallow the publishing of new unnamespaced packages.
3. Add support for package aliases internally to support package renaming.
4. Automatically rename existing packages based on the owner username to become `$owner/$package`, and create an alias for from the old name to the new one.
5. Hide unnamespaced packages from the web UI.
6. After a very long period of time, update the clients to issue a warning when using unnamespaced packages in the dependency list.

With this approach, all existing packages will continue to work.
## Challenges

The main challenge presented by @ericmj is that we will end up with a list of package forks, which is something that has plagued the Erlang community for ages.

**Comment by jlouis** [comment]
Some additional comments:

First, every User identity on hex has their own namepace, e.g., `jlouis/*` in which their packages are published.

Second, you have collection namespaces, `elixir/*`, `erlang/*`, `elixir-platform/*` and so on. These are used to form collections of packages with a given set of coherency. It is not for splitting packages between Erlang and Elixir, but for the idea of being able to establish a stable base-set of packages which have been shown to work together. People are notoriously good at breaking backwards compatiblity, and some packages might not work on newer versions of Erlang/Elixir, so it is good to have a way to tag/curate packages as such.

A special namespace `global/*` exist. Everyone of the 2000 packages goes there. As do non-namespaced package uploads.

**Comment by ericmj** [comment]
> Second, you have collection namespaces, elixir/*, erlang/*, elixir-platform/* and so on.

This is not the job of a package manager or its admins to maintain. Anyone is free to do this themselves though.

> A special namespace global/* exist. Everyone of the 2000 packages goes there. As do non-namespaced package uploads.

So you are for keeping the global namespace and allowing future uploads to that namespace? That is what I had in mind if namespaces are add. npm does this too.

**Comment by jlouis** [comment]
I completely agree you shouldn't maintain such collections yourself. There are many good reasons for maintaining certain sections "outside" the main package space however:

* New versions of standard libraries which break backwards compatibility.
* Experimental stuff which is not yet ready for general consumption, but need the ease of development you get from having a proper package manager repository.
* Poor people who have to maintain systems for older releases.

As for the global namespace: indeed, I think one should keep this. I fully acknowledge the strength of having a single default entry-point for a package, fostering collaboration. I would imagine that a global namespace is just "pointers" to underlying namespaces for the individual users. In fact, I'd prefer if a package were a SHA256 checksum and the meta-data about it were simply pointing to the underlying package. This is a content addressable store, which means you can another entry-point for caching.

**Comment by josevalim** [comment]
If we are still going to keep the global namespace, why is it any better than today's solution of using a different package name for the same application?

Today:

    {:uuid, "1.0.0", hex: :zeank_uuid}

With namespaces:

    {:uuid, "1.0.0", namespace: :zeank}

?

**Comment by jlouis** [comment]
You latter example is strucurally better. You can build tooling around that, which you can't for the first variant. There is no way to know that `zeank_uuid` is namespace specific, whereas in the latter case, there are. Imagine I can choose a namespace ordering in my configuration file, meaning that by default I want the packages in my own namespace rather than the global packages, if applicable. Or packages from a given collection. In the latter example, I can write that myself. In the first example, I have relatively little chance, unless I build yet another indirection layer on top.

**Comment by josevalim** [comment]
@jlouis perfect, I agree with the benefits you brought up, thank you!

**Comment by rranelli** [comment]
Would namespaces allow one to have *both* uuid libraries as dependencies? (from what I understood in the discussion, I don't think they would)

I recently had an issue with the `uuid` dependency when adding `cqex` to my project: https://github.com/matehat/cqex/issues/5

**Comment by ericmj** [comment]
No, unfortunately not. You can only have one application of the same name
loaded in the VM at once.

On Thu, Jul 7, 2016 at 7:46 PM, Milhouse <notifications@github.com> wrote:

> Would namespaces allow one to have *both* uuid libraries as dependencies?
> (from what I understood in the discussion, I don't think they would)
>
> I recently had an issue with the uuid dependency when adding cqex to my
> project: matehat/cqex#5 <https://github.com/matehat/cqex/issues/5>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hexpm/hex_web/issues/364#issuecomment-231154232>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATV2rISeiCqH9EYWnLnllv2sIUHNfo8ks5qTTtZgaJpZM4I4No9>
> .
>



-- 
Eric Meadows-Jönsson

**Comment by asabil** [comment]
Is there anything I could do to move this forward? I would like to publish https://github.com/asabil/raven-erlang to hex, but I can't because there is already a raven project, but that's an elixir one

**Comment by ericmj** [comment]
We are going to introduce namespaces but we are still deciding on how they should work generally and on Hex.pm and the new registry format is blocking their introduction. As it looks right now it is unlikely that Hex.pm will support free-to-use public namespaces due to the concerns I have raised here and on IRC.

I wouldn't recommend waiting on this feature to publish your package.

**Comment by ericmj** [comment]
I have started the work on support for multiple repositories, a repository is its own namespace. Hex.pm will only have a single public repository (with possibly some rare exceptions for things like nerves), you will be able to create repositories on Hex.pm but they will be private and packages in the global namespace cannot depend on them.

We have support for multiple repositories in the client now so anyone that wants to use namespace can do so.
