### ISSUE TITLE
Update top-level docs to the next-to-last version if the last version is being reverted

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#383]

**Comment by idyll** [comment]
Can this include a flag or indication of the nature of the issue with the previous package.

I am hoping to use this to add additional scanning beyond just out of date and instead fail builds when a package you are using contains a known security issue.

**Comment by ericmj** [comment]
This is only for docs. You can only revert packages for up to one hour after its initial release so it's unlikely that's for security reasons.

**Comment by ericmj** [comment]
This will not be needed when we move to the new hexdocs service.
