### ISSUE TITLE
Provide user-agent usage stats from repository access logs

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#401]

**Comment by iamvery** [comment]
Leaving a note to say that I was pointed to this issue from a request to gather Elixir version usage statistics.

> Does anyone gather statistics about Elixir version adoption? e.g. hex.pm (might)
>
>We’ve have a couple issues come up on the koans project, and we’re considering dropping 1.2 support. That seems pretty sane given koans are about learning, and learners might want to start with the latest (https://github.com/elixirkoans/elixir-koans/pull/181)

**Comment by iamvery** [comment]
Is there anything we can link here to show relevant work? Or perhaps this was closed without intent to complete?

**Comment by ericmj** [comment]
It's hard to make the stats accurate since they are over-represented by CI systems and after we split the registry into multiple files users with many dependencies would also be over-represented.

**Comment by iamvery** [comment]
Makes sense! Thanks for the clarification ❤️
