### ISSUE TITLE
Add section about publishing docs to "Publishing a package" documentation 

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#415]
Add a section here https://hex.pm/docs/publish about how docs publishing works.

**Comment by Qqwy** [comment]
Related to this: The current publishing example mix.exs contains an extra link to externally-published documentation. As documentation is now automatically generated and uploaded to hexdocs, should that line be removed?

**Comment by ericmj** [comment]
> Related to this: The current publishing example mix.exs contains an extra link to externally-published documentation. As documentation is now automatically generated and uploaded to hexdocs, should that line be removed?

Yes :+1:
