### ISSUE TITLE
Email dashboard has display issues on small screens

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#431]

**Comment by simonprev** [comment]
Could you share a screenshot of the issues and which browsers you are using? I’ll try to fix this issue 😄

**Comment by ericmj** [comment]
<img width="418" alt="screen shot 2017-01-19 at 14 17 14" src="https://cloud.githubusercontent.com/assets/316890/22108271/996ffa38-de52-11e6-9e96-acc93972b609.png">

The spacing between the email input and "Add" button.

The "Resend verification email" link is almost not visible.

**Comment by pragmaticivan** [comment]
Can I pick this one?

**Comment by ericmj** [comment]
@pragmaticivan Please do!
