### ISSUE TITLE
Include link to a packages html route in api response 

### ISSUE THREAD

**Issue by enilsen16** [hexpm/hexpm#432]
The url in the packages response changed from a link to the html to a link to the json api. This was the first tweet where this started happening -- https://twitter.com/hex_pm/status/790658737778233344

Was there a specific reason for this change? Looks like it has been happening since yesterday around 12pm PST....

**Comment by ericmj** [comment]
I believe it was a consistency fix. All urls in the in API are intended for discovery of the REST API.

We should add specific website links to the API that points to the HTML resources.
