### ISSUE TITLE
Search dependencies of packages

### ISSUE THREAD

**Issue by bbense** [hexpm/hexpm#450]
Provide a way to search the dependencies of packages. i.e. if I have hex package foo, how can I find all the hex packages that depend on foo?

**Comment by borodiychuk** [comment]
How should it be named? Something like "Reverse dependencies"?

**Comment by ericmj** [comment]
I think "dependents" work.

**Comment by qcam** [comment]
wondering if anyone has taken this issue? otherwise I could take it.

**Comment by ericmj** [comment]
It's up for grabs. Let me know if you want to discuss what it should look like. My idea was to have link from the package page to the package search page with the filled query. The query can be something like "depends:ex_doc" to list all packages that depend on ex_doc.

**Comment by qcam** [comment]
Yeah, that sounds like what is in my mind. Perhaps let me come up with a PR based on the idea and we can discuss further from there.

**Comment by wojtekmach** [comment]
Fixed by #511
