### ISSUE TITLE
feature: short url?

### ISSUE THREAD

**Issue by c0b** [hexpm/hexpm#457]
the domain name hex.pm is already pretty short I think can serve as short url, would be nice to see https://hex.pm/cowboy redirect to https://hex.pm/packages/cowboy ; exceptions are a few ones like https://hex.pm/docs you can reserve

the NPM Registry for NodeJS community is comparable to hex.pm for Erlang / Elixir, they have such feature already, like https://npmjs.com/react redirects to https://www.npmjs.com/package/react which I have been using a lot, saves time to open homepage first and search for the package name

Out of programming language community, this kind of short url redirection is pretty common among others, like many Linux Distros have a package search service, in Debian https://packages.debian.org/hashalot can search for the package name `hashalot` it redirects to https://packages.debian.org/search?keywords=hashalot

Currently in hex.pm the https://hex.pm/cowboy is a 404 page I think it's a big waste;
if many ones like the idea, I would like to devote some time to implement it

**Comment by ericmj** [comment]
The problem is that we before introducing this have to imagine every future top-level endpoints we might have on hex.pm or we are going to break links when we introduce new ones. Do you know how npm solves this?

**Comment by fteem** [comment]
@ericmj I think that `npmjs` has a "catch all" route that basically will redirect any path that does not match a route to the `/packages/:name` route. For example, `npmjs.com/obviously-not-a-package-name` will redirect to `npmjs.com/package/obviously-not-a-package-name`.

If you would like to avoid this (adding a route), maybe a shorter URL like `hex.com/p/cowboy` could work?

**Comment by c0b** [comment]
or another idea could be redefine 404 page to be somewhat smarter: instead of showing this `404 page not found` empty page, we can do reasonable guessing:

1. based on the url route, try search it with known route
   1. search it by package name, if it exists and is the only one, redirect to it
   2. if it's not the only one, show a list view of possible package names
2. search `/docs/...` package name matching failed
3. ... (some more creative thinking)
4. the current `404 page not found` will be served only as the last resort

![image](https://cloud.githubusercontent.com/assets/14798161/21472746/bc17ea10-ca9c-11e6-8a9a-6fd155cf6732.png)

**Comment by ericmj** [comment]
We could add a short url such as `hex.pm/p/PACKAGE`, but I don't really see the use case. Is this for when you enter package names in the browser address bar? We also support open search so if you type "hex.pm" and then [TAB] you browser should allow you to search for packages.

We cannot automatically redirect on `hex.pm/PACKAGE` because that means we would break links in the future.

**Comment by c0b** [comment]
**short url** is to keep link short, that's where you see the tinyurl.com/... bit.ly/... becoming popular and all big players in social network are building their own short link services; it's more useful for sharing: like https://hex.pm/cowboy (https://hex.pm/p/cowboy is also ok) is better than https://hex.pm/package/cowboy

**Comment by ericmj** [comment]
I don't see the benefit to save a few characters, now that we are adding multi repository support there will be even less percentage saved. I think building a separate short linker service for hex.pm would be better or using one of the existing ones you listed.

**Comment by michalmuskala** [comment]
What we could do is show a link to `hex.pm/packages/<name>` on the 404 page that is displayed if you open `hex.pm/<name>`
