### ISSUE TITLE
SEO for specific functions

### ISSUE THREAD

**Issue by JohnB** [hexpm/hexpm#481]
When I search for "elixir enum map" or "elixir enum.map/2" it seems pretty clear to me that I want to end up at `https://hexdocs.pm/elixir/Enum.html#map/2` - but the best result in google is to the main enum page at `https://hexdocs.pm/elixir/Enum.html` - not to the specific function I'm looking for. (yes, I'm lazy; yes, I know I could use the internal search but it doesn't seem any better)

What would it take to increase the SEO for functions? 
* It may be as simple as adding a `name="map"` to the anchor tag. 
* It might also help to change the anchor's `title` from the uselessly-generic "Link to this function" to "map" or "map/2".
* Each function is wrapped inside `<div class="detail" id="map/2">` but this doesn't seem like enough to clue in google to link directly to it. Again, adding a `name` or `title` field that has the arity-less function name (e.g. `map` instead of `map/2`) may help google to find it (yes, without the arity we'll get duplicate names or title, but if this SEO assistance works then at least we'll get *closer* to where we want to go).
* There is a sidebar table of contents that has a `<a href="Enum.html#map/2">map/2</a>` link. This might also benefit from a `name` or `title` field.

I would create a PR for this, but I've been unable to find where the page is generated. Point me to it and I'll see what I can do. Unfortunately, we won't really know if any of this helps until fresh pages get generated, pushed to `hexdocs.pm`, and then indexed by search engines.

**Comment by ericmj** [comment]
Document is generated by (ex_doc)[https://github.com/elixir-lang/ex_doc/]. Does google provide search results with anchor links, I can't recall seeing a link like that.

If it's possible it would be great if you could do some research and see what is needed to make it work. Thank you!
