### ISSUE TITLE
Replace HexWeb.Parallel with Task.async_stream

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#485]
We might get rid of HexWeb.Parallel entirely, or keep it but use Task.async_stream underneath.

**Comment by josevalim** [comment]
How will you handle earlier Elixir versions? Task.async_stream won't fix the spammy behaviour as well (nor the timeout issues).

**Comment by wojtekmach** [comment]
@josevalim I suspect you though this issue is in the hex client repo; on the server we can use whatever Elixir we want.

I agree that just using async_stream won't fix spammy behaviour or timeouts; I think the idea is to first move to async_stream and fix these things on top of that.

**Comment by josevalim** [comment]
Oh, doh. Please ignore me.

**Comment by ericmj** [comment]
> I agree that just using async_stream won't fix spammy behaviour or timeouts; I think the idea is to first move to async_stream and fix these things on top of that.

Yep.

**Comment by druzn3k** [comment]
I'm trying to do this one, and it seems that's going smoothly. I'm keeping `HexWeb.Parallel` and using `Task.async_stream` inside that module. Is anyone else working on this?
