### ISSUE TITLE
Improve display for social sharing

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#486]
Example:

https://twitter.com/whatyouhide/status/838791304263974913

<img width="367" alt="screen shot 2017-03-06 at 20 06 56" src="https://cloud.githubusercontent.com/assets/76071/23625487/9fc0face-02a9-11e7-9d3e-2dadeb07e608.png">

**Comment by ericmj** [comment]
I think we need to support twitter card [1] and open graph [2]. They seem to be very similar [3].

[1] https://dev.twitter.com/cards/overview
[2] http://ogp.me/
[3] https://dev.twitter.com/cards/getting-started#opengraph

**Comment by ericmj** [comment]
Any contributions on this would be appreciated.

**Comment by pragmaticivan** [comment]
Can I pick this one?

**Comment by wojtekmach** [comment]
Please do!
W dniu wt., 7.03.2017 o 08:19 Ivan Santos <notifications@github.com>
napisał(a):
