### ISSUE TITLE
Improve placeholder for profile fields

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hexpm#488]
<img width="717" alt="screen shot 2017-03-06 at 11 20 35 pm" src="https://cloud.githubusercontent.com/assets/301291/23645977/aa09b1be-02c3-11e7-855e-f8dcee935aee.png">

That list of inputs doesn't explain very well what kind of data you should insert.

ex:

twitter: If you add a URL it will break the link.
<img width="503" alt="screen shot 2017-03-06 at 11 22 49 pm" src="https://cloud.githubusercontent.com/assets/301291/23646063/f9c4dc74-02c3-11e7-8936-b34f23be44cb.png">

**Comment by ericmj** [comment]
We do some basic checks to remove the urls when people make mistakes [1] but it doesn't seem to be working in your case, I don't know why. But I agree that we should improve the UI to make sure people enter the correct value. And maybe also add a validation check that it's not a URL entered.

[1] https://github.com/hexpm/hexpm/blob/master/lib/hexpm/accounts/user_handles.ex#L24-L41
