### ISSUE TITLE
Add separate endpoint for release publish

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#489]
The problem with the current `POST /api/package/:name/releases` endpoint is that you can publish a package with a different name in the URL and the metadata. When I found I thought we had a security issue where you could publish a new version for a package you don't own, but fortunately due to other circumstances this was not possible. But you can still publish a package with incorrect metadata, I will be adding an explicit check for this on master.

The question is if we should keep the current check and leave the endpoint as-is or if we should introduce a new endpoint where the package name is not included in the path, if so what should the route be to that endpoint?

EDIT: You actually cannot publish a package with bad metadata but the error message is very confusing. I can improve the error message in one case but not all because doing it for all would mean leaking concerns between the controller and my "context/crud" modules which I don't want to do.

/cc @hexpm/contributors

**Comment by wojtekmach** [comment]
I've spoken with @ericmj and we decided that introducing another `POST /api/packages` endpoint that accepts tarball as request body makes sense. We've also considered `/api/:repository/packages` taking private repositories into consideration, but it's still TBD.

**Comment by ericmj** [comment]
Sounds good. We should name it `POST /api/releases` and `POST /api/repo/:repo/releases` to make the distinction between releases and repositories.
