### ISSUE TITLE
Fix/remove coveralls service link from README

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hexpm#491]
Not sure if that was intentional, but coveralls is not working: https://coveralls.io/github/hexpm/hexpm

If there's intention to still using the service, maybe @ericmj needs to activate again or remove from:
https://github.com/hexpm/hexpm/blame/master/README.md#L108

**Comment by ericmj** [comment]
I removed excoveralls because it did not build on 1.5.0-dev, the error has now been fixed to be a warning instead. But I don't think we should use coverage because the cover tools are not good enough.
