### ISSUE TITLE
Improve publishing documentation about `project.package.name` naming constraints

### ISSUE THREAD

**Issue by Qqwy** [hexpm/hexpm#506]
Based on this issue on `Hex` itself: https://github.com/hexpm/hex/issues/364, it turns out that `project.package.name` is supposed to be in snake_case (lowercase with underscores as spaces) because this name is _usually_ taken from the OTP application name, which _usually_ follows this convention.

`Hex` itself seems (I did not check it myself to make sure) to enforce this, but the documentation does not mention it.

Proposal: Alter the information about `project.package.name` on https://hex.pm/docs/publish to read:

> `:name` The name of the package in case you want to publish the package with a different name than the application name. Usually the same as the name of your OTP application (having the same value as `project.app`), written in snake_case (lowercase with underscores between words).

We should probably bicker a little bit about the exact wording of the statement before I'll open a PR that adds it to the page :slightly_smiling_face: .

**Comment by ericmj** [comment]
> Hex itself seems (I did not check it myself to make sure) to enforce this, but the documentation does not mention it.

It's validated on the server: https://github.com/hexpm/hexpm/blob/master/lib/hexpm/repository/package.ex#L54

> We should probably bicker a little bit about the exact wording of the statement before I'll open a PR that adds it to the page 🙂 .

Your proposal looks great!
