### ISSUE TITLE
Allow to interpolate package version when rendering links

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#516]
Since all `links` are shared between all package releases, it's not possible to construct a version-specific link like:

```
%{
  "CHANGELOG" => "https://github.com/org/repo/blob/1.0.0/CHANGELOG.md"
}
```

because a new release will overwrite it.

We should allow interpolating release version into the links so that when rendered on the Web/API the value is filled in:

```
%{
  "CHANGELOG" => "https://github.com/org/repo/blob/%{version}/CHANGELOG.md"
}
```

thoughts @ericmj?

**Comment by ericmj** [comment]
It seems like a bit of a hacky solution but I guess we need to do this since we can't display the changelog ourselves. I would like to instead find a safe way to render markdown instead of doing these workarounds :(.

Some things to consider is that the package metadata will have the uninterpolated string and we should probably store it like that as well, so that the metadata in the tarball and database is equal, and we only do the interpolation when rendering.

**Comment by wojtekmach** [comment]
>  I would like to instead find a safe way to render markdown instead of doing these workarounds :(

could you elaborate?

> Some things to consider is that the package metadata will have the uninterpolated string and we should probably store it like that as well, so that the metadata in the tarball and database is equal

Yes that's exactly what I was thinking, that both tarball (metadata.config) and row in DB would have e.g. `"../%{version}/CHANGELOG.md"` and we'd interpolate it on the client, that is on Web, on API and when doing `mix hex.info <package>`

**Comment by josevalim** [comment]
I wouldn't say this is a markdown issue but rather a consequence of the fact links are for the package and not for the release. If it was per release, the problem would not exist.

**Comment by michalmuskala** [comment]
Hmm... if we by default generated `mix.exs` with a `@version` module attribute (and this is used by a lot of projects) - this means it would be easy to use `"foo#{@version}bar"` in the links without any special support.

**Comment by ericmj** [comment]
> could you elaborate?

If we included the changelog in the release and we could render and display it on the package page there would be need for this link.

> I wouldn't say this is a markdown issue but rather a consequence of the fact links are for the package and not for the release. If it was per release, the problem would not exist.

If links are per release there would be no way to fix links for old releases.

> Hmm... if we by default generated mix.exs with a @version module attribute (and this is a style used by a lot of projects already) - this means it would be easy to use "foo#{@version}bar" in the links without any special support.

But if we do this we still have the same problem that we are trying to solve that the link points to the wrong version for older releases.

**Comment by ericmj** [comment]
I don't feel like this is a high priority issue. If we need something like this I think it's better to render the changelog directly, see: https://github.com/hexpm/hexpm/issues/560.
