### ISSUE TITLE
PAGE NOT FOUND, no docs

### ISSUE THREAD

**Issue by ZackEyston** [hexpm/hexpm#518]
Hey, 

My package [ExWrapper](https://hex.pm/packages/exwrapper) have a "PAGE NOT FOUND" when i publish it with "hex.publish". However, i check all stuff in my mix.exs and all are good for me.

Can you help me ?

**Comment by wojtekmach** [comment]
you need to change `"exwrapper"` to `"ExWrapper"` here: https://github.com/OpenMercure/ExWrapper/blob/master/mix.exs#L25

See that this URL already works: https://hexdocs.pm/exwrapper/ExWrapper.html

**Comment by ZackEyston** [comment]
Okay, i have make the changement, and push and hex.publish. But the link in hex.pm don't work again .. it redirect to https://hexdocs.pm/exwrapper/exwrapper.html.

**Comment by wojtekmach** [comment]
It works now, the docs aren't immediately refreshed. In the future make sure to first test the docs locally if you find issues on hexdocs.pm. You can do that with `mix docs && open doc/index.html`

**Comment by ZackEyston** [comment]
Okay mea culpa for the time lapse. Thx you for all :+1:
