### ISSUE TITLE
Improve email verification

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#529]
We have identified a few issues with the current sign up and email verification system. Here are the issues we need to fix:

  * [ ] Add link "Resend verification email" link on sign up and log in pages that directs you to a form to enter email.
  * [ ] Add timestamp to verification so that it expires after 24h. Make sure that you can still resend emails after 24h.
  * [ ] When signing up with an email that is already in use we should not leak that we have it in the system. Instead fake that sign up was successful and send an email to the user explaining that there already is an account for this email. Do the same for the password reset form.

**Comment by crownedgrouse** [comment]
Hi, I'm in such issue. I never received confirmation email, cannot send it again, and mix telling me that username is already used. I sent a mail to support but never got answer either. :(

**Comment by crownedgrouse** [comment]
See also #513

**Comment by ericmj** [comment]
@crownedgrouse I don't think we received any such email on support@hex.pm. Can you resend the support email again and give us the username you signed up with?

**Comment by ericmj** [comment]
@crownedgrouse I think I found your user, I resent the email but we haven't received any notifications about bounces or delivery failures so please check your spam folder and verify that the email you gave is correct.

**Comment by crownedgrouse** [comment]
unfortunalety I do not see the confirmation mail, while in the mean time I get the github followup of this issue at same address.  Nothing in Spam folder. Weird.
Could you send a mail from support@hex.pm to email you get in database ?

**Comment by crownedgrouse** [comment]
my bad, i checked my local spam folder, but in webmail of my mail provider I see you mails in spam folder, among others. hirk.  did not notice that a such service was active.
sorry for the noise.

**Comment by crownedgrouse** [comment]
BTW there is a dot at end of the confirmation URL. this could be not well understood by users copying/paste the URL in browser. Add a space at least.

**Comment by ericmj** [comment]
Thanks for the feedback, we will do that.
