### ISSUE TITLE
Documentation download links for Erlang packages not working

### ISSUE THREAD

**Issue by Kapeli** [hexpm/hexpm#532]
Documentation download links for Erlang packages are not working.

Steps to reproduce:
1. Go to https://hex.pm/packages/hackney
2. Under the "Links" section, press the "download" link
3. Result: an AccessDenied page is shown.

**Comment by wojtekmach** [comment]
Thanks for the report. The latest version of hackney (1.8.6 as of writing) does not have associated docs, which explains why the download link points to a file that doesn't exist.

On package page, when there're no docs associated with the latest release, we should either hide the download link or point download link to the latest published docs (possibly marking it a such)

Note, that on individual release pages it works as expected:

- https://hex.pm/packages/hackney/1.8.6 does not have the link
- https://hex.pm/packages/hackney/1.4.7 (the latest release with published docs) has the download link

**Comment by josevalim** [comment]
@wojtekmach I would say there are no docs for that version. Hopefully that will also push library authors to publish their docs. We may also need a mechanism to say the docs exist externally, for tools such as Cowboy.

**Comment by wojtekmach** [comment]
> We may also need a mechanism to say the docs exist externally, for tools such as Cowboy.

@josevalim we can achieve this with setting `links` in package metadata, e.g. for cowboy this could be:

```elixir
links: %{
  "GitHub" => "https://github.com/ninenines/cowboy",
  "User Guide" => "https://ninenines.eu/docs/en/cowboy/1.0/guide/",
  "Manual" => "https://ninenines.eu/docs/en/cowboy/1.0/manual/",
}
```

**Comment by ericmj** [comment]
@Kapeli Thanks for the report. We are working on a fix at https://github.com/hexpm/hexpm/pull/533.

Is Dash using the tarball downloads or does it work by scraping the docs of hexdocs.pm? Would it be possible for Dash to use the API instead and if not what can we do to make it possible?

**Comment by Kapeli** [comment]
Dash uses the tarballs.

I use the API for searching and getting the list of versions available for a package. Once I have that I do HEAD requests to check if tarballs are actually available for the package's versions.

Instead of doing HEAD requests, it would be nice if the packages endpoint (i.e. https://hex.pm/api/packages/hackney) would list whether or not docs are available for each version, or have a separate endpoint for that.

This is a very small issue for me though, the HEAD requests work fine.

**Comment by ericmj** [comment]
I think HEAD requests is the best way to do it. We don't want to add more information to releases on the https://hex.pm/api/packages/hackney endpoint because the payload is already too big for packages with many releases.

A https://hex.pm/api/packages/hackney/docs endpoint may be better in that case that lists the docs for every release of the package.
