### ISSUE TITLE
PAGE NOT FOUND

### ISSUE THREAD

**Issue by krivtsov** [hexpm/hexpm#544]
the text on this page  https://hexdocs.pm/phoenix/controllers.html#content
not working link
> We cover how to use Ecto in a Phoenix project in the [Ecto ModelsGuide](https://hexdocs.pm/phoenix/ecto_models.html).

**Comment by josevalim** [comment]
Thats a bug in the Phoenix docs, not on Hex. The new link should be: https://hexdocs.pm/phoenix/ecto.html
