### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#545]
E.g.: https://hex.pm/packages?search=vault&sort=downloads

![zrzut ekranu 2017-08-11 o 03 11 35](https://user-images.githubusercontent.com/76071/29198284-cb2d6872-7e42-11e7-8c06-e79a6ea406eb.png)

**Comment by ericmj** [comment]
Fixed in f72d4d5aa17b2fd764b7561e67603965dd6b2575, also see a98fa33c72036a5c1bc84a476a1b3f15e3c2485d.
