### ISSUE TITLE
Search results displays packages based off number of downloads recently

### ISSUE THREAD

**Issue by jeramyRR** [hexpm/hexpm#561]
Rust's cargo.io recently announced some new features that were a nice addition to the package managers site.  One such feature is displaying search results based off  a packages number of downloads recently rather than all time by default. 

This feature can be an indicator that a newer project is addressing the needs of the community better than an older project as it will be more popular at the time of search.  This contrasts to the way hex.pm currently displays by total downloads by default.  A package with more downloads doesn't necessarily mean that it is what the community is currently using, only that it was, at one point in time, the most popular.

This may be an easy feature to include in the future as hex.pm already tracks this information and stores it on each packages landing page.  I will take a look at hex.pms repo and see if it's something I can submit myself if the product owners choose to approve this feature.

**Comment by ericmj** [comment]
This sounds like a good idea but first it would be nice to see some examples where changing this would improve the search results.

**Comment by ericmj** [comment]
Actually, we can implement this without examples of search improvements.

We should be he change results and the "Most downloads" on the front page to be based on the downloads for use last 30 days instead of all time downloads.

**Comment by jeramyRR** [comment]
@ericmj, I'd like to implement this feature.  Can you assign it to me?

**Comment by jeramyRR** [comment]
@ericmj,
Attached is a picture of the progress I've made so far.  Any thoughts?

![image](https://user-images.githubusercontent.com/1684189/29904860-98c8df4a-8dd0-11e7-8841-5cc5926105e9.png)

**Comment by ericmj** [comment]
@jeramyRR i think we should show only the "last 90 days" count and call it "recent downloads"

**Comment by wojtekmach** [comment]
Fixed in #566
