### ISSUE TITLE
hexdocs up and running guide "Page not Found"

### ISSUE THREAD

**Issue by ericshively** [hexpm/hexpm#573]
In the Up and Running guide at:

A few paragraphs down is:
"Phoenix assumes that our PostgreSQL database will have a postgres user account with the correct permissions and a password of “postgres”. If that isn’t the case, please see the instructions for the ecto.create mix task."

ecto.create links to: https://hexdocs.pm/phoenix/mix_tasks.html#ecto-specific-mix-tasks

but is "Page not found" and asks me to open an issue.

**Comment by ScottRadcliff** [comment]
Just commenting that I experienced this also and came here to open an issue or contribute in some way.

**Comment by ericmj** [comment]
Please open an issue on the phoenix repository.
