### ISSUE TITLE
/api/packages?sort=downloads no longer works

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#577]
Instead now `total_downloads` or `recent_downloads` needs to be used. hex client is still using `downloads` which is ignored. Thus, e.g.: `cowboy` does not show up at the top:

```
~% mix hex.search cowboy | head
Package                              Version  URL
cowboy_routes_tree                   0.2.0    https://hex.pm/packages/cowboy_routes_tree
cowboy                               2.0.0    https://hex.pm/packages/cowboy
cloudi_service_http_cowboy           1.7.2    https://hex.pm/packages/cloudi_service_http_cowboy
mochicow                             0.6.4    https://hex.pm/packages/mochicow
cowboy_session                       1.0.0    https://hex.pm/packages/cowboy_session
exelli                               0.1.0    https://hex.pm/packages/exelli
lasse                                1.1.1    https://hex.pm/packages/lasse
phoenix_cowboy_logging               1.0.0    https://hex.pm/packages/phoenix_cowboy_logging
raxx_cowboy                          0.2.0    https://hex.pm/packages/raxx_cowboy
```

@ericmj should we change hex client, or support `downloads` again in the API?

**Comment by ericmj** [comment]
@wojtekmach We should probably change back total_downloads to downloads. What do you think?

**Comment by wojtekmach** [comment]
Agreed; I think we can simply transform `total_downloads` to `downloads` in the controller or something along these lines. Thus the API would effectively support: `downloads | total_downloads | recent_downloads`. Or just `downloads | recent_downloads`?

**Comment by ericmj** [comment]
You're right, we should probably support all three because total_downloads has been out for so long.
