### ISSUE TITLE
"Finding documentation" search does not work on Edge

### ISSUE THREAD

**Issue by ilkka** [hexpm/hexpm#583]
Using Microsoft Edge, typing e.g. "Ecto" into the search box and pressing enter results in this error in the console:

```
Object doesn't support property or method 'values'
```

It is thrown from line 100 of the HTML, from the embedded script block. The line in question is

```javascript
var iter, locs = this.responseXML.querySelectorAll("loc").values();
```

There's an [Edge platform issue about the missing iterable implementation](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5998615/), so I guess it will land sometime in the future. A workaround would be nice, but I'm sure this is not a very big blip on your radar :)

**Comment by josevalim** [comment]
@ilkka we would definitely appreciate a contribution that fixes it. :) What do you think?

**Comment by ilkka** [comment]
@josevalim sure, I'll give it a go. I guess it's just vanilla JS in [hexpm/hexdocs-static](https://github.com/hexpm/hexdocs-static/), not built from anywhere else?

**Comment by josevalim** [comment]
That seems to be the case but we can wait until someone else confirms.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Correct, hexdocs-static contains the sources.

**Comment by ilkka** [comment]
Submitted PR GH-9.

**Comment by ericmj** [comment]
Closing in favor of PR.
