### ISSUE TITLE
gravatar without public email address

### ISSUE THREAD

**Issue by NobbZ** [hexpm/hexpm#586]
I'd like to have my gravatar visible, but not my main email address.

If one wants to contact me, he can do so via the issue trackers of the packages, via Twitter or the Forum. Each of these ways will pop up in my mailbox anyway and I will take notice of it.

I wont reply any faster on a direct mail than on a message via the former ways.

Even worse, by not using the issue trackers, any message will be unrelated and unsorted in my mailbox. Notifications by the issuetrackers are bundled in my inbox and also publicly vissible for broader notice.

Still I wan't to be able to have my gravatar to get recognized easily.

**Comment by ericmj** [comment]
In the same way we have a dropdown to select your public email we can have an option for a  dropdown that selects the email used for gravatar. Contributions would be welcome.

**Comment by wojtekmach** [comment]
Closed by #593
