### ISSUE TITLE
discussion: Allow package search with "and"

### ISSUE THREAD

**Issue by supersimple** [hexpm/hexpm#603]
The current package search uses an implicit "or" when entering multiple strings. It has been mentioned an option for searching for a package that contains all entered strings would be useful.

**Comment by OvermindDL1** [comment]
Or if we do something like surround a word in doublequotes then it becomes required, thus surrounding every word in doublequotes essentially turns it into an 'and'.

**Comment by josevalim** [comment]
My vote would be for +. +foo requires it to be present. -foo would require
it to be missing.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
We can probably do these things after we change the search system: https://github.com/hexpm/hexpm/issues/390. Right now I wouldn't want to spend time improving the postgres full text search if we are going to replace it.
