### ISSUE TITLE
Clean up retirement message when reason is other

### ISSUE THREAD

**Issue by supersimple** [hexpm/hexpm#605]
When a package is retired, the retirement html displays the reason. However, if the reason is "other", nothing is displayed. When including a message with the "other" reason, the message starts with a colon (it is used to indicate further information about the reason.)
It works fine for any other reason, but for "other", it looks incorrect. See Screenshot.
<img width="1060" alt="screen shot 2018-01-06 at 11 22 48 pm" src="https://user-images.githubusercontent.com/773380/34647180-ef776d48-f338-11e7-89ff-17bbb1900165.png">

**Comment by supersimple** [comment]
Also, if a message is not included with an "other" reason, there is just an empty red box.

**Comment by ericmj** [comment]
Closing if favor of PR #606.
