### ISSUE TITLE
Add retirement to `GET /api/packages/:name` endpoint

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#607]
Ref https://github.com/hexpm/hex/issues/480#issuecomment-355842543

E.g.:

```
# GET /api/packages/foo
{
  "releases": [
    {"version": "1.0.0", "url": "..."},
    {"version": "1.0.1", "url": "..."},
  ],
  "retirement": {
    "1.0.0": {"reason": "other", "message": "bad"}
  }
}
```

**Comment by wojtekmach** [comment]
@ericmj forgot to mention, representing retirement like this will allow us to also add it to the `GET /api/packages` list endpoint. I think we can do that because I'd guess most packages would have 0 or only a few retired releases so we wouldn't increase the payload by much. No need to do that yet though, we can wait on that for a use case.

**Comment by supersimple** [comment]
This should be closed now. https://github.com/hexpm/hexpm/pull/616

**Comment by supersimple** [comment]
This should be closed now. https://github.com/hexpm/hexpm/pull/616

**Comment by wojtekmach** [comment]
👍
