### ISSUE TITLE
Something wrong with docs layout

### ISSUE THREAD

**Issue by azatmurtazin** [hexpm/hexpm#614]
For example:

https://hexdocs.pm/mogrify/Mogrify.html

![img](https://i.imgur.com/7Dc1Ccr.png)

**Comment by josevalim** [comment]
We just host the assets. The docs are completely generated by the mogrify package. Please ask them to update their ex_doc version and run `mix hex.publish docs` to get a fresh looking one.

**Comment by josevalim** [comment]
Thanks!
