### ISSUE TITLE
Broken Link to "Using MySQL Guide"

### ISSUE THREAD

**Issue by fireproofsocks** [hexpm/hexpm#617]
The page https://hexdocs.pm/phoenix/ecto.html contains a link labeled "Using MySQL Guide" which points to https://hexdocs.pm/phoenix/using_mysql.html  
That page is a 404.  Where is the MySQL Guide?

**Comment by josevalim** [comment]
This is an issue with the Phoenix package. It has supposedly been fixed here: https://github.com/phoenixframework/phoenix/issues/2641

@ericmj @wojtekmach I am thinking we should include a javascript in the 404 page. The javascript would parse the path and send it to Hex API asking: is this a valid package path? If so, does the package exist? If so, does this version have docs? The Hex API would return important information like the package name, version and docs availability so we can build a reasonable error message to users, possibly linking to the package+version or the package page, so they can report the bug in the proper place.

**Comment by ericmj** [comment]
Yeah, I think that's a good idea. I have opened a new issue to track this.
