### ISSUE TITLE
Add checks for common errors on hexdocs 404 page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#618]
Comment from @josevalim in https://github.com/hexpm/hexpm/issues/617#issuecomment-357417808:

> I am thinking we should include a javascript in the 404 page. The javascript would parse the path and send it to Hex API asking: is this a valid package path? If so, does the package exist? If so, does this version have docs? The Hex API would return important information like the package name, version and docs availability so we can build a reasonable error message to users, possibly linking to the package+version or the package page, so they can report the bug in the proper place.

**Comment by jeffreyplusplus** [comment]
Is anyone working on this?

**Comment by ericmj** [comment]
No, I don't believe so.

**Comment by jeffreyplusplus** [comment]
Does the existing `get "/api/packages/:name/releases/:version"` route already meet most of the requirements?

Using the invalid url (https://hexdocs.pm/phoenix/using_mysql.html) from the comment as an example: 
The proposed JS on the 404 page for that link would parse the url, call hex.pm/api/packages/phoenix/releases/latest/, and get back the package information needed to display a more robust 404 page.

Would the only additional work on the hexpm side be to 1. modify the `get "/packages/:name/releases/:version"` route to assume the latest version when latest is passed in as a version number and 2. add an invalid package error alongside the existing invalid version error?

**Comment by ericmj** [comment]
> Does the existing get "/api/packages/:name/releases/:version" route already meet most of the requirements?

Yes, or more specifically the `/api/packages/:name` endpoint. That way we don't have to modify hexpm to add a "latest" version endpoint and a 404 response should show that there is no package by that name.

**Comment by jeffreyplusplus** [comment]
Ah, ok. Does that mean no changes are necessary in the hexpm repo? All that's needed is JS in the hexdocs project to parse the path and call `hex.pm/api/packages/:name` to get enough information to display the desired package information?

**Comment by ericmj** [comment]
I believe so, yes.

**Comment by JMurphyWeb** [comment]
Ah @jeffreyplusplus are you on this?

**Comment by jeffreyplusplus** [comment]
No, it doesn't look like any work is needed in this repo.

**Comment by joshdcuneo** [comment]
I'm keen to work on this over on hexpm/hexdocs-static. Does the Hex team have any browser support guidelines? It doesn't look like any of the existing projects use javascript at all.

**Comment by joshdcuneo** [comment]
This is a little more complex than it appears at face value. The error page is served on `hexdocs.pm` so it is not possible to call the hexpm API directly from the browser due to CORS.

**Comment by ericmj** [comment]
hexpm has some javascript: https://github.com/hexpm/hexpm/tree/main/assets.

We don't have any specific browser support rules. Are users are developers so I think we can assume modern browsers. Here are some stats for https://hex.pm:

<img width="548" alt="Screenshot 2021-07-26 at 18 34 57" src="https://user-images.githubusercontent.com/316890/127025827-a5279943-f048-4280-8332-595878d2b97a.png">
<img width="548" alt="Screenshot 2021-07-26 at 18 35 03" src="https://user-images.githubusercontent.com/316890/127025823-0516d583-e4c7-4273-8f44-f72fc911c9d3.png">
<img width="548" alt="Screenshot 2021-07-26 at 18 35 15" src="https://user-images.githubusercontent.com/316890/127025822-008b314b-c441-444f-8729-7133cbdeab26.png">
<img width="548" alt="Screenshot 2021-07-26 at 18 35 23" src="https://user-images.githubusercontent.com/316890/127025816-acdf216b-d8a1-40b0-ab88-d367233568db.png">

**Comment by joshdcuneo** [comment]
Perfect. Thanks for the info.

**Comment by ericmj** [comment]
This would be nice to have but currently not planned.
