### ISSUE TITLE
FOUC in Firefox

### ISSUE THREAD

**Issue by michallepicki** [hexpm/hexpm#619]
When loading a package's page with Firefox (e.g. https://hex.pm/packages/poison), for a brief moment the screen is taken over by a huge black-and-white icon (see screenshot below). When browsing through packages, this causes the screen to flash from white to black and back to white multiple times.

We can probably improve browsing experience by inlining some of the styles used by these icons in the html code.

Browser and OS used: Firefox Nightly 59.0a1, Ubuntu 16.04

![hex pm huge icons while loading](https://user-images.githubusercontent.com/4972756/34991210-10708448-fac9-11e7-9e95-93aba35d542f.png)

**Comment by ericmj** [comment]
Is this what you reported as bug to Firefox @michalmuskala? I thought if your style tag is in `<head>` the rendering should block until CSS is loaded.

I guess we can fix the issue on our end even it's a browser bug. 👍

**Comment by michallepicki** [comment]
Right, so the actual problem is with Firefox. People at stackoverflow say it may be because of the `autofocus` html attribute. We can set it with javascript instead: https://stackoverflow.com/a/43794008

**Comment by ericmj** [comment]
That sounds like a good idea. @michallepicki Would like to try it out?

**Comment by michallepicki** [comment]
Yes, I'll make a PR or write back when I know if it is the cause.
