### ISSUE TITLE
Incorrect redirect when going to package's documentation

### ISSUE THREAD

**Issue by cjbottaro** [hexpm/hexpm#622]
Going to the default documentation page:
https://hexdocs.pm/faktory_worker_ex/
incorrectly redirects to:
https://hexdocs.pm/faktory_worker_ex/README.html
(README should be lower cased)

The strange thing is that going to a specific version:
https://hexdocs.pm/faktory_worker_ex/0.5.0/
redirects to the _correct_ page:
https://hexdocs.pm/faktory_worker_ex/0.5.0/readme.html

Thanks!

**Comment by wojtekmach** [comment]
https://hexdocs.pm/faktory_worker_ex/ correcty redirected to https://hexdocs.pm/faktory_worker_ex/readme.html - could you double-check, clear browser cache etc?

Btw, `main: "README"` should be `main: "readme'` for markdown pages in [1], see e.g. on [2]

[1] https://github.com/cjbottaro/faktory_worker_ex/blob/2084bf0c7761d6898ff69f5b01fd5e73fc90b7bf/mix.exs#L31
[2] https://github.com/elixir-lang/ex_doc/blob/v0.18.1/mix.exs#L62

**Comment by cjbottaro** [comment]
Cool, thanks... yeah was caching issue. Sorry about that.

**Comment by wojtekmach** [comment]
no worries!
