### ISSUE TITLE
Differentiate between active and retired packages on the user profile page

### ISSUE THREAD

**Issue by lee-dohm** [hexpm/hexpm#623]
I really like the "retire" feature! It allows me to mark packages as unmaintained but still not break things by unpublishing them.

I think it would be nice if, on one's user profile page, there would be some indication if the latest version of a package was retired. Maybe have a subheading of retired packages separate from the active ones?

**Comment by wojtekmach** [comment]
> (...) if the latest version of a package was retired. Maybe have a subheading of retired packages separate from the active ones?

Something we've previously discussed was a notion of "retired package" meaning the package as a whole is retired (e.g. project got renamed, there are better alternatives, abandoned etc). I think if we have that then annotating and/or displaying them in a separate subheading would make sense.

For now, I think if latest release got retired it doesn't necessarily mean the package as a whole is abandoned.

**Comment by lee-dohm** [comment]
Fair enough! Thanks for the update.
