### ISSUE TITLE
Application Error when publishing a package

### ISSUE THREAD

**Issue by rstacruz** [hexpm/hexpm#624]
Running `mix hex.publish` results in a Heroku application error page:

> ![image](https://user-images.githubusercontent.com/74385/35210634-fcf578d2-ff8d-11e7-9597-c426067f4048.png)

Steps to reproduce:

```js
git clone https://github.com/rstacruz/authsense.git
cd authsense
git checkout 76a938c03cd0fb11aa1f2cb0c18d3f76bfa1d0de
mix deps.get
mix hex.publish
```

**Comment by rstacruz** [comment]
oops, i pushed it now, you can try again.

**Comment by rstacruz** [comment]
Btw, using:

- Hex v0.17.3
- Mix 1.6.0
- Elixir 1.6.0

**Comment by rstacruz** [comment]
Full logs: https://gist.github.com/rstacruz/aa98fb913695f4055f00476d1769f77c

**Comment by ericmj** [comment]
I cannot reproduce the issue:

```
✗ mix hex.publish package
Building authsensetest 1.0.0
  Dependencies:
    pbkdf2_elixir ~> 0.12 (app: pbkdf2_elixir)
    comeonin ~> 4.0 (app: comeonin)
    plug ~> 1.0 (app: plug)
    ecto ~> 2.0 (app: ecto)
  App: authsensetest
  Name: authsensetest
  Files:
    lib
    lib/authsense
    lib/authsense.ex
    lib/authsense/exceptions.ex
    lib/authsense/plug.ex
    lib/authsense/service.ex
    mix.exs
    README.md
  Description: Sensible helpers for authentication for Phoenix/Ecto.
  Version: 1.0.0
  Build tools: mix
  Licenses: MIT
  Maintainers: Rico Sta. Cruz
  Links:
    github: https://github.com/rstacruz/authsense
  Elixir: ~> 1.5
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.
Proceed? [Yn] Y
Local password:
[#########################] 100%
Package published to https://hex.pm/packages/authsensetest/1.0.0 (9c6013724aa1431dfc752c1f64b45e94e79c1b5294a8b6aff95432e01c95af04)
```

Is it possible that publishing the package takes a long time and server side timeout is being triggered? Can you run it as `time mix hex.publish` to show the timing?

**Comment by rstacruz** [comment]
It's still the same problem for me. I don't think it's a timeout, it works fast enough.

> 5.91 real
> 1.70 user
> 1.04 sys

**Comment by rstacruz** [comment]
I also did `rm -rf _build deps; mix deps.get; mix hex.publish` and still the same.

**Comment by rstacruz** [comment]
I also tried `authsensetest` as the name, just like you did

```
〉mix hex.publish
Building authsensetest 1.0.0
  Dependencies:
    pbkdf2_elixir ~> 0.12 (app: pbkdf2_elixir)
    comeonin ~> 4.0 (app: comeonin)
    plug ~> 1.0 (app: plug)
    ecto ~> 2.0 (app: ecto)
  App: authsensetest
  Name: authsensetest
(...snip...)

Publishing package to public repository hexpm.
Proceed? [Yn]
Building docs...
Compiling 4 files (.ex)
Generated authsensetest app
Docs successfully generated.
View them at "doc/index.html".
Local password:
Publishing package...
[#########################] 100%
Publishing failed
<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
  (..snip..)
        </html>
```

**Comment by rstacruz** [comment]
This seems like what's triggering it:

https://github.com/hexpm/hexpm/commit/44c2db8c0cab55c53df7a13c839a038aaec67bc2

and my IP address is `124.105.127.188`

**Comment by ericmj** [comment]
I have unbanned your IP. You were automatically IP-banned, probably because you were using credo with vscode which spams the hex API with update checks. I would recommend updating your credo and your vscode plugins to prevent being IP banned again.

**Comment by ericmj** [comment]
This commit https://github.com/hexpm/hexpm/commit/70059f2f590f3a705d39ed47535c22a648e4ff29 should ensure the users sees the correct error message when the request is blocked.
