### ISSUE TITLE
View for "packages needing some love"

### ISSUE THREAD

**Issue by tsutsu** [hexpm/hexpm#625]
It would be quite nice to be able to see, on the hex.pm site, which published (open-source) Hex packages are experiencing "code rot"—i.e. are having problems due to a lack of recent fixes, that could be solved by contributing PRs to them. Probably such a view would be sorted (by default) by a combination of the severity of the problems and the popularity/recent downloads of the package, to point potential contributors to the packages where contributions would help the most people.

There are several technical problems that might qualify a package for appearing on such a list, some of which are cheap to calculate (e.g. find packages with outdated deps that constrain your own deps to resolve older; find packages pinned to old Elixir versions; find packages with little documentation coverage) and some which are more expensive (e.g. find packages whose current version has more failing `mix test` cases under the current Elixir version+current deps resolution, than it did when it was originally published.) I imagine packages might be ranked in such a list by the sum of the number of these problems it has; perhaps with some problems weighted more severely than others. 

The simple fact of the age of the most recent version published of a package might also be useful as a factor in these determinations. Some packages are, in fact, "done", needing no further updates, and so by itself package-latest-version-age can't be labelled as a problem; but package-latest-version-age might, for example, aid in determining which packages to run the more expensive checks on first, if more expensive checking that cannot be accomplished with a simple database query is deemed worthwhile.

Also, it might be helpful to differentiate between packages that are actually in need of PRs, and packages that have been seemingly abandoned by their maintainers despite the presence of PRs that would fix such problems. This could likely be determined—for packages that have a Github repo link, at least—by using the Github API to query the number of open PRs with ages exceeding some threshold. These seemingly-abandoned packages would be better served by having this property listed wherever they appear in the existing package views, since this fact is useful for all users, not just potential contributors.

**Comment by michalmuskala** [comment]
While I think those informations would be very useful, I don't think hex itself is the place for it. A lot of those metrics are subjective one way or the other or rely on external data - with github being most common. This is problematic because publishing a hex package does not require you to have any other account than hex itself, linking to github or other issue trackers is entirely optional.

 I think it's a good idea to develop such a project separately from hex itself - hex exposes a lot of data through the API that should be enough to develop desired features.

**Comment by pragmaticivan** [comment]
Hey @tsutsu maybe you can propose something like that on https://extracurricular.elixirschool.com/

**Comment by ericmj** [comment]
We are not planning to tackle any community or social features like this right now. We are focusing on the core of the package manager and think other websites can solve this in better ways using the public HTTP APIs from hex.pm.
