### ISSUE TITLE
Error in Ecto>Getting Started>Validating changes

### ISSUE THREAD

**Issue by kosbas** [hexpm/hexpm#629]
Hello, I'm new to programming. It looks like you have an error in your instructions. Or the instruction is obsolete.
https://hexdocs.pm/ecto/getting-started.html#validating-changes

Do not work:

`defmodule Friends.Person do
  use Ecto.Schema

  schema "people" do
    field :first_name, :string
    field :last_name, :string
    field :age, :integer
  end
  def changeset(person, params \\ %{}) do
    person
    |> Ecto.Changeset.cast(params, [:first_name, :last_name, :age])
    |> Ecto.Changeset.validate_required([:first_name, :last_name])
  end
end`

Work:
`defmodule Friends.Person do
  use Ecto.Schema
  import Ecto.Changeset

  schema "people" do
    field :first_name, :string
    field :last_name, :string
    field :age, :integer
  end

  def changeset(person, %{} = params) do
    person
    |> cast(params, [:first_name, :last_name, :age])
    |> validate_required([:first_name, :last_name])
  end
end`

The answer found [here](https://elixirforum.com/t/adding-multiple-associations-with-one-cast/8188/2).
`kos@kos-Extensa-5220:~/phoenix/friends$ mix -v
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.5.2
`
`kos@kos-Extensa-5220:~/phoenix/friends$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
  connection 1.0.4
  db_connection 1.1.3
  decimal 1.4.1
  ecto 2.2.8
  poolboy 1.5.1
  postgrex 0.13.4
All dependencies up to date
`

**Comment by wojtekmach** [comment]
the guide is correct. You don't need to `import Ecto.Changeset` in order to call ` Ecto.Changeset.cast` and other functions. But If you'd want to call with just `cast` (without `Ecto.Changeset.`) then yes, you need to import.
