### ISSUE TITLE
Search for "aws lambda" misses the "ex_aws_lambda" package

### ISSUE THREAD

**Issue by DevJac** [hexpm/hexpm#633]
![screen shot 2018-02-19 at 11 18 37 am](https://user-images.githubusercontent.com/5282489/36392088-cbf6924a-1566-11e8-8b81-43e6e5ecb0d5.png)

As can be seen in the screenshot, searching for "aws lambda" on hex.pm seems to miss the only package that has both "aws" and "lambda" in its name, instead matching on a variety of unrelated packages.

https://www.hex.pm/packages/ex_aws_lambda is the package I was searching for. I think it should have been in the search results. I haven't shown all the search results in my screenshot, but this package was not one of them.

**Comment by ericmj** [comment]
Unfortunately I don't believe we can fix this without changing the search infrastructure we have today. It is planned to switch from postgres trigram + full text search to a better suited solution but it's not on the immediate roadmap. Contributions are of course always welcome to the existing search or if you have any plans for a better solution.

**Comment by DevJac** [comment]
Thank you for the reply and acknowledging the issue. I may take a look to see if the current search can be improved as you suggested. 😄
