### ISSUE TITLE
Organizations billable email

### ISSUE THREAD

**Issue by bcardarella** [hexpm/hexpm#642]
Not sure if this is the right place for this, but entering billing information for my organization I am presented with a `<select>` element rather than a text field for the Billing email. This list is limited to just my account email. Even if there is a way to expand the list by adding alias emails to my account, I believe it is best to have a text field here. Many organizations will have a different account specifically meant for invoicing/billings.

**Comment by ericmj** [comment]
I agree that the select is limiting. The reason I went with the select over a free text field is that we already have email verification set up for the emails associated with your account.

Do you think it is worth it to a text field over a select even if we don't add verification for it? Maybe we should invoices to all admins + a billing email entered via text field?

**Comment by josevalim** [comment]
@ericmj maybe you just need a link saying "Add a new e-mail address" that links to the proper page?

**Comment by ericmj** [comment]
Closed wrong issue.

**Comment by bcardarella** [comment]
> Maybe we should invoices to all admins + a billing email entered via text field?

The reason we have a different email account to handle invoices is so personal accounts don't get inundated with invoices. Also, making sure that the invoices get to the correct person for payment, or for record keeping.

**Comment by ericmj** [comment]
@bcardarella Would @josevalim's suggestion work then? Or do you not want to add the email for invoices to your own account?

**Comment by bcardarella** [comment]
Maybe? If email verification is something that is a must-have then it could. But verifying the email mail not be possible for certain orgs. For example, the email recipient could be a record keeping system that isn't actually accessed directly by a person. Also, verification is typically something meant for security purposes around account access. There are many other services that use the plain text field for billing email, for example see Travis:

![screen shot 2018-03-06 at 8 41 29 am](https://user-images.githubusercontent.com/18524/37035527-da01e276-211a-11e8-8539-463e79defa2a.png)

**Comment by bcardarella** [comment]
Looking at the Hex email dashboard, would this allow someone to sign into my account with any of the emails added? If so this isn't somewhere I'd want to add an email address that others may have access to.

**Comment by ericmj** [comment]
You are right, account emails and billing emails have different security requirements. I will change to a free text field without any verification.

**Comment by bcardarella** [comment]
Awesome, thanks for hearing me out :) Once't its deployed we'll sign up for the paid account!

**Comment by ericmj** [comment]
@bcardarella We have deployed with the change. Thanks for the feedback and please let us know if you have any issues or more feedback.
