### ISSUE TITLE
Allow Org to have public packages

### ISSUE THREAD

**Issue by yordis** [hexpm/hexpm#645]
I would love to have a Org profile were people could see all the packages under the Org rather than publishing the packages in behave of my personal account.

One other important reason why to have it is that some of the packages could belong to specific company so if one of the engineers decide to not work for the company anymore we do not want to relay on him/her on the Hex management because the package should belong to the Org itself but turn out that him/her is one of the maintainers.

From Organization/Company point of view, we want to embrace the team work instead of individuals as well.

**Comment by wojtekmach** [comment]
It's a workaround around the limitations of the system, so not sure if I should be promoting it, but one thing you can already do is to create a Hex user representing your company and add that user as a maintainer to the packages. We plan to add finer-grained permissions in https://github.com/hexpm/hexpm/issues/380 so in the future you'll be able to mark that user as the only one being able to add/remove other maintainers.

> I would love to have a Org profile were people could see all the packages under the Org rather than publishing the packages in behave of my personal account.

In a sense the current model is actually more flexible because on the outside, looking at just hex.pm/packages/foo, the package belongs to neither particular user nor to an organization. So while the stewardship of the package can change back'n'forth between individuals and companies the name stays the same.

**Comment by ericmj** [comment]
Something I have been thinking about is making organizations user accounts as well. If we add permission levels in #380 then we would get organization ownership of public packages almost for free.

**Comment by yordis** [comment]
> but one thing you can already do is to create a Hex user representing your company and add that user as a maintainer to the packages.

@wojtekmach that is what I am doing but that person will become the bottleneck of the Org, unless you give everyone the account credentials and hopefully you dont need to change it that much.

The second bullet point is more for go to `/org/:name` and be able to see all the packages under that Org,

or be able from the package profile to see if the package is maintained under specific Org.

This will help agencies and company that does work for other companies, like Plataformatec, Infinite Red and so on.

If we add the support for public packages under the Org, this could be a possibility.

**Comment by yordis** [comment]
@ericmj we could do that, but what would happen if one account wants to manage and pay for multiple Orgs?

Right now I have this situations, no like I am posting things on Hex, but from business perspective I am in charge of two LLCs.

So at that moment will be better is `org` is it own entity.

What do you think?!

**Comment by ericmj** [comment]
> we could do that, but what would happen if one account wants to manage and pay for multiple Orgs?

You will still be able to admin multiple organizations like you can today.

**Comment by yordis** [comment]
@ericmj right, but making two Orgs account become problematic to manage.

This is the same situations with Github account, my Github account could belong to multiple Orgs and by so I can work for multiple companies or manage multiple Orgs.

But if you roll with making the Org the actual account we will end up creating Orgs accounts for everything.

It is like, Slack vs Discord/Github, for this, I would prefer that Orgs management is under an account rather than creating Org accounts.

**Comment by ericmj** [comment]
You would create organizations the same way they are created today so you would not be creating any separate accounts. Your own account that you log in with can manage both organizations like it can today. The fact that organizations are also users would not bring any more management work for you and you would not be able to log in to the organization user.

**Comment by ericmj** [comment]
We are planning on linking users and organizations but closing this issue now because it has diverged from the original feature request.
