### ISSUE TITLE
Low framerate when scrolling on a documentation page in Safari for desktop

### ISSUE THREAD

**Issue by kottkrig** [hexpm/hexpm#659]
Scrolling on a documentation page in Safari 11.1 for desktop results in a very low framerate.

### Steps to reproduce:

1. Go to a documentation page: https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html
2. Scroll up and down

### Some thoughts:

1. It seems to be connected to how large the browser window is. The framerate drops when I increase the window size.
2. Code blocks also seems to affect the framerate. It drops even lower when a code block is in the viewport.

**Comment by kottkrig** [comment]
I digged a little deeper and it seems to be directly connected to repaints due to `overflow-y: auto;` on the class `.content`. The framerate increases dramatically when I disable this property. 

I tried to add the property `will-change: transform;` but that doesn't seem to help.

**Comment by josevalim** [comment]
Thanks @kottkrig! hexdocs only hosts the documentation. This should be reported to the [ex_doc](github.com/elixir-lang/ex_doc) project instead. A PR is defintiely welcome (if you can figure out a proper fix). :)

**Comment by kottkrig** [comment]
Thanks for the heads up about the [hex_doc](https://github.com/elixir-lang/ex_doc) repository. I will see what I can do. :)
