### ISSUE TITLE
Do not rate limit requests from Fastly

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#660]

**Comment by nashby** [comment]
@ericmj hey, what kind of requests come from Fastly? Was wondering if that's possible to implement using ip ranges https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges

**Comment by coryt** [comment]
There seems to be a PR already merged that added support for this. https://github.com/hexpm/hexpm/pull/546

Can you clarify what the bug is?

**Comment by coryt** [comment]
I took a closer look at this and I think the issue is that the fastly public ip list isn't being used, is that correct?

**Comment by ericmj** [comment]
It seems to be already implemented, indeed. Thanks for checking.
