### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [hexpm/hexpm#662]
[The official Hex website](https://hex.pm) is inaccessible over IPv6.

AWS EC2 VPCs support IPv6, so this should be fairly easy to fix. See [the very extensive VPC IPv6 migration guide](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-migrate-ipv6.html).

**Comment by ericmj** [comment]
Heorku does not support ivp6 so this is not possible until heroku adds support or we migrate away from heroku.

**Comment by tambry** [comment]
I don't think it's appropriate to close this, as the issue still exists.

**Comment by ericmj** [comment]
The issue still exists but it is currently out of our control or would require too much work and would be of small immediate benefit. Since the issue is not actionable we are closing it because we don't keep issues open that we can not work on, see http://blog.plataformatec.com.br/2014/05/tips-for-keeping-your-open-source-software-issues-tracker-tidy/ "ABC (Always Be Closing)".

**Comment by tambry** [comment]
What about hexdocs.pm? That seems to use Fastly, which has IPv6 support.

**Comment by ericmj** [comment]
We can do it for hexdocs.pm and repo.hex.pm which both use Fastly. For hexdocs.pm it should just be a matter for switching to Fastly's dualstack. For repo.hex.pm we also need to make sure that the download stats job works correctly with IPv6 addresses.

**Comment by ericmj** [comment]
The AAAA record for hexdocs.pm should now be up. I will work on repo.hex.pm next.

**Comment by tambry** [comment]
I'm afraid I don't see any AAAA records on hexdocs.pm.

**Comment by ericmj** [comment]
It seems that for hexdocs.pm we are using older Fastly infrastructure that does not seem to support dualstack. I will investigate.

**Comment by ericmj** [comment]
Seems to be working for hexdocs.pm and repo.hex.pm now. Can you verify @tambry?

**Comment by tambry** [comment]
Can confirm that it works now for both of those. Thanks for fixing those!
