### ISSUE TITLE
Add ability to change username of user

### ISSUE THREAD

**Issue by edbedbe** [hexpm/hexpm#665]
I just went to change my username and didn't find it as an available option in the `mix hex` tasks or the Hex web interface.

Am I missing it, or is it not possible right now? I would be down to make a pull request to add the capability. I would make a pull request to this repo first, then to the `hex` repo to add the front-end interface to the new API endpoint.

**Comment by ericmj** [comment]
We are not planning to add this to the UI, but if you want to change username you can contact support@hex.pm.

**Comment by edbedbe** [comment]
Thank you!
