### ISSUE TITLE
Allow API or Listing of Packages from Repo URL

### ISSUE THREAD

**Issue by HangingClowns** [hexpm/hexpm#666]
I’m in the middle of setting up a mirror for official support of hex within my company firewall. 

I’ve been told if there’s a way for them to get a list of all packages and where they are by a URL then they can easily setup a mirror. Originally they tried to use https://repo.hex.pm but this is returning an unauthorized response, so they are unable to query for all available packages. I believe what another mirror is doing is downloaded a DETS registry file and parsing that. 

They have said there’s at least two ways for them to mirror. One is to follow how maven does: http://repo1.maven.org/maven2/ which will allow them to see all available files and folder structures to mirror.

Another possibility is to follow what npm does: https://registry.npmjs.org which I believe uses an api to let them find all available packages.

@josevalim This is what I’ve found after talking with you at elixir/ruby conf in Taiwan this past weekend.

**Comment by ericmj** [comment]
We have both an HTTP API and registry you can use to discover packages. For the HTTP API you have https://github.com/hexpm/specifications/blob/master/apiary.apib#L238 and in the registry https://github.com/hexpm/specifications/blob/master/registry-v2.md#namesproto.

I would recommend using the registry because it is much faster.

**Comment by HangingClowns** [comment]
This is good but I don’t see a link to directly downlod the packages which is what I would need to “scrape” for a mirror. I suppose I would need to replace the base url and a few others.

**Comment by ericmj** [comment]
There are no direct links, you have to build the URLs from package name and version, https://github.com/hexpm/specifications/blob/master/endpoints.md#endpoints-1.

**Comment by josevalim** [comment]
@HangingClowns so the thing I have in mind and I plan to have it ready soon would allow you to download the specifications and packages that you are currently using. This synchronization is manual, so you would need to remember to push the packages somewhere when you update things. The advantage is that you don't need to maintain a full proxy. All you need to do is to put a dumb http server in front of those packages. Is that acceptable for you?

**Comment by wojtekmach** [comment]
@HangingClowns we're working on https://github.com/hexpm/hex_erl that will make building repositories and/or mirrors easier, e.g. you can do:

```elixir
iex(2)> :hex_repo.get_names()
{:ok,
 %{
   packages: [
     %{name: "a_message"},
     %{name: "aadya"},
     %{name: "aatree"},
     %{name: "aba_api"},
     %{name: "aba_cli"},
     %{name: "aba_model"},
     %{...},
     ...
   ]
 }}
iex(3)> :hex_repo.get_versions()
{:ok,
 %{
   packages: [
     %{name: "a_message", retired: [], versions: ["1.0.0"]},
     %{name: "aadya", retired: [], versions: ["0.1.0"]},
     %{name: "aatree", retired: [], versions: ["0.1.0"]},
     %{name: "aba_api", retired: [], versions: [...]},
     %{name: "aba_cli", retired: [], ...},
     %{name: "aba_model", ...},
     %{...},
     ...
   ]
 }}
iex(4)> :hex_repo.get_tarball("a_message", "1.0.0")
{:ok, <<86, 69, 82, 83, 73, 79, 78, 0, ...>>,
 [cache: :miss, etag: "\"201a8090ece8b7bcafe11964a7fa2a5d\""]}
```

I'll adjust `get_names` and `get_versions` functions to also handle caching with etags in next couple of days.

You can identify your mirror via UserAgent (that will help us support your mirror a lot) like this:

```elixir
options = [client: %{adapter: :hex_http_httpc, user_agent_fragment: "(httpc) (some_hex_mirror/1.0)"}]
:hex_repo.get_names(options)
```

hex_erl is still under active development but we don't expect to make major breaking changes.

**Comment by HangingClowns** [comment]
@josevalim that would be good. I'm just thinking about company wide, it would be great if we can integrate with the [artifactory](https://www.jfrog.com/jira/browse/RTFACT-14011), as we are already using it within the company. We have java, node, ruby, and I believe a few others working just fine that way.

If another team is going to be doing elixir, the barrier for them to enter, would be lower if we can just setup a mirror for them to point to. On the other hand, after speaking with some people, your manual method should suffice as I can create a project and push folders and packages directly on to there to match the correct structure of the URL.

@wojtekmach I believe I can use that library to do something like an escript to sync current packages on hex and push them onto the "dumb server"?

**Comment by josevalim** [comment]
@HangingClowns I agree support for artifactory would be great but that's really out of our scope/not up to us. That's why I asked if a manual step for now is enough, it will hopefully allow folks to get started.

Also, do you use network partitions/shared drivers? Because we could add support for those too, so you don't need to have a "dumb server".

**Comment by josevalim** [comment]
Can you mount those directories and access the file through the file
system? For example, if you mount it, can you access it with File.read?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by HangingClowns** [comment]
Yes, I believe i can. I can confirm for you, for sure, tomorrow. I know for sure I can copy and open files through the windows explorer without an issue, so I'm guessing should be fine. The format: `\\MACHINE_NAME\shared_folder`

**Comment by josevalim** [comment]
Great! If can confirm tomorrow with the exact path that works for reading
across drivers it will help us a lot.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by HangingClowns** [comment]
So interesting... I get an error with cmd and elixir for trying to read files from there saying “CMD does not support UNC paths as current directories”. But I used pushd \\ComputerName/SharedFolder and I was able to cd to the directory and it worked. 

https://serverfault.com/questions/50085/how-do-you-handle-cmd-does-not-support-unc-paths-as-current-directories?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by HangingClowns** [comment]
Looks like after I’ve mapped it to a drive letter I can read it without an issue. This can help with dev but maybe won’t be useful for a ci server.

**Comment by HangingClowns** [comment]
Is there an issue # for the changes that will be made to hex so I can follow progress? @josevalim

**Comment by josevalim** [comment]
@HangingClowns no changes will be necessary to Hex. The goal here is to help with CI but if CI can't read from the shared driver, you will need a dumb server in front. I still need to finish the script but it should be out hopefully soon.

**Comment by josevalim** [comment]
Sorry for delay @HangingClowns, but I have been trying to find time to finish this and failing. The idea though is not very complicated. The idea was to have a script (or a mix task) that traverses the mix.lock file of the project and get all hex dependencies and their versions. Then you would request the registry information for each hex package you find, as well as, that specific package version, and copy it to the local directory. You can see the paths in the [endpoints document](https://github.com/hexpm/specifications/blob/master/endpoints.md#endpoints-1) @ericmj sent earlier.

Later, if you serve this exact same structure from your in-company proxy, you should be good to go. All you need to set is HEX_MIRROR variable.

If you want, you can also store rebar and hex archives, fetched by local.rebar and local.hex respectively in the in-company proxy. You can look at the implementation of those tasks to get the addresses.

**Comment by HangingClowns** [comment]
Thanks! Can you share a gist of what you started?

**Comment by josevalim** [comment]
@HangingClowns I tried to find it before my last comment but I couldn't :(
