### ISSUE TITLE
Add billing actions to audit log

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#673]

**Comment by dsdshcym** [comment]
Hi @ericmj!

I'd like to work on this issue and I need some help from you.

-   Here is a list of all the billing actions I think we need to audit:
    
    1.  billing.checkout
    2.  billing.get (?)
    3.  billing.cancel
    4.  billing.create
    5.  billing.update
    6.  billing.change\_plan
    7.  billing.invoice (?)
    8.  billing.pay\_invoice
    9.  billing.report (?)
    
    Is it necessary to audit read actions like `get`, `invoice` and `report`?
-   Steps
    1.  Add a `audit: audit_data` param to all the functions in `Hexpm.Billing`.
    2.  We need to update existing `impl()` function calls to use `Multi` so that we can use them with `AuditLog.audit/4`. Here are a few choices:
        
        1.  Update `Hexpm.Billing.Hexpm` and `Billing.Local` functions and use `Multi` in them.
        2.  Wrap `impl()` function calls in `Multi` so that `Billing.Hexpm` and `Billing.Local` functions don't need to change.
        
        I would recommend the second choice here since it's simpler to modify one place. And we can migrate to choice 1 later if needed.
    3.  Then call `AuditLog.audit/4` in `Hexpm.Billing` functions.
    4.  Translate the return value of `Multi.run` from Tuple to the old result to keep backward compatibility

**Comment by ericmj** [comment]
Hi! Thanks for continuing the work on audit logs 💜. 

> Is it necessary to audit read actions like get, invoice and report?

No, only write actions I would say.

> Steps

These steps look good. I would say add the Multi outside of the `impl()` since this implementation shouldn't concern itself with audit logs.

**Comment by dsdshcym** [comment]
> add the Multi outside of the `impl()`

I'm not sure if I understand this correctly. This is what I have now, could you check?

```elixir
defmodule Hexpm.Billing do
  use HexpmWeb, :context
  
  # ....

  def create(params, audit: audit_data) do
    Multi.new()
    |> Multi.run(:create, fn _, _ ->
      impl().create(params)
    end)
    |> audit(audit_data, "billing.create", params)
    |> Repo.transaction()
    |> case do
      {:ok, %{create: result}} -> result
    end
  end
end
```

**Comment by ericmj** [comment]
Yeah, that looks good.

**Comment by ericmj** [comment]
All implemented. Thanks @dsdshcym!
