### ISSUE TITLE
Feature request: Version dropdown on hexdocs

### ISSUE THREAD

**Issue by michallepicki** [hexpm/hexpm#682]
I would like to be able to view available documentation versions and switch to them through a dropdown. Similar to the one on [Microsoft's .NET API documentation pages](https://docs.microsoft.com/en-gb/dotnet/api/system.collections?view=netcore-2.0) - try picking .NET Core 1.1 through the dropdown on the left.

I understand this is a dynamic thing and requires additional features in ex_doc but I think it can be done:
1. Expose a list of {version, URL_BASE} pairs for links to available docs (for each version) through a json endpoint on hexpm
2. Add an optional versions_endpoint_url config to ex_doc which, if present, would modify the generated documentation static HTMLs to include small `<script>` to handle clicking on package name/version by fetching versions from the endpoint and showing links to this page for other versions in a dropdown.
3. Differences between pages that were added / removed between versions would be handled by a dynamic 404 page for https://github.com/hexpm/hexpm/issues/618 .

People hosting their docs on their own would be able to maintain their own versions.json file.

This is a long shot but I think it's worth thinking about.

**Comment by josevalim** [comment]
@michallepicki I think this could work if we do a join work with ex_doc/hex. Basically hex will expose a "versions.json" file. ExDoc can try to access this file and, if one is available, we show the drop down.

**Comment by michallepicki** [comment]
@josevalim Yes, I was not sure whether this issue belongs to this repo or `hex` repo but I saw #618 being here and I think it's related.

**Comment by ericmj** [comment]
I believe we can't do AJAX in exdoc so how would we fetch this information? We would like to be able to hook into the search the same way.

**Comment by josevalim** [comment]
@ericmj oh, it can work with a .js file then. You will set a variable in a .js file. That's how we export information to ExDoc today too. Although you may want too have export a .json file too.

**Comment by josevalim** [comment]
@ericmj I would treat this problem separately from the search.

**Comment by michallepicki** [comment]
I'm not sure I understand why we would want to do a fetch in ex_doc at all? I don't think we need to have versions during documentation build. I think it's fine to have them pulled in js after a user clicks on the dropdown in his browser. This way we don't need to rebuild old package's docs when a new version of a package is introduced (but of course only newer or docs rebuilt after introducing this functionality would have this dropdown js code)

**Comment by josevalim** [comment]
We are not saying to have it on the documentation build. When we say ex_doc, we say the HTML+JS generated by ExDoc.

We need to add this to ExDoc, so old versions won't get this feature. The other other would be for Hex to wrap or override the documentation pages but I find that brittle and error prone and puts the work on the Hex team.

**Comment by ericmj** [comment]
@josevalim I would like to have a more general solution because any feature will need to be supported forever. I don't like a the versions.js file because if we want to add another similar feature we would add a bunch of extra requests for each page load. We already have quite a lot of page loads in exdoc.

@michallepicki They would not be fetched when documentation is built, they would be fetched on page load. We can't use AJAX because it does not work locally when serving from the filesystem.

**Comment by josevalim** [comment]
@ericmj I am not sure if you are arguing against the `.js` extension in particular or against doing a separate request in general, regardless of the extension. But to me, the `.js` approach is not really different from `.json` in terms of trade-offs. They are just different formats.

In any case, we may be fine using AJAX here. This feature is not essential to how ExDoc works and odds are that you don't have the versions file locally anyway.

**Comment by ericmj** [comment]
I am arguing against the extra request. If ex_doc instead provided a place where hexdocs could inject our own javascript that would be better because there would be no extra requests.

**Comment by michallepicki** [comment]
I'm confused about that and it looks like I don't understand how hexdocs works

**Comment by josevalim** [comment]
@ericmj i am not sure i like the idea of pre-processing pages. What happens when you release a new version? You need to go to all previous published docs and process them again?

**Comment by ericmj** [comment]
@josevalim The idea is based on the new hexdocs that is in progress where we can dynamically generate content.

**Comment by michallepicki** [comment]
After playing with this idea a bit I understand why a `.js` script is better than `.json` ajax call. With data exported through a script it should be possible to keep the dropdown working when accessed through `file://` without a http server.

Crazy idea: what about making it work only on `hexdocs` by wrapping static documentation in an iframe and adding dropdown + hexpm link + github link etc using a `hexdocs` top bar? The wrapper could be dynamiclly generated by `hexpm` (or pre-generated and cached / saved) but the documentation would stay static. And it would be possible to go from an docs version to a newer one.
