### ISSUE TITLE
`hex.publish` private package fails

### ISSUE THREAD

**Issue by fredwu** [hexpm/hexpm#692]
Hi,

We've been using the private hex repo for a while, and just now we've encountered errors for the first time.

`mix hex.publish` errors out:

```
Docs successfully generated.
View them at "doc/index.html".
Local password:
Publishing package...
[#########################] 100%
Publishing failed
Internal server error
```

After the error, we can actually see the new version on hex.pm. But the new version cannot be seen by `mix deps.update package_name` in our other projects.

Then, we tried `mix hex.publish --revert 0.6.1`:

```
Local password:
Reverting package...
Reverting package_name 0.6.1 failed
Internal server error
Reverting docs...
Page not found
Reverting docs for package_name 0.6.1 failed
```

It shows the revert also errored out, but upon executing the revert command, the new version (0.6.1 in this case) was removed from hex.pm when we view our package page.

I've also tried to delete `~/.hex/cache.ets` but that didn't help.

I got the error on both Elixir 1.6.4 (which had no problems before) and 1.6.5:

```
 ❯❯❯ mix hex.info
Hex:    0.17.7
Elixir: 1.6.5
OTP:    20.3.8

Built with: Elixir 1.6.4 and OTP 19.3
```

Is this a network issue? Anyway we could help debug this issue?

**Comment by larskrantz** [comment]
Got this error too with private package with same error messages as above.

```
> mix hex.info
Hex:    0.17.7
Elixir: 1.6.4
OTP:    20.3.1

Built with: Elixir 1.6.4 and OTP 19.3
```

**Comment by ericmj** [comment]
Thank you for the reports. The fix has been deployed to production.

**Comment by larskrantz** [comment]
Confirmed as working, thanks!
