### ISSUE TITLE
HTTP status code: 400

### ISSUE THREAD

**Issue by crownedgrouse** [hexpm/hexpm#700]
Hi,
I cannot publish a new version of a project already existing on hex.
I updated rebar3, removed _build and rebar3 cache, but no way.
Any idea ?

```
$> ./rebar3 hex publish
[...]
  Build tools: rebar3
Before publishing, please read Hex CoC: https://hex.pm/policies/codeofconduct
Proceed? ("Y")> Y
===> Status Code: HTTP status code: 400
Hex Error: Bad request
```

**Comment by crownedgrouse** [comment]
https://hex.pm/packages/jason_erl

Latest rebar3 from yesterday, sorry do not have the number right now. Writing from mobile, and computer off.

**Comment by wojtekmach** [comment]
Yes, the version string must look like SemVer.

**Comment by crownedgrouse** [comment]
Hu . A better error raising might be nice in such case than HTTP 400. Hex should even not proceed ?

**Comment by wojtekmach** [comment]
Yeah, I'm leaving this issue open to investigate the situation later today. I'm pretty sure hex.pm returns proper error in json response so it's a matter of clients like rebar3 to interpret that, but if we aren't returning proper error we will fix it here.

**Comment by crownedgrouse** [comment]
stopping before propose to publish "Y" would be better maybe.

**Comment by ericmj** [comment]
> stopping before propose to publish "Y" would be better maybe.

That would need to be added to rebar3_hex.
