### ISSUE TITLE
Change "write" permission to be read write

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#703]
I have following keys generated via UI:

<img width="742" alt="screen shot 2018-08-01 at 00 20 39" src="https://user-images.githubusercontent.com/76071/43490416-d1b8289e-9520-11e8-9190-69c64295bce5.png">

I can hit /packages/:package endpoint with 2nd key but not with the 1st key. It's kind of logical but not sure if it's practical, should write implying read permission?

**Comment by wojtekmach** [comment]
@ericmj we can close this because of https://github.com/hexpm/hexpm/pull/792, right?

**Comment by ericmj** [comment]
Yep!
