### ISSUE TITLE
Package count on index page.

### ISSUE THREAD

**Issue by nashby** [hexpm/hexpm#704]
Right now it says `7 026 packages available` and according to source code it counts private packages as well. So it's kinda false that that number of packages are available (at least not for me :p). Does it make sense to use the same logic here as we use on `https://hex.pm/packages` page? As I can see we show packages (and the count) that are accessible for current user

If that makes sense I can work on this.

**Comment by ericmj** [comment]
The idea is that it shows the packages available in the system, not for a specific a user. It would be easy to change package available on the front page but package versions and downloads would probably require schema and index changes to the releases table and download views.

We can change the numbers if we can do it for all of them without increasing page load time a lot.

**Comment by nashby** [comment]
@ericmj oh, I see. After thinking about it again I guess it makes sense to show stats for whole system on the front page. So closing it. Thanks for the quick response!
