### ISSUE TITLE
Packages search results sorting UI improvement.

### ISSUE THREAD

**Issue by nashby** [hexpm/hexpm#709]
I suggest following changes: 

OLD: 
![](https://i.gyazo.com/4a169ea2d8e80c28bfd71523b5b603a5.png)

NEW: 
![](https://i.gyazo.com/2da8fed96f7c03cbeeff1e15b3a53c77.png)

I think this way it's more readable which sorting is applied right now. The reason why I think it's better is because I couldn't find which sorting is applied when I was using hex.pm. I think showing currently applied sorting in the element where you change it is more convenient. If that sounds good to you I can work on PR.

**Comment by ericmj** [comment]
Looks great, please go ahead and send a PR.
