### ISSUE TITLE
Docs from our Private Package are published openly online with access to source code

### ISSUE THREAD

**Issue by dokie** [hexpm/hexpm#739]
We have a private organizational package [here](https://hex.pm/packages/inflowmatix/inflownet_core) and we have found via Google search the docs from an older version [here](https://hexdocs.pm/inflownet_core/api-reference.html) which allows click through to our GitHub repo and source code. How can we get this removed please?

**Comment by ericmj** [comment]
Please email support@hex.pm from an email associated with hex account belonging to your organization and we can remove the content.

**Comment by dokie** [comment]
OK -  done thanks - sorry for raising it as an issue. Please delete accordingly!
