### ISSUE TITLE
Sort by dependents count

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#747]
Another way to gauge packages relative popularity. Although if we do this we should display dependents count on package index too. Thoughts?

TODO:
- [ ] Sort on website
- [ ] Sort on `/packages` API endpoint

**Comment by ericmj** [comment]
👍 

> Although if we do this we should display dependents count on package index too.

Yeah, we can change the column we use for downloads to display the count when you sort by it. It seems we already change between this when sorting by recent/total but not when sorting by dates 🤔

**Comment by lccezinha** [comment]
Hey @wojtekmach and @ericmj still this feature relevant? If yes, I would like to try it.

Any advice or suggestion of how to solve it?

**Comment by wojtekmach** [comment]
@lccezinha we have a package_dependants materialised view from which we can grab the count of dependants. And yes, a PR would be very welcome, let us know if you run into any issues!

**Comment by lccezinha** [comment]
@wojtekmach Thanks for your response. I'll take some time to look at the project I'm new in Phoenix framework but I'll try it!

**Comment by lccezinha** [comment]
@wojtekmach I'm not familiar with materialized views an how to use them inside the ecto query flow. Is there an example inside the code that does something similar?

**Comment by wojtekmach** [comment]
Hey Luiz, the beauty of materialised views is that they're treated as any other tables (they’re kind of like read-only tables), so we can use regular joins, associations etc in Ecto queries.
