### ISSUE TITLE
"Download" online documentation link goes straight to CDN

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#750]
![screenshot 2018-11-11 at 06 41 46](https://user-images.githubusercontent.com/76071/48309552-158c7780-e57d-11e8-8626-f2c05b26388d.png)

I believe previously it went to: https://repo.hex.pm/docs/decimal-1.5.0.tar.gz

@ericmj please close if this was on purpose, I don't think it's necessarily bad, just double-checking. For `mix hex.docs offline` we use the `https://repo.hex.pm/docs/...` one.

**Comment by supersimple** [comment]
@ericmj @wojtekmach this seems to have already been fixed.

**Comment by wojtekmach** [comment]
Yup, thanks!
