### ISSUE TITLE
Store and display publisher of package version

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#753]
Currently the published of a package is only stored in the audit log which is internal only.

1. [x] Store user who published release in database
2. [x] Show publisher on the website's package page
3. [x] Add to release API endpoint
4. [x] Add to `mix hex.info PACKAGE VERSION`
5. [x] Backfill release publishers from audit log

**Comment by edmz** [comment]
(I assume this is because of the event-stream fiasco, if not the please ignore.)

Could there be a way to notify the users of a package that a publisher has changed? Maybe when doing `mix deps.get` a package could be highlighted as one where the publisher has recently changed?

**Comment by ericmj** [comment]
We have been discussing that but the current thinking is that noise to value ratio will be too high.

**Comment by ericmj** [comment]
@pedroassumpcao I think it's enough to be able to search by owner for now so I would skip searching by publisher for now until we discover there is a need for it.

**Comment by dsdshcym** [comment]
Hi, @ericmj !

I want to work on this issue. Here is what I'm planning to do to "Store user who published release in database":

I assume there is only one `publisher` for every release, so I choose to add `belongs_to :publisher, User` relationship to `Release` schema. Please correct me if this assumption is wrong.

Here are my plans with some questions:
1.  Add `release_publishers` table (We write SQL directly in migration files, right?)
2.  Add `belongs_to :publisher` relationship to `Repository.Release` schema (`belongs_to` or `has_many`?)
3.  Add a test case for `Releases.publish/7` to assert that it will set `user` as `release.publisher`. Change `Releases.create_release/4` to `Releases.create_release/5` and modify `Release.build/3` to make the test pass
4.  Add `validate_required :publisher_id` to `changeset(release, :update, params, package, checksum)`

Please let me know your thoughts and if I can start working on this. Thanks!

**Comment by ericmj** [comment]
We can have a direct relation between `User` and `Release` with the `belongs_to :publisher, User` association on `Release` so we don't know need a `release_publishers` table. Everything else sounds good. 👍

**Comment by dsdshcym** [comment]
Cool! I'll just add `publisher_id` to `releases` table then.

It's 11pm now and I'm going to take some rest. I'll start working on this tomorrow and submit the PR ASAP. 

Thanks for the quick reply!

**Comment by dsdshcym** [comment]
There's only "Show publisher on the website's package page" left unfinished now.

Here's my rough plan for adding this info:
1. preload publisher in `PackageController.package/6` for release  https://github.com/hexpm/hexpm/blob/8aaab173abf33aef786d2f0ad2eae59844f9afbc/lib/hexpm_web/controllers/package_controller.ex#L88
2. add a publisher section (use the same design as owners) to show.html.eex  https://github.com/hexpm/hexpm/blob/8aaab173abf33aef786d2f0ad2eae59844f9afbc/lib/hexpm_web/templates/package/show.html.eex#L204
3. extract a partial for rendering owner/publisher to remove the duplications

**Comment by ericmj** [comment]
I think we can close this now? Confirm /cc @dsdshcym @wojtekmach

**Comment by wojtekmach** [comment]
I think we have all the pieces, thanks @dsdshcym and let us know if you think anything else should be changed here!

**Comment by dsdshcym** [comment]
@ericmj @wojtekmach I think this feature is good now. When would it be deployed? I still can't see publishers for package releases on hex.pm.

And thanks a lot for your guidance during the development of this feature. 🙏

**Comment by ericmj** [comment]
Thank you @dsdshcym. It's going to be deployed today if we don't run into any issues.
