### ISSUE TITLE
Document how to use private packages and organizations from rebar3

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#758]
Move this page https://hex.pm/docs/private to the Mix docs and write the equivalent docs for rebar3.

**Comment by supersimple** [comment]
@ericmj is there someplace to get the details of rebar3 usage from?

**Comment by tsloughter** [comment]
Part of it is here https://www.rebar3.org/docs/configuration#section-hex-repos-and-indexes

I'll have to update it to mention organizations.
