### ISSUE TITLE
Request: Make repo database SSL optional

### ISSUE THREAD

**Issue by mroach** [hexpm/hexpm#764]
`prod.exs` has database SSL hardcoded to `true`

```elixir
config :hexpm, Hexpm.RepoBase, ssl: true
```

It would be ideal for this to be optionally controlled via the environment like the rest of database configuration so it can be switched off when running a private instance of hexpm.

Or, perhaps modify `init` in `repo.ex` to automatically turn it off when there is no SSL configuration provided?

**Comment by ericmj** [comment]
> Or, perhaps modify init in repo.ex to automatically turn it off when there is no SSL configuration provided?

This sounds best for us, but I believe connecting to some postgres databases over SSL does not require any additional SSL config. If I recall correctly this is the case for Heroku's postgres offering.

**Comment by mroach** [comment]
I just realised the Ecto database URL supports overriding this with `?ssl=false`. So this is less of an issue then. Maybe this is now a non-issue?
