### ISSUE TITLE
Minimal Theming support for published docs

### ISSUE THREAD

**Issue by Serkan-devel** [hexpm/hexpm#765]
As explained on another closed issue, 
Is it possible to change the theme of docs, published to the hexdocs.pm-page?

I think ReadTheDocs already has minimal support for theming on their site

**Comment by ericmj** [comment]
hexdocs.pm only hosts docs that users upload, the users are in full control of the html and themes of the docs that they upload. If you want to change the theme of elixir docs you should check out the ex_doc project [1] which is the main documentation generator for elixir projects.

[1] https://github.com/elixir-lang/ex_doc

**Comment by Serkan-devel** [comment]
Actually one would need to modify ex_doc directly, which would be a little impractical when updating.

Could there be a setting on a project's `mix.exs` to just simply install a theme as a package and link to it?

```elixir
  def project do
    [
      ...
      docs: [
        logo: "priv/static/static/logo.png",
        extras: ["README.md", "docs/config.md", "docs/intro.md"],
        main: "readme",
        output: "priv/static/doc"
        theme: "solarized-dark"
      ]
     ...
    ]
  end
...


  defp deps do
    [
     ...
      {:ex_doc, "~> 0.19", only: :dev, runtime: false},
      {:ex_solarized_doc, "~> 0.1"}
     ...
    ]
  end
```

**Comment by ericmj** [comment]
I don't believe ex_doc have those kind of extension points but it would be best to discuss that on the ex_doc project since it's not relevant to Hex.

**Comment by Serkan-devel** [comment]
oh
