### ISSUE TITLE
Change Most Downloaded on homepage to use recently downloaded

### ISSUE THREAD

**Issue by supersimple** [hexpm/hexpm#766]
In order to make the results more interesting and relevant, change the list of Most Downloaded to the most downloaded in the last 90 days.

**Comment by thiamsantos** [comment]
Hi @supersimple,

I would like to work on this issue.

So far I thought on change the query that load the top package downloads to do something like this:

```sql
SELECT p0.id, p0.name, p0.inserted_at, p0.meta, sum(d0.downloads) AS downloads
	FROM downloads AS d0 
	INNER JOIN releases AS r0 ON r0.id = d0.release_id 
	INNER JOIN packages AS p0 ON p0.id = r0.package_id
	WHERE d0.day > CURRENT_DATE - INTERVAL '90' DAY
	GROUP BY p0.id
	ORDER BY downloads DESC
	LIMIT 8;
```

I was worried about perfomance on this case, there is some materialized view or some table, I don't know, that I could use to store this data, without having to make the query every time the page is loaded?

What are your thoughts about that?

**Comment by supersimple** [comment]
@thiamsantos 
Thank you.
There is some existing code that does something similar to this now. If you look at: https://hex.pm/packages
you can see the number of recent downloads.

That data is actually stored in a materialized view (IIRC).

You can see some part of that logic here: https://github.com/hexpm/hexpm/blob/master/lib/hexpm/repository/package.ex#L374

I hope that helps. Let me/us know if you have any other questions.

**Comment by thiamsantos** [comment]
@supersimple so this `"recent"` downloads are the numbers from the last 90 days?

**Comment by supersimple** [comment]
In the package_downloads materialized view there is a "view" column. The "recent" view records represent the last 90 days.

**Comment by thiamsantos** [comment]
@supersimple I see, thanks for the help!

**Comment by ericmj** [comment]
Closed in favor of PR: https://github.com/hexpm/hexpm/pull/775.
