### ISSUE TITLE
Add config.js for version dropdown on HexDocs

### ISSUE THREAD

**Issue by josevalim** [hexpm/hexpm#795]
Recent ExDoc versions allow a version dropdown to be shown by adding a `docs_config.js`. Now it is the job of HexDocs to generate said `docs_config.js` file.

The `docs_config.js` should be placed in the same directory as the documentation with all available versions. However, this is a bit problematic because, if we generate the `docs_config.js` when the docs are published, then it will only list the versions available at the time of publishing. Unless we change all existing docs_config.js for all versions whenever a new version is published.

To address this, I suggest to place two docs_config.js file, one at the root of the package and one for each package/version. For example, for Ecto, we would have:

    * hexdocs.pm/ecto/config.js
    * hexdocs.pm/ecto/3.0.0/config.js

The second `docs_config.js` will always redirect to the first one. If we are using S3, [it can be done as mentioned here](https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html). The "root" `docs_config.js` will be generated whenever there a new version is published. Here are the changes necessary:

  1. Whenever new documentation is published, we will check if a `docs_config.js` exists and, if not, we will configure the PROJECT/VERSION/docs_config.js to redirect to PROJECT/docs_config.js

  2. Whenever new documentation is published, we will push a PROJECT/docs_config.js with all version nodes for PROJECT

Here is how the docs_config.js can look like:

```js
  var versionNodes = [
    {
      version: "v0.0.0", // version number or name (required)
      url: "https://hexdocs.pm/ex_doc/0.19.3/" // documentation URL (required)
    }
  ]
```

The versionNodes value can be generated by hand or with a JSON lib. We can optionally include a link to the "Hex Package" itself, as the last entry in the versions list.

If someone from the Hex team can provide guidance where those changes happen, it may help with external contributors. :)

**Comment by wojtekmach** [comment]
Picking it up!

**Comment by michallepicki** [comment]
@wojtekmach 's PR: https://github.com/hexpm/hexdocs/pull/9
Related issue: https://github.com/hexpm/bob/issues/30

**Comment by wojtekmach** [comment]
I think we can close this since remaining things are tracked elsewhere. Thanks everyone for helping with this!
