### ISSUE TITLE
Elixir kernel documentation of ceil/1 guard incorrect

### ISSUE THREAD

**Issue by 7hwrd** [hexpm/hexpm#804]
The description of ceil/1 is incorrect. It currently is “Returns the smallest integer not greater than number.”.

It should be “Returns the smallest integer not *less* than number.”.

See https://hexdocs.pm/elixir/Kernel.html#ceil/1 also see the identical text in the guard function list.

**Comment by wojtekmach** [comment]
Thanks for the report! This is already fixed on Elixir master, see: https://hexdocs.pm/elixir/master/Kernel.html#ceil/1.

Btw, the hexpm repository is responsible for working with packages and hosting package docs but if the docs are wrong it should be reported on that package's issue tracker not here.
