### ISSUE TITLE
Can't sort by "Recently updated"

### ISSUE THREAD

**Issue by rodrigues** [hexpm/hexpm#806]
Hello, I think I've found a bug:

https://hex.pm/packages?page=1&sort=updated_at

The first result I get is https://hex.pm/packages/xml_builder, but this package was last updated in Nov 2018.

**Comment by ericmj** [comment]
It sorts by changes to the package, not when it was last published. Changes can include metadata changes, package ownership changes, etc.

**Comment by rodrigues** [comment]
oh, ok, then Recently published is what I was looking for, right?

Thanks!
