### ISSUE TITLE
docs to explain earlier what is going on

### ISSUE THREAD

**Issue by mfrasca** [hexpm/hexpm#814]
(I come from Python, I have a formal education on functional languages, but hardly used it.)

in the documentation, first two pages, that is between up-and-running and adding-pages, I have the impression I don't exactly follow.  unlike a very beginner's tutorial like djangogirls, this https://hexdocs.pm/phoenix/adding_pages.html seems to be afraid to show errors.  I would like that before we are led to add a new page, we checked what happens when I request the non-existing `hello` page/route/view/... and add the pieces step by step, showing what is still missing.

related to this: after executing `mix phx.new hello`, which files should I add to my (not even that) hypothetical git repository?

**Comment by wojtekmach** [comment]
Hi! Hex is concerned with hosting packages and docs, but not with the contents themselves. The source of the page you're referencing is here: https://github.com/phoenixframework/phoenix/blob/master/guides/adding_pages.md so if you'd like to re-open the issue please do it on that repository.

> related to this: after executing mix phx.new hello, which files should I add to my (not even that) hypothetical git repository?

`mix phx.new` generates a `.gitignore` file with good defaults so it's OK to add all generated files to your git repo.
