### ISSUE TITLE
Select username field when the "Log In" page is loaded

### ISSUE THREAD

**Issue by whatyouhide** [hexpm/hexpm#823]
Nitpick: when I go to hex.pm and click "Log In", I get to the login page but the username field is not selected. This means that I open 1password with my shortcut and fill the website in but it's not filled in, so I have to go in there with a mouse and click the username field. I think generally in login pages the username field is selected. Thoughts? Is this dumb? 💟

**Comment by ericmj** [comment]
Makes perfect sense. This seems to be a common pattern with tools like 1password so hex.pm should support it.

**Comment by supersimple** [comment]
@whatyouhide PR #828 fixes this. Thanks for the issue 🌲
