### ISSUE TITLE
Text field for number of organization seats doesn't adapt

### ISSUE THREAD

**Issue by whatyouhide** [hexpm/hexpm#824]
If I want to add `n` organization seats, the text box is fine if `n` is only one digit, but doesn't grow to adapt to more digits. In the screenshot, I was adding "12" seats and as you can see only the "2" is shown.

<img width="217" alt="Screen Shot 2019-06-24 at 4 00 25 PM" src="https://user-images.githubusercontent.com/3890250/60025097-3d0dfb80-9699-11e9-8108-2311d0f3bb45.png">

**Comment by supersimple** [comment]
@whatyouhide PR #827 fixes this.
