### ISSUE TITLE
Add support for text/plain emails

### ISSUE THREAD

**Issue by ankhers** [hexpm/hexpm#841]
Currently hex.pm only send emails in text/html. I would like to add support for text/plain.

The general outline of what I would like to do can be found in [this gist](https://gist.github.com/ankhers/a5ff718b28db9ad0d2b5fad9adfbd4d6).

**Comment by liskin** [comment]
Actually it does send the text/plain part as well, but it's empty, which is all the more confusing as classic e-mail readers simply display an empty message.

**Comment by ankhers** [comment]
Right. This is actually what lead me to make this issue and #843. Because my email client showed an empty message, which was initially confusing.
