### ISSUE TITLE
HTML not encoded

### ISSUE THREAD

**Issue by stevecw** [hexpm/hexpm#842]
Simple issue.
In the left menu bar, under Deployment > Deploying with Releases for Phoenix 1.4.9 HexDocs, you have some unencoded HTML appearing (refer to screenshot).

Thanks
![hex_doc](https://user-images.githubusercontent.com/26632419/63034911-079eb680-be6f-11e9-9201-dc802158bebb.png)

**Comment by ericmj** [comment]
Please report this issue to either https://github.com/phoenixframework/phoenix from which the documentation is or https://github.com/elixir-lang/ex_doc which generated the documentation.
