### ISSUE TITLE
"Dependents" section seems to not take organization namespaces into account

### ISSUE THREAD

**Issue by fertapric** [hexpm/hexpm#850]
If a public/private package of an organization uses the same name than a public "global" package, the "Dependents" section shows the dependents of the latter.

This is quite a surprise for private packages :)

**Comment by ericmj** [comment]
We need to change the materialized view https://github.com/hexpm/hexpm/blob/master/priv/repo/migrations/20170613205641_add_package_dependants_view.exs to include both package name and repository name. 

We also need to change the `depends:package` search query to support a repository with `depends:acme/package` https://github.com/hexpm/hexpm/blob/master/lib/hexpm/repository/package.ex#L263.

Up for grabs if anyone wishes to contribute!
