### ISSUE TITLE
Add 2FA to website and API

### ISSUE THREAD

**Issue by supersimple** [hexpm/hexpm#852]
In the interest of user security, we would like to add 2 factor authentication to the API and Website. This should be handled in phases or steps (both for productivity and because the CLI will need work done on it when the API changes.)

This is a list of identified stages (there could be others yet discovered)
## Website

- [x] Add an auth_secret to the User (stored in database, and added to the schema)
- [x] Add a way to generate QR Codes for registering with Google Authenticator (initial implementation)
- [x] Add a page to display the generated QR code for Authenticator
- [x] Add a way to verify Google Auth codes
- [x] Add page to activate/deactivate 2FA from user account settings page
- [x] Add page as part of login process that expects 2FA code before successfully authenticating (this will be another gateway after the login page)
- [x] Recovery codes - making sure each code can be used only once, ability to generate new codes. See: https://github.com/settings/auth/recovery-codes
- [x] Verify auth app code before activating 2FA in setup.

## API
- [ ] Modify authentication flow to ask for 2FA code if user has it activated.

Please comment on this issue with steps that are unclear or missing

**Comment by wojtekmach** [comment]
We should also add "Recovery Codes", we can mimic how GitHub handles them: https://github.com/settings/auth/recovery-codes.

**Comment by supersimple** [comment]
@wojtekmach yes, this may or may not be required for the first iteration. Can you deconstruct that into actionable items and add it to the issue description?

**Comment by wojtekmach** [comment]
Sure. And agreed, we may not necessarily need it for v1.

**Comment by starbelly** [comment]
Task 3, Task 6, and most of 7 are complete (sans the ability generate new codes once one is used or the ability to generate a new set). 

  One thing that needs to be revisited is the enabling of 2fa. Currently, the user checks enable tfa and clicks save, the setting, totp secret, and recovery codes are persisted, then they are shown the QR code, etc. This was for an MVP and to make it work. 

 How it should be IMO is that the: 

 - user checks enable tfa, clicks "setup" vs save
 -  a totp secret is generated and stored in the session
 - the user is then presented with a QR code
 - user scans code
 - user enters otp code to verify setup and clicks submit
 - if the otp code is valid then we save the secret and generate codes etc. 

 This prevents the user from mistakenly locking themselves out.

**Comment by supersimple** [comment]
@starbelly @jeffreyplusplus @wojtekmach @ericmj https://github.com/hexpm/hexpm/pull/851 should have all of the MVP features. If any of you have time to test it out, i would appreciate it.

**Comment by starbelly** [comment]
@supersimple I'm on it...
