### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by andyl** [hexpm/hexpm#854]
There was discussion of RSS feeds at one point (#19, #29) but it looks like the current version of HexPM has no RSS feeds.  Is that right?

If so I'm curious:
- why was RSS support dropped?
- would people be interested in a PR to reinstate RSS feeds?

**Comment by supersimple** [comment]
Hi @andyl - Neither Wojtek or I have any knowledge of why it does not current exist, however, there is an XML feed that might be useful in lieu of the lack of RSS: https://hex.pm/sitemap.xml
Also, I think the best way to subscribe to a list of package changes would be programmatically through [hex_core](https://github.com/hexpm/hex_core)

**Comment by andyl** [comment]
@supersimple thanks for your response I'll check out the API.
