### ISSUE TITLE
audit_log.organization_id may not be set sometimes

### ISSUE THREAD

**Issue by dsdshcym** [hexpm/hexpm#864]
Hi there!

I found this issue when I was working on #673:

We have three `AuditLog.build/4` function handlers. Each one of them sets `audit_log.organization_id`. But except the one that accepts an `Organization`, the other two's `organization_id` are always `nil`.

1. https://github.com/hexpm/hexpm/blob/dcbac282f083ece76e08619116fbcbee3386a653/lib/hexpm/accounts/audit_log.ex#L15-L26

   In this case, `extract_params` for `password.reset.init` and `password.reset.finish` all returns `%{}`

2. https://github.com/hexpm/hexpm/blob/dcbac282f083ece76e08619116fbcbee3386a653/lib/hexpm/accounts/audit_log.ex#L28-L38

   In this case, `extract_params` calls `serialize`, but `serialize` doesn't fetch `:repository` for any schema

I think we have several ways to fix this issue (if we need to fix it):

1. set `organization_id` to `nil` explicitly if it's the expected result
2. fix `extract_params` to also extract `organization_id`
3. use `params[:organization][:id]` rather than `params[:repository][:organization_id]`

Let me know what you think

**Comment by ericmj** [comment]
In the case of `password.reset.init` and `password.reset.finish` we shouldn't set an `organization_id` since organizations doesn't have passwords.

> use params[:organization][:id] rather than params[:repository][:organization_id]

I don't think we always have `params[:organization][:id]` set when working with packages for example. Because of this I think 2. is the best solution, and lets do 1. for the password logs.

Does this sound good to you?

**Comment by dsdshcym** [comment]
Sounds good!

I've submitted #868 for password related changes.

I'll do 2 later.

Thank you for your advice!

**Comment by dsdshcym** [comment]
Hi @ericmj!

If #872 gets merged, the following actions will get `organization_id` recorded:
- docs.publish
- docs.revert
- owner.add
- owner.transfer
- owner.remove
- release.publish
- release.revert
- release.retire
- release.unretire
- organization.member.add
- organization.member.remove
- organization.member.role
- billing.checkout
- billing.cancel
- billing.create
- billing.update
- billing.change_plan
- billing.pay_invoice

And for these actions, `organization_id` would still be `nil`, (since we don't extract `organization` or `package` for these actions in `extract_params`)
- key.generate
- key.remove
- email.add
- email.remove
- email.primary
- email.public
- email.gravatar
- user.create
- user.update
- organization.create
- password.reset.init
- password.reset.finish
- password.update

I think we should still set `organization_id` for `organization.create`, but I'm not sure the best way to do it. Because in extract_params, we just return the serialized `organization`.

https://github.com/hexpm/hexpm/blob/19b2071e5102cd11eae6b06181fd47c1e2a4f08a/lib/hexpm/accounts/audit_log.ex#L130

My first guess is to add an `audit_log_organization_id` to the return value of `extract_params`:

```elixir
  defp extract_params("organization.create", organization), do: 
    Map.put_new(serialize(organization), :audit_log_organization_id, organization.id)
  end

  def build(%User{id: user_id}, user_agent, action, params) do
    params = extract_params(action, params)

    %AuditLog{
      user_id: user_id,
      organization_id: params[:organization][:id] || params[:package][:organization_id] || params[:audit_log_organization_id],
      user_agent: user_agent,
      action: action,
      params: params
    }
  end
```

But adding a field just for one action seems to be too much? What do you think?

**Comment by ericmj** [comment]
> My first guess is to add an audit_log_organization_id to the return value of extract_params

Another option is to special case `organization.create` in the `build` function like we do for `password.reset.*`? Your solution also looks good, pick which you think is best.

**Comment by ericmj** [comment]
Thank you for discovering and fixing this!
