### ISSUE TITLE
Describe math in HexDocs

### ISSUE THREAD

**Issue by zacky1972** [hexpm/hexpm#865]
I'm developing Numexy, which is a math library for Elixir.

I'd like to describe mathematical expressions in HexDocs because to understand the program code requires to understand the numerical theory of it using them.

Can I describe them in HexDocs?

If not, I propose to make the notation of them follow Jupiter Notebook: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

**Comment by wojtekmach** [comment]
Hi, this is a very interesting feature! However, because hexpm is only concerned with hosting packages and their docs but not their contents, I’m gonna go ahead and close this. Could you send a proposal to elixir-lang/ex_doc instead?

**Comment by zacky1972** [comment]
OK, I see!
