### ISSUE TITLE
Add a way to update the organization avatar

### ISSUE THREAD

**Issue by elbrujohalcon** [hexpm/hexpm#870]
I just created this org: http://hex.pm/orgs/nextroll
I want it to have a nice _profile picture_, like this one: http://hex.pm/orgs/inaka
But there is currently no way to change that image.

**Comment by ericmj** [comment]
We should make this "Public profile" view available for organizations as well:

<img width="1015" alt="Screen Shot 2019-11-11 at 18 47 45" src="https://user-images.githubusercontent.com/316890/68608737-e7a18200-04b3-11ea-9e29-b2cbb38cd94c.png">

**Comment by dsdshcym** [comment]
Hi @ericmj!
I'd like to take a try on this issue.

I think it's not trivial nor user-friendly to add a profile item for each organizations in the sidebar.

My plan is to add a profile section in `OrganizationController#show` page. And show a similar form as the form in `ProfileController#index` page.

Something like this:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4723751/70049996-e96cea00-1608-11ea-8c87-b4facb19041b.png">

 What do you think?

**Comment by dsdshcym** [comment]
After a quick investigation, I find three todoes to make updating organization profile work:

1.  remove `organization_error` calls in `Users.update_profile/3`
2.  add an `OrganizationController#update_profile` endpoint to
    1.  check if current\_user has write permission
    2.  update organization.user profile info (I'm not sure if fields that has a question mark are needed)
        -   public email?
        -   gravatar email
        -   handles
            -   twitter
            -   github
            -   elixirforum
            -   freenode?
            -   slack?
    3.  redirect to `OrganizationController#show` page
3.  add a profile form section in `OrganizationController#show` page

**Comment by dsdshcym** [comment]
After a quick investigation, I find three todoes to make updating organization profile work:

1.  remove `organization_error` calls in `Users.update_profile/3`
2.  add an `OrganizationController#update_profile` endpoint to
    1.  check if current\_user has write permission
    2.  update organization.user profile info (I'm not sure if fields that has a question mark are needed)
        -   public email?
        -   gravatar email
        -   handles
            -   twitter
            -   github
            -   elixirforum
            -   freenode?
            -   slack?
    3.  redirect to `OrganizationController#show` page
3.  add a profile form section in `OrganizationController#show` page

**Comment by ericmj** [comment]
> What do you think?

Looks good 👍 

> check if current_user has write permission

Only admin should be able to change profile data.

> I'm not sure if fields that has a question mark are needed

I think they are all useful except maybe elixirforum handle.

> add a profile form section in OrganizationController#show page

You may want to extract `templates/dashboard/profile/index.html.eex` to a shared template like `templates/dashboard/_keys.html.eex`.

**Comment by dsdshcym** [comment]
What about full name? Can admin update it too?

**Comment by ericmj** [comment]
Yes, but we should change it to "Display name".

**Comment by wojtekmach** [comment]
> > I'm not sure if fields that has a question mark are needed

> I think they are all useful except maybe elixirforum handle.

I'd keep this one, there's e.g.: https://elixirforum.com/u/plataformatec

**Comment by dsdshcym** [comment]
Before allowing admin to update organization profile, we need to allow admin to add organization email first.
So I opened #876 to add this feature first.
After it's done, @elbrujohalcon can add gravatar email for his organization thus change the gravatar.

The profile section we discussed above can be added after.

**Comment by dsdshcym** [comment]
As @ericmj pointed out in https://github.com/hexpm/hexpm/pull/876#issuecomment-563272998, we can use free text fields for adding/updating public/gravatar emails for organization users, and these emails don't need to be verified.

Due to these behavioral changes, I think we need to update some apis in `Users` module:
1. We can reuse `Users.update_profile/3`, but still need to separate organization user and normal user.
2. We cannot continue using `public_email_multi` or `gravatar_email_multi` in `update_profile/3` for organization user because these two functions only set public/gravatar flags for existing emails. And we need a way to accept an `email` string and set it as the public/gravatar email.
3. We need to add some changeset API to `Email` module as well

So my proposed solution is like this:
- `Users` module
  ```elixir
  def create_or_update_email_multi(multi, user, flag, email_address, audit: audit_data) do
    if old_email = Enum.find(user.emails, &Map.get(&1, flag)) do
      update_email_op = String.to_atom("update_#{flag}")
  
      multi
      |> Multi.update(update_email_op, Email.update_email(old_email, email_address))
      |> audit(audit_data, "email.#{flag}", fn data ->
        # get new_email from multi data
        # ...
        {old_email, new_email}
      end)
    else
      # ...
      # create new email
      # ...
  
      multi
      |> Multi.create(
        create_email_op,
        Email.changeset(
          build_assoc(user, :emails),
          :create_for_org,
          %{email: email_address, flag: flag},
          false
        )
      )
      |> audit(audit_data, "email.add", fn data ->
        # get new_email from multi data
        # ...
        email
      end)
      |> audit(audit_data, "email.#{flag}", fn data ->
        # get new_email from multi data
        # ...
        {nil, new_email}
      end)
    end
  end
  
  def update_profile(%User{organization_id: id} = user, _params, _opts) when not is_nil(id) do
    multi =
      Multi.new()
      |> Multi.update(:user, User.update_profile(user, params))
      |> audit(audit_data, "user.update", fn %{user: user} -> user end)
      |> create_or_update_email_multi(user, :public, %{"email" => params["public_email"]},
        audit: audit_data
      )
      |> create_or_update_email_multi(user, :gravatar, %{"email" => params["public_email"]},
        audit: audit_data
      )
  
    case Repo.transaction(multi) do
      {:ok, %{user: user}} ->
        {:ok, user}
  
      {:error, :public_email, _, _} ->
        {:error,
         %Ecto.Changeset{data: user, errors: [public_email: {"unknown error", []}], valid?: false}}
  
      {:error, :gravatar_email, _, _} ->
        {:error,
         %Ecto.Changeset{
           data: user,
           errors: [gravatar_email: {"unknown error", []}],
           valid?: false
         }}
    end
  end
  ```
- `Email` module
  ```elixir
    def changeset(email, :create_for_org, params, false) do
      cast(email, params, ~w(email)a)
      |> validate_required(~w(email)a)
      |> update_change(:email, &String.downcase/1)
      |> validate_format(:email, @email_regex)
      |> unique_constraint(:email, name: "emails_email_key")
      |> unique_constraint(:email, name: "emails_email_user_key")
      |> put_change(:verified, false)
    end
    
    def update_email(email, new_address) do
      change(email, %{email: new_address})
    end
  ```

Let me know if it looks good to you and I'll open a PR then

**Comment by ericmj** [comment]
That looks good. 👍
