### ISSUE TITLE
Orphan link

### ISSUE THREAD

**Issue by juise** [hexpm/hexpm#884]
At https://hexdocs.pm/logger/Logger.html there is the link:

> Check the implementation for Logger.Backends.Console[https://hexdocs.pm/logger/Logger.Backends.Console.html], for examples on how to handle the recommendations in this section and how to process the existing options.

which is an orphan...

**Comment by ericmj** [comment]
Please report this issue to https://github.com/elixir-lang/elixir that maintains the logger docs or to https://github.com/elixir-lang/ex_doc that generates the docs because that link should not be generated in the first place.
