### ISSUE TITLE
Verify package contents against source control

### ISSUE THREAD

**Issue by zachdaniel** [hexpm/hexpm#895]
Could we potentially leverage the ability to link packages to a source repo by confirming that the changes in the released package match with source control? We could also potentially leverage the new diff feature to accomplish this, as we could actually pinpoint the range of commits (maybe/theoretically) that back a package release. We could make this an opt-in feature for packages, as there are definitely use cases for not linking back to source control or the package having contents that don't exist in source control. 

Having a way to limit/prevent package hijacking by confirming their contents against source control could really limit the surface area for vulnerabilities coming from compromised dependencies.

**Comment by zachdaniel** [comment]
I think a potential way to do it would be to make it an opt-in feature, whereby you can say something like `mix hex.publish --verify`, and if you do that it will expect that the same ref you are currently on in git also exists in the remote (and that the remote is publicly available). I can think of two potential options from there:

1.) Verification is all or nothing, and if the checksum of each file does not match the checksum of the file in the remote at that sha, the publish is rejected and they don't get a little verified checkmark in their hex.pm page.

2.) Verification is on a file by file basis, and `mix hex.publish --verify` will just report the number or percentage of files that can be found to be matching in source control, and perhaps list the ones that are not.

In both cases, we could link back to that verified sha in source control. Naturally, it would only support a subset of version control systems. A few features could be added on top of this, for instance being able to say `verified: true` in your `mix.exs` to tell it never to download an unverified version of that package.

There may be problems with this approach, specifically that git history is mutable, so they could *remove* the commit, and thus "verified" doesn't necessarily point to anything useful. Either way, it does prove that, at least at the time of publishing, that the code in the package matched with a specific sha in version control. Perhaps there are security concerns I'm not considering here, more than happy to have this proposal ripped apart by someone with more experience in these matters.

**Comment by ericmj** [comment]
> I think a potential way to do it would be to make it an opt-in feature, whereby you can say something like mix hex.publish --verify, and if you do that it will expect that the same ref you are currently on in git also exists in the remote (and that the remote is publicly available).

Making it opt-in or opt-out is not a major concern right now. That is something we can decide when we know how it will work and know how it will impact users and packages.

> There may be problems with this approach, specifically that git history is mutable, so they could remove the commit, and thus "verified" doesn't necessarily point to anything useful. Either way, it does prove that, at least at the time of publishing, that the code in the package matched with a specific sha in version control.

Checking at the time of publishing can be useful for the person publishing to help them verify they are doing things correctly. But this needs to be something that can be continuously checked, for example it can be integrated in the `mix hex.audit` task so that users can verify themselves that the package matches source control. A service can continuously can fairly cheaply check that the checksum of a given tag does not change. Client side checks and this service should help mitigate history being mutable.

I think the next step right now is to implement a service that makes these checks when packages published. This can be done with existing APIs we provide: https://github.com/hexpm/specifications/blob/master/registry-v2.md.

**Comment by zachdaniel** [comment]
Yeah I see what you're saying. I was thinking that verifying continuously would have strange implications, but if we're using the checksum + tags then I think it works out nicely. 

So perhaps if the package is configured with `verify: true` (or maybe something more expressive, can figure that out later), then we look for a tag in github, compare the files against source control, and store the mapping of package checksums to the tag checksum. 

My only concern: What kind of use cases exist that could involve having files in the package that don't exist in source control or don't line up with source control? If there are compelling use cases for that, then we might not want to make "source code verification" a package level concept, but rather a file level concept.

**Comment by ferd** [comment]
Just as a data point, because hex is stricter about format and file requirements (i.e. maintainers field deprecated) than GitHub (allows anything), I actually tend to publish to hex before I tag my git repo, and then push it to be public.

**Comment by supersimple** [comment]
> I think the next step right now is to implement a service that makes these checks when packages published. This can be done with existing APIs we provide: https://github.com/hexpm/specifications/blob/master/registry-v2.md.

I dont think Hex will ever expect any VCS to be in parity, or be relied on for that. The paradox we are in is that many users look to github for readme or sample code (and many packages provide that link, which we show on the hexpm website.)

I think making a service like Johanna did with diff is a good start. Perhaps we can find a good way to incorporate that (badge on the GH side, or warning on the hexpm side.)

Ultimately, we might end up having to show the source code for each release in Hex. This is probably the only way to really know what you are downloading.

@zachdaniel BTW - thank you for bringing this up. Security is a big issue and we need to get creative on ways to mitigate those problems.

**Comment by ericmj** [comment]
> Ultimately, we might end up having to show the source code for each release in Hex. This is probably the only way to really know what you are downloading.

Yes! Something similar to diff.hex.pm that lets you browse the package contents directly would be great.

**Comment by zachdaniel** [comment]
If we make a source code browser in hex (or as a separate service integrated with hex), I fear that no one will really use it. Yes, it *could* be used to verify what you're downloading, but what I really liked about having some kind of "what is on GH is correct" check is that its a much simpler comfort. 

"The source code of what is published on hex, matches the publically available source code on github." I'm not suggesting that my original idea makes sense, just emphasizing the spirit of it.

**Comment by supersimple** [comment]
@zachdaniel I think I agree with your sentiment. There are existing tools if a user is inclined to verify the package is indeed identical to what is on Github. What we have been trying to do is to surface those tools and make them as easy and obvious as possible.
what comes to my mind is - given we have some service to verify the code, we put a check mark next to the github link on the hexpm page or something similar. Or, there is a badge on the github readme that indicates the same.
Hex doesn't insist on parity, so I dont think we'd ever want to indicate that something is wrong when parity does not exist, but we walk a fine line since we display links to the source control page. Some people might take this as tacit verification of it's quality.
I think there is a feature in here somewhere. Please let us know what actionable ideas you might have.

**Comment by kitplummer** [comment]
Kinda parallel to this thread, but I was hoping to be able to do some manual validation by simply following the _source_url_ element from an API query.  But alas, no _source_url_ element is returned.  There is the arbitrary "Links" list but I don't see that as "official" as the source_url.  Is there a reason the Web and API views don't display/return the _source_url_ field?

**Comment by ericmj** [comment]
`source_url` is not part of the package metadata. We have `links` in the metadata instead which is more flexible.

**Comment by kitplummer** [comment]
But flexible in terms of validating/verifying a package (and source code) is not a good thing IMO.  
For example here's `plug`:

```json
{
  "docs_html_url": "https://hexdocs.pm/plug/",
  "downloads": {
    "all": 19344022,
    "day": 67830,
    "recent": 2916575,
    "week": 307736
  },
  "html_url": "https://hex.pm/packages/plug",
  "inserted_at": "2014-04-23T18:58:52.000000Z",
  "meta": {
    "description": "A specification and conveniences for composable modules between web applications",
    "licenses": [
      "Apache-2.0"
    ],
    "links": {
      "GitHub": "https://github.com/elixir-plug/plug"
    },
    "maintainers": []
  },
  "name": "plug",
  "owners": [
    {
      "email": "jose.valim@gmail.com",
      "url": "https://hex.pm/api/users/josevalim",
      "username": "josevalim"
    },
    {
      "email": "eric.meadows.jonsson@gmail.com",
      "url": "https://hex.pm/api/users/ericmj",
      "username": "ericmj"
    },
    {
      "email": "gazler@gmail.com",
      "url": "https://hex.pm/api/users/gazler",
      "username": "gazler"
    }
  ],
  "releases": [
    {
      "has_docs": true,
      "inserted_at": "2020-02-07T09:10:56.491446Z",
      "url": "https://hex.pm/api/packages/plug/releases/1.9.0",
      "version": "1.9.0"
    },
...
   {
      "has_docs": false,
      "inserted_at": "2014-04-23T18:58:54.000000Z",
      "url": "https://hex.pm/api/packages/plug/releases/0.4.1",
      "version": "0.4.1"
    }
  ],
  "repository": "hexpm",
  "retirements": {},
  "updated_at": "2020-02-07T09:11:00.368643Z",
  "url": "https://hex.pm/api/packages/plug"
}
```

If you're going to actually do verification against source control, it needs to be a "standardized" field, not something that is optional - as a starting point.

**Comment by ericmj** [comment]
Yes, if we do add some kind of source control checks to Hex would probably standardize that URL.

**Comment by ericmj** [comment]
We are not planning to go ahead with this due to the difficulties and drawbacks outlined above. The goal is that services like https://diff.hex.pm/ and https://preview.hex.pm/ will solve these issues instead.
