### ISSUE TITLE
Private account dashboard returning 500

### ISSUE THREAD

**Issue by brunoripa** [hexpm/hexpm#899]
Hi,
  
   it's a bunch of days that our organisation cannot access the packages dashboard, we have a huge "500 error" message error.

Apparently the package repository is working (though we see some failures in packages updates, we must point to specific new build version of our packages). Anything going on ?

**Comment by ericmj** [comment]
Please contact support@hex.pm and include your organization name and we will look at it.

**Comment by brunoripa** [comment]
Done, thanks @ericmj
