### ISSUE TITLE
Bad download count on private packages 

### ISSUE THREAD

**Issue by rodrigues** [hexpm/hexpm#907]
<img width="746" alt="Screenshot 2020-02-14 at 00 47 11" src="https://user-images.githubusercontent.com/128147/74488771-8aa6d500-4ec3-11ea-95a9-b167631c7472.png">

On all private packages the download counters are all zero, even if we've downloaded things.

Maybe better not show for private packages? Not sure, as I don't know the whole scope of things, but letting you know.

By the way, reporting these two minor things, but our experience last few months with private packages has been amazing 👌

**Comment by ericmj** [comment]
This is definitely a bug, I will look into it.

> By the way, reporting these two minor things, but our experience last few months with private packages has been amazing 👌

That is great, love to hear that. Thank you for reporting the issues, even if they are minor, it will make the service better overall.
