### ISSUE TITLE
hex.outdated makes reference to the color of the text, which does not work on windows

### ISSUE THREAD

**Issue by supersimple** [hexpm/hexpm#918]
mix hex.outdated states "A green requirement means ..." however colors are not supported on Windows.
We should either:
1. give windows colors (not that easy)
2. remove references to colors
3. make alternate text just for windows users.

**Comment by ericmj** [comment]
We should be able to do the same check IO.ANSI.format does to determine if colors are being output and in those cases not show the message about colors. Alternatively, we should not rely on colors and instead add a column that says if the requirement allows upgrades.
