### ISSUE TITLE
Add link to login on 404 page

### ISSUE THREAD

**Issue by rodrigues** [hexpm/hexpm#922]
When I open a private package page (e.g. https://hex.pm/packages/ORG/PACKAGE), and for some reason I got logged out of hex.pm, I get a 404 not found.

It would be nice if there was a link to login from that page (or show session indicator), so I could better distinguish a 404 from an access issue, and easily login and get back to that page.

Thanks!

**Comment by supersimple** [comment]
Thank you for the suggestion @rodrigues .
If you would like to work on this, take a look at the error_view. It uses the simple_header, where most of the site uses header. The difference is that header expects to have @current_user set.

**Comment by supersimple** [comment]
Closed by PR #930
