### ISSUE TITLE
Pagination on package history (URL path: .../audit_logs?page=x) seems to be broken

### ISSUE THREAD

**Issue by akaibukai** [hexpm/hexpm#925]
Hello,
The pagination on the pages showing the history of a package seems to be broken as they display the same data.
Example:
https://hex.pm/packages/ex_money/audit_logs?page=1
https://hex.pm/packages/ex_money/audit_logs?page=2
https://hex.pm/packages/ex_money/audit_logs?page=3
All of these pages show the same history while the pagination itself correctly updates.

**Comment by akaibukai** [comment]
I think I found the bug [on that line](https://github.com/hexpm/hexpm/blob/7a11c7dfe0e54c873638445f7642352d10cdc2c8/lib/hexpm_web/controllers/package_controller.ex#L77).
It is:
```elixir
audit_logs = AuditLogs.all_by(package, 1, 100)
```
It should be:
```elixir
audit_logs = AuditLogs.all_by(package, page, 100)
```

**Comment by wojtekmach** [comment]
Thank you for the report and finding root cause!
