### ISSUE TITLE
Typo in HexDocs -> Module -> String -> Integer code points

### ISSUE THREAD

**Issue by sanjib** [hexpm/hexpm#941]
URL: https://hexdocs.pm/elixir/String.html#module-integer-code-points

Typo:
you can call Strig.to_charlist:

Should be:
you can call String.to_charlist:

**Comment by wojtekmach** [comment]
hexpm is concerned with hosting the docs, not with the contents of the docs themselves. Could you send a PR to elixir-lang/elixir with the fix?

**Comment by sanjib** [comment]
Thanks, will do.
