### ISSUE TITLE
Show useful stats in Owned packages

### ISSUE THREAD

**Issue by jung-hunsoo** [hexpm/hexpm#942]
Currently only package name and version are shown in the list of owned packages.

And it'd be better to show more useful fields like `downloads count` and `release date`.

Since they're already provided in the detail page, it wouldn't be so hard to implement.

**Comment by supersimple** [comment]
![image](https://user-images.githubusercontent.com/773380/86997040-62698c80-c16a-11ea-943a-a7e45861f401.png)
![image](https://user-images.githubusercontent.com/773380/86997066-6c8b8b00-c16a-11ea-8ec3-b017cd7da1be.png)

Here are some examples from NPM and Rubygems, respectively.
I do like the additional context for the packages, and my opinion Rubygems presents it better.
WDYT @jung-hunsoo @ericmj @wojtekmach ?

**Comment by ericmj** [comment]
I prefer the rubygem presentation but I also like that npm includes the package description in the listing.

**Comment by jung-hunsoo** [comment]
@supersimple Thanks for the improvement.

Though I prefer simple style, both looks file. It's also possible to choose the layout by users; simple and full.

One thing is, the `published` label in npm is repetitive and less informative.

**Comment by supersimple** [comment]
@jung-hunsoo so, let's go with:name, description, latest version, and total downloads for each package.

**Comment by jung-hunsoo** [comment]
@supersimple Great. Should be `hexpm/lib/hexpm_web/templates/user/show.html.eex` template, right?

If you need I can create a PR, but I think you have much better understanding of this site's UX than me.

**Comment by supersimple** [comment]
@jung-hunsoo yes, that is the file. 
I'd love to have you work on it if you can. I'm happy to answer questions and collaborate if you'd like.
If not, no worries.
