### ISSUE TITLE
Underscores (_) in documentation not treated as word break in search

### ISSUE THREAD

**Issue by dotdotdotpaul** [hexpm/hexpm#943]
Example:

If you go to the [Phoenix PubSub docs](https://hexdocs.pm/phoenix_pubsub/Phoenix.PubSub.html) and search for "pool" you get exactly one result, which is in the Phoenix.Tracker behaviour, and that's probably not what you were looking for.

However, search for `pool_size` and you add the Phoenix.PubSub.child_spec function to the list, and that's _probably_ what you were looking for.

Expected (Requested?) Behavior:

Seems like when searching, underscores in the source material should be treated as word breaks so that you can match on "partial underscores", useful for searching for configuration elements (which are often snake-cased, like this one).  So a search for "pool" should bring up matches on `pool_size` as well as `pools` and `use_pool?` (I made up the last one as an example).

Preferably, if the input search term has an underscore, the underscore should match underscores (so searching for "pool_size" only matches `pool_size` and/or `max_pool_size`, but not `pool size`

**Comment by ericmj** [comment]
Please open this issue on: https://github.com/elixir-lang/ex_doc

**Comment by dotdotdotpaul** [comment]
My bad, I thought it was powered by hexdocs.pm's service(s).
