### ISSUE TITLE
`mix hex.info` shows a retired version as the latest

### ISSUE THREAD

**Issue by zachdaniel** [hexpm/hexpm#947]
I accidentally published a 1.0.0 version of my package here: https://hex.pm/packages/ash. It isn't at 1.0 and won't be any time soon. I retired the release, which is pretty clear on its verbiage in most places, however the `Config` section shows `{:ash, "~> 1.0"}`. I think it would be clearer if that shows the latest *non-revoked* version. (also, if its possible for someone to take that 1.0 package down, that would be great. I'm 100% sure that I'm the only person using it right now :D)

**Comment by ericmj** [comment]
Retired package versions are informational only, they do not change if the package version is resolved or not, that's why it still shows up in hex.info and in the version requirement.

A package can be retired for many reasons and a retired version does not necessarily mean that it shouldn't be used at all. When the retired version is resolved the user will be informed and it's then up to the user if they want to use the package or not.

**Comment by zachdaniel** [comment]
I totally understand that packages being retired is a “symbolic/informal” action, but to me the `Config` section is also informal. It’s a “recommendation”. What about making a way to configure for a package what the recommended version is? I don’t want users to see that and think they should use 1.0.0.

No worries if not, just wanted to put forth my take on it. Thanks for your time :)

**Comment by wojtekmach** [comment]
“Latest” release has a special meaning (that we are trying to consistently apply across Hex codebase but might not be there yet), and that it is a latest stable (not pre-release) version. We use „latest” eg in:

- which version to show when you go to hex.pm/packages/foo
- which version to show when you go to hex.pm/packages/foo

we also have plans to have `mix hex.package fetch foo`.

So this notion of „latest” is used in at least a few places and it is important to be consistent so it works predictably.

I personally would be in favor of including non-retired in the definition of “latest” and I thought we already did that (maybe I’m we did in just some places)

**Comment by ericmj** [comment]
We shouldn't exclude retired versions from "latest" unless we also exclude them when resolving which is a related but separate discussion.

**Comment by wojtekmach** [comment]
Good point.

**Comment by zachdaniel** [comment]
I think the issue that I'm faced with is actually a problem. Seems like a potential solution would be to let the package maintainer choose a version to be their recommended version for things like `hex.pm/packages/foo` and `Config: {:package, version}`. I will most likely not release my package's real 1.0.0 version for like...a year or more. It's my fault, but it is still very problematic that hex will be showing them this version. I anticipate this will cause a fair amount of wasted time and confusion.

**Comment by ericmj** [comment]
I am not sure how much confusion it will cause, we should show the package version as retired almost everywhere. Another thing you can do is release 2.0.0.

**Comment by zachdaniel** [comment]
I guess it would be a lesser of the two evils for me to just bump to 1.0.1 and explain on my readme that “even though we’re past version 1.0.0, this package is not stable yet”

**Comment by zachdaniel** [comment]
Alright I’ll leave it as is, and if people encounter issues I’ll just release a new version. Thanks for bearing with me!
