### ISSUE TITLE
Prompt for personal/company information when creating organization

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#977]
Without this information we cannot start the trialed subscription. Another alternative is to not require this information until payment details are required but that would require changes to the billing system.

**Comment by supersimple** [comment]
@ericmj what personal/company info do we need? and where should it be stored?

**Comment by supersimple** [comment]
Everything in this section?
![Screenshot from 2020-11-19 10-37-19](https://user-images.githubusercontent.com/773380/99702599-3a146780-2a53-11eb-8d93-a2ccf7ab0eb1.png)

**Comment by ericmj** [comment]
Yes, we should show that form before the organization is created. We can move it to a partial so it can be displayed in both locations.

**Comment by ericmj** [comment]
This is no longer needed since we always start the trial for private packages when creating an organization now.
