### ISSUE TITLE
Invalid certificate for hex.pm

### ISSUE THREAD

**Issue by safwank** [hexpm/hexpm#980]
I'm getting an invalid certificate error (`NET::ERR_CERT_COMMON_NAME_INVALID`) when viewing the website. Looking at the cert, it looks like it's meant for redesign.hex.pm, not hex.pm.

![image](https://user-images.githubusercontent.com/510124/99447318-4b864280-2973-11eb-80fe-b9646b4e8a97.png)

**Comment by ericmj** [comment]
It was a temporary certificate issue. It has been resolved now.
