### ISSUE TITLE
Invalid SSL Cert on hex.pm?

### ISSUE THREAD

**Issue by dkarter** [hexpm/hexpm#981]
Just tried to access https://hex.pm and got this
<img width="2672" alt="CleanShot 2020-11-17 at 14 52 36@2x" src="https://user-images.githubusercontent.com/551858/99447385-d2400e80-28e4-11eb-9ffa-3b62923b75bf.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/551858/99448142-05829d80-28e5-11eb-935a-4dc9973d4284.png">

https://redesign.hex.pm works.. it appears the SSL cert would need to be generated with support for both `redesign.hex.pm` and the bare domain `hex.pm`.

Thank you and please let me know if there's any way I can help!

**Comment by ericmj** [comment]
It was a temporary certificate issue. It has been resolved now.
