### ISSUE TITLE
How do I run this thing? (Preferably as a Docker container)

### ISSUE THREAD

**Issue by prologic** [hexpm/hexpm#992]
Hey guys!

Trying to figure out how to run this thing (_preferably as a Docker container_).

So far I've built the Docker Image (_ssuccessfully_), now I'm trying to figure out how to actually run it. I'm a complete Erlang / Exlir n00b so I know nothing about the ecosystem let alone best practices.

So far I'm running into basic things that wouldn't be an issue if there was a "zero config" mode; e.g:

```#!sh
/app $ ./bin/hexpm start_iex
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1]

ERROR! Config provider Config.Reader failed with:
** (ArgumentError) could not fetch environment variable "HEXPM_HOST" because it is not set
    (elixir 1.11.0) lib/system.ex:529: System.fetch_env!/1
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.13.2) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.13.2) erl_eval.erl:240: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.13.2) erl_eval.erl:411: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:126: :erl_eval.exprs/5

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"HEXPM_HOST\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,529}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,240}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,411}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]}]}}
init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eva

Crash dump is being written to: erl_crash.dump...done
/app $
```

I have no idea what `HEXPM_HOST` is yet but I'll poke around the codebase and see if I can get past this...

**Comment by prologic** [comment]
So I can get past the missing `HEXPM_HOST` and `HEXPM_PORT` env vars, but now I'm at a missing `SECRET_KEY_BASE` which I have absolutely no idea about. None of this seems to be documented anywhere and there are very few references in code so its quite hard to tell what these values are or should be:

```#!sh
/app $ HEXPM_HOST=0.0.0.0 HEXPM_PORT=4000 ./bin/hexpm start_iex
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1]

ERROR! Config provider Config.Reader failed with:
** (ArgumentError) could not fetch environment variable "HEXPM_SECRET_KEY_BASE" because it is not set
    (elixir 1.11.0) lib/system.ex:529: System.fetch_env!/1
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.13.2) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.13.2) erl_eval.erl:240: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:233: :erl_eval.expr/5
    (stdlib 3.13.2) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.13.2) erl_eval.erl:411: :erl_eval.expr/5

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"HEXPM_SECRET_KEY_BASE\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,529}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,240}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,411}]}]}}
init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eva

Crash dump is being written to: erl_crash.dump...done
/app $
```

**Comment by wojtekmach** [comment]
> but now I'm at a missing SECRET_KEY_BASE which I have absolutely no idea about. None of this seems to be documented anywhere and there are very few references in code so its quite hard to tell what these values are or should be:

The reference is here:

https://github.com/hexpm/hexpm/blob/b06a5c9e8ab8f830dc3802d82ff898ccd98a9fd4/config/runtime.exs#L4:L7

and since we happen to be configuring the app itself I'd search for `Application.get_env,fetch_enc` in our codebase. You'd then find https://github.com/hexpm/hexpm/blob/b06a5c9e8ab8f830dc3802d82ff898ccd98a9fd4/lib/hexpm_web/endpoint.ex#L68 which means we're configuring the Phoenix.Endpoint and you can find more docs here: https://hexdocs.pm/phoenix/Phoenix.Endpoint.html?#module-runtime-configuration

Hope that helps for following the breadcrumbs in the future! I'd also check out the https://hexdocs.pm/phoenix/deployment.html in general and https://hexdocs.pm/phoenix/releases.html in particular.

**Comment by wojtekmach** [comment]
I'm gonna go ahead and close it as I'm not sure what are the next steps. Feel free to continue the conversation though.

Out of curiosity, do you need to run a full hexpm service, or do you just want a basic Hex package hosting? If the latter, check out https://github.com/hexpm/hexpm/pull/993 & https://github.com/hexpm/hex/pull/836.

**Comment by prologic** [comment]
The latter, thanks will check that out 👌
