### ISSUE TITLE
Docs are not published

### ISSUE THREAD

**Issue by ahamez** [hexpm/hexpm#998]
I've published today (2021-01-24) a new version (1.3.1) of [protox](https://github.com/ahamez/protox).

However, the documentation for this version is not available (https://hexdocs.pm/protox/1.3.1), it fails with a 404, even though the local documentation `doc/index.html` is correctly generated for this version.
Only the previous version is available (https://hexdocs.pm/protox/1.3.0).

The command `mix hex.publish` does not report any error. I've tried to publish documentation directly using `mix hex.publish docs`, but it does not report any error as well:
```
$ mix hex.publish docs
Compiling 24 files (.ex)
Generated protox app
Generating docs...
View "html" docs at "doc/index.html"
View "epub" docs at "doc/Protox.epub"
Local password:
[#########################] 100%
Docs published to https://hexdocs.pm/protox/1.3.1
```

Finally, it seems this problem is encountered by all packages published at least today, the latest version of their documentation is not available.

**Comment by ericmj** [comment]
Thanks for the report, the issue has been fixed.
